# ASCON-AEAD-128 CNN256 Top-k Model Training, All 16 Bytes

This notebook trains byte-wise 256-class key-byte classifiers for the ASCON-AEAD-128 tight-trigger dataset.

It is prepared for your usual Windows PC with CUDA/GPU training.

Folder policy used in this notebook:

```text
Traces only:
C:\Users\thetp\Downloads\ASCON_FYP\03_Data

Model training results:
C:\Users\thetp\Downloads\ASCON_FYP\04_Results

Model checkpoints:
C:\Users\thetp\Downloads\ASCON_FYP\05_Models
```

Main outputs:

```text
Single trace: Top1, Top2, Top4, Top8, Top16, Top32
Grouped trace: grouped_n1, grouped_n2, grouped_n4, grouped_n8, grouped_n12, grouped_n16
Per-byte model checkpoints
Per-byte summaries
All-byte summary
Candidate-space reduction summary
```

## 1. Environment and CUDA Check

In [1]:
import sys
import platform
import torch

print("Python executable:", sys.executable)
print("Python version:", sys.version)
print("Platform:", platform.platform())
print("PyTorch version:", torch.__version__)
print("PyTorch CUDA version:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU count:", torch.cuda.device_count())
else:
    print("WARNING: CUDA is not available. Training will run on CPU and will be much slower.")

Python executable: C:\Users\thetp\anaconda3\envs\acorn_train\python.exe
Python version: 3.11.15 | packaged by Anaconda, Inc. | (main, Mar 11 2026, 17:12:15) [MSC v.1942 64 bit (AMD64)]
Platform: Windows-10-10.0.26200-SP0
PyTorch version: 2.11.0+cu128
PyTorch CUDA version: 12.8
CUDA available: True
GPU: NVIDIA GeForce RTX 3070
GPU count: 1

## 2. Imports

In [2]:
from pathlib import Path
from datetime import datetime
import math
import random
import time
import gc
import json
import os

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

try:
    from tqdm.auto import tqdm
    TQDM_AVAILABLE = True
except Exception:
    TQDM_AVAILABLE = False

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 220)

## 3. Configuration

In [3]:
# ============================================================
# Project paths
# ============================================================
PROJECT_ROOT = Path(r"C:\Users\thetp\Downloads\ASCON_FYP")

# Traces only
DATA_BASE = PROJECT_ROOT / r"03_Data\tight_trigger_keybyte_auto30k"

# Results and model checkpoints
RESULTS_BASE = PROJECT_ROOT / r"04_Results\ascon_cnn256_topk_training"
MODELS_BASE = PROJECT_ROOT / r"05_Models\ascon_cnn256_topk_training"

# If None, the notebook auto-detects the newest dataset folder under DATA_BASE.
# You can also set it manually, for example:
# DATASET_RUN_NAME = "ascon_tighttrigger_30k_per_byte_20260526_011623"
DATASET_RUN_NAME = None

# If None, a new timestamped training run folder is created.
# If you want to resume a specific previous run, set it manually.
RUN_ID = datetime.now().strftime("run_%Y%m%d_%H%M%S")

RESULTS_ROOT = RESULTS_BASE / RUN_ID
MODELS_ROOT = MODELS_BASE / RUN_ID
RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
MODELS_ROOT.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_BASE:", DATA_BASE)
print("RESULTS_ROOT:", RESULTS_ROOT)
print("MODELS_ROOT:", MODELS_ROOT)

# ============================================================
# Byte selection
# ============================================================
RUN_ALL_BYTES = True
TARGET_BYTE = 0
BYTES_TO_TRAIN = list(range(16)) if RUN_ALL_BYTES else [TARGET_BYTE]

# If True, skip byte if its per-byte summary already exists in this RUN_ID.
SKIP_COMPLETED_BYTES = True

# ============================================================
# Top-k and grouped settings
# ============================================================
TOPK_VALUES = (1, 2, 4, 8, 16, 32)
GROUP_SIZES = (1, 2, 4, 8, 12, 16)

# ============================================================
# Data split settings
# ============================================================
SEED = 42
TEST_SIZE_TOTAL = 0.30       # 70% train, 30% temporary
VAL_SIZE_FROM_TEMP = 0.50    # 15% val, 15% test

# ============================================================
# Training settings
# ============================================================
EPOCHS = 80
BATCH_SIZE = 128
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
LABEL_SMOOTHING = 0.03
EARLY_STOPPING_PATIENCE = 15
GRAD_CLIP_NORM = 1.0

# If RTX 3070 8GB runs out of memory, change BATCH_SIZE to 64.
# BATCH_SIZE = 64

# ============================================================
# Augmentation settings
# ============================================================
USE_AUGMENTATION = True
AUG_SHIFT_MAX = 4
AUG_NOISE_STD = 0.005
AUG_SCALE_STD = 0.02

# ============================================================
# Saving settings
# ============================================================
SAVE_SPLIT_MAPPING = True
SAVE_TOP32_PREDICTIONS = True
SAVE_CONFIG_COPY = True

# ============================================================
# Device
# ============================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

set_seed(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"
PIN_MEMORY = True if device == "cuda" else False

print("Device:", device)
print("Bytes to train:", BYTES_TO_TRAIN)

PROJECT_ROOT: C:\Users\thetp\Downloads\ASCON_FYP
DATA_BASE: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k
RESULTS_ROOT: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605
MODELS_ROOT: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605
Device: cuda
Bytes to train: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

## 4. Locate and Verify Dataset Folder

In [4]:
def find_byte_files(byte_dir: Path, target_byte: int):
    """Return trace/meta files using the common naming patterns."""
    patterns_trace = [
        f"byte{target_byte:02d}_chunk_*_traces.npz",
        f"ascon_byte{target_byte:02d}_chunk_*_traces.npz",
        "*_traces.npz",
    ]
    patterns_meta = [
        f"byte{target_byte:02d}_chunk_*_metadata.csv",
        f"ascon_byte{target_byte:02d}_chunk_*_metadata.csv",
        "*_metadata.csv",
    ]

    trace_files = []
    meta_files = []

    for pat in patterns_trace:
        trace_files = sorted(byte_dir.glob(pat))
        if trace_files:
            break

    for pat in patterns_meta:
        meta_files = sorted(byte_dir.glob(pat))
        if meta_files:
            break

    return trace_files, meta_files


def dataset_score(folder: Path):
    """Score a possible ASCON dataset folder.

    Supports both layouts:
    1. DATA_BASE / ascon_tighttrigger_30k_per_byte_YYYYMMDD_HHMMSS / byte_00 / files
    2. DATA_BASE / byte_00 / files
    """
    if not folder.exists() or not folder.is_dir():
        return None

    if "PLACEHOLDER" in folder.name.upper():
        return None

    total_trace_files = 0
    total_meta_files = 0
    total_meta_rows = 0
    bytes_with_data = 0

    for b in range(16):
        byte_dir = folder / f"byte_{b:02d}"
        if not byte_dir.exists() or not byte_dir.is_dir():
            continue

        trace_files, meta_files = find_byte_files(byte_dir, b)
        total_trace_files += len(trace_files)
        total_meta_files += len(meta_files)

        byte_meta_rows = 0
        for mf in meta_files:
            try:
                byte_meta_rows += len(pd.read_csv(mf))
            except Exception:
                pass

        total_meta_rows += byte_meta_rows

        if len(trace_files) > 0 and len(meta_files) > 0 and byte_meta_rows > 0:
            bytes_with_data += 1

    return {
        "folder": folder,
        "bytes_with_data": bytes_with_data,
        "total_trace_files": total_trace_files,
        "total_meta_files": total_meta_files,
        "total_meta_rows": total_meta_rows,
    }


def autodetect_dataset_root():
    candidates = []

    # Candidate 1: DATA_BASE itself, if byte_00 is directly inside it.
    score = dataset_score(DATA_BASE)
    if score is not None:
        candidates.append(score)

    # Candidate 2: one-level child run folders.
    for p in sorted(DATA_BASE.iterdir() if DATA_BASE.exists() else []):
        score = dataset_score(p)
        if score is not None:
            candidates.append(score)

    if not candidates:
        raise FileNotFoundError(
            f"No valid ASCON dataset found under {DATA_BASE}.\n"
            "Expected either:\n"
            f"  {DATA_BASE}\\byte_00\\...\n"
            "or:\n"
            f"  {DATA_BASE}\\ascon_tighttrigger_30k_per_byte_YYYYMMDD_HHMMSS\\byte_00\\..."
        )

    candidate_df = pd.DataFrame([
        {
            "folder": str(c["folder"]),
            "bytes_with_data": c["bytes_with_data"],
            "total_trace_files": c["total_trace_files"],
            "total_meta_files": c["total_meta_files"],
            "total_meta_rows": c["total_meta_rows"],
        }
        for c in candidates
    ]).sort_values(["bytes_with_data", "total_meta_rows", "total_trace_files"], ascending=False)

    print("Dataset candidates found:")
    display(candidate_df)

    best_folder = Path(candidate_df.iloc[0]["folder"])
    return best_folder


# If DATASET_RUN_NAME is None, auto-detect the real dataset and ignore PLACEHOLDER folders.
# If your byte_00...byte_15 folders are directly inside DATA_BASE, this will use DATA_BASE.
# If they are inside a timestamped run folder, this will use that run folder.
if DATASET_RUN_NAME is None:
    DATASET_ROOT = autodetect_dataset_root()
else:
    DATASET_ROOT = DATA_BASE / DATASET_RUN_NAME

print("Using dataset root:", DATASET_ROOT)

# Quick file count verification.
rows = []
for b in range(16):
    byte_dir = DATASET_ROOT / f"byte_{b:02d}"
    trace_files, meta_files = find_byte_files(byte_dir, b)

    meta_rows = 0
    for mf in meta_files:
        try:
            meta_rows += len(pd.read_csv(mf))
        except Exception:
            pass

    rows.append({
        "byte": b,
        "byte_dir": str(byte_dir),
        "trace_chunks": len(trace_files),
        "metadata_chunks": len(meta_files),
        "metadata_rows": meta_rows,
        "expected_rows": 30000,
        "looks_ok": len(trace_files) == len(meta_files) and meta_rows == 30000,
    })

verify_df = pd.DataFrame(rows)
verify_path = RESULTS_ROOT / "dataset_quick_verification_before_training.csv"
verify_df.to_csv(verify_path, index=False)
print("Saved quick verification:", verify_path)
display(verify_df)

if not verify_df["looks_ok"].all():
    print("WARNING: Some bytes may not have 30 chunks / 30,000 rows. Check before training all bytes.")

Dataset candidates found:

                                              folder  bytes_with_data  total_trace_files  total_meta_files  total_meta_rows
2  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...               16                480               480           480000
1  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...                1                  1                 1              100
0  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...                0                  0                 0                0

Using dataset root: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007
Saved quick verification: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\dataset_quick_verification_before_training.csv

    byte                                           byte_dir  trace_chunks  metadata_chunks  metadata_rows  expected_rows  looks_ok
0      0  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
1      1  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
2      2  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
3      3  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
4      4  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
5      5  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
6      6  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
7      7  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
8      8  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
9      9  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
10    10  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
11    11  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
12    12  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
13    13  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
14    14  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True
15    15  C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tig...            30               30          30000          30000      True

## 5. Save Training Configuration

In [5]:
training_config = {
    "project_root": str(PROJECT_ROOT),
    "dataset_root": str(DATASET_ROOT),
    "results_root": str(RESULTS_ROOT),
    "models_root": str(MODELS_ROOT),
    "bytes_to_train": BYTES_TO_TRAIN,
    "topk_values": TOPK_VALUES,
    "group_sizes": GROUP_SIZES,
    "seed": SEED,
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "learning_rate": LEARNING_RATE,
    "weight_decay": WEIGHT_DECAY,
    "label_smoothing": LABEL_SMOOTHING,
    "early_stopping_patience": EARLY_STOPPING_PATIENCE,
    "use_augmentation": USE_AUGMENTATION,
    "aug_shift_max": AUG_SHIFT_MAX,
    "aug_noise_std": AUG_NOISE_STD,
    "aug_scale_std": AUG_SCALE_STD,
    "device": device,
    "run_id": RUN_ID,
}

config_path = RESULTS_ROOT / "training_config.json"
config_path.write_text(json.dumps(training_config, indent=2), encoding="utf-8")
print("Saved config:", config_path)

Saved config: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\training_config.json

## 6. Data Loading Functions

In [6]:
def get_byte_files(dataset_root: Path, target_byte: int):
    byte_dir = dataset_root / f"byte_{target_byte:02d}"

    trace_patterns = [
        f"byte{target_byte:02d}_chunk_*_traces.npz",
        f"ascon_byte{target_byte:02d}_chunk_*_traces.npz",
        "*_traces.npz",
    ]
    meta_patterns = [
        f"byte{target_byte:02d}_chunk_*_metadata.csv",
        f"ascon_byte{target_byte:02d}_chunk_*_metadata.csv",
        "*_metadata.csv",
    ]

    trace_files = []
    meta_files = []
    for pat in trace_patterns:
        trace_files = sorted(byte_dir.glob(pat))
        if trace_files:
            break
    for pat in meta_patterns:
        meta_files = sorted(byte_dir.glob(pat))
        if meta_files:
            break

    if not trace_files:
        raise FileNotFoundError(f"No trace npz files found for byte {target_byte:02d} in {byte_dir}")
    if not meta_files:
        raise FileNotFoundError(f"No metadata csv files found for byte {target_byte:02d} in {byte_dir}")

    if len(trace_files) != len(meta_files):
        raise ValueError(f"Chunk count mismatch for byte {target_byte:02d}: traces={len(trace_files)}, metadata={len(meta_files)}")

    return byte_dir, trace_files, meta_files


def load_byte_dataset(dataset_root: Path, target_byte: int):
    byte_dir, trace_files, meta_files = get_byte_files(dataset_root, target_byte)

    print(f"\nLoading ASCON byte {target_byte:02d}")
    print("Byte dir:", byte_dir)
    print("Trace chunks:", len(trace_files))
    print("Metadata chunks:", len(meta_files))

    X_list = []
    meta_list = []

    for tf, mf in zip(trace_files, meta_files):
        with np.load(tf) as npz:
            if "traces" in npz.files:
                traces = npz["traces"]
            else:
                traces = npz[npz.files[0]]

        meta = pd.read_csv(mf)

        if len(traces) != len(meta):
            raise ValueError(f"Row mismatch: {tf.name} has {len(traces)} traces but {mf.name} has {len(meta)} rows")

        X_list.append(traces.astype(np.float32, copy=False))
        meta_list.append(meta)

    X = np.vstack(X_list).astype(np.float32, copy=False)
    meta = pd.concat(meta_list, ignore_index=True)

    required_cols = ["target_byte", "key_hex", "key_byte_value", "key_byte_hex", "key_byte_hw"]
    missing = [c for c in required_cols if c not in meta.columns]
    if missing:
        raise KeyError(f"Missing metadata columns for byte {target_byte:02d}: {missing}")

    y = meta["key_byte_value"].astype(np.int64).values

    # Basic label sanity check.
    bad = 0
    for i, row in meta.head(min(5000, len(meta))).iterrows():
        kh = str(row["key_hex"])
        tb = int(row["target_byte"])
        kv = int(row["key_byte_value"])
        if len(kh) >= (tb * 2 + 2):
            kv_from_key = int(kh[tb*2:tb*2+2], 16)
            if kv_from_key != kv:
                bad += 1
    if bad > 0:
        print(f"WARNING: Found {bad} key label mismatches in first checked rows for byte {target_byte:02d}")

    print("X shape:", X.shape)
    print("y shape:", y.shape)
    print("Class count:", len(np.unique(y)))
    print("Trace dtype:", X.dtype)

    return X, y, meta


def safe_stratify_labels(y, min_count_required=2):
    values, counts = np.unique(y, return_counts=True)
    if len(values) < 2:
        return None
    if counts.min() < min_count_required:
        print("Warning: disabling stratify because at least one class has too few samples.")
        return None
    return y


def preprocess_and_split(X, y, seed=42):
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0).astype(np.float32, copy=False)

    # Remove per-trace DC offset.
    X = X - X.mean(axis=1, keepdims=True)

    indices = np.arange(len(y))
    stratify_y = safe_stratify_labels(y, min_count_required=3)

    X_train, X_temp, y_train, y_temp, idx_train, idx_temp = train_test_split(
        X, y, indices,
        test_size=TEST_SIZE_TOTAL,
        random_state=seed,
        stratify=stratify_y,
    )

    stratify_temp = safe_stratify_labels(y_temp, min_count_required=2)

    X_val, X_test, y_val, y_test, idx_val, idx_test = train_test_split(
        X_temp, y_temp, idx_temp,
        test_size=VAL_SIZE_FROM_TEMP,
        random_state=seed,
        stratify=stratify_temp,
    )

    # Standardize per sample point using train statistics only.
    mean = X_train.mean(axis=0, keepdims=True).astype(np.float32)
    std = (X_train.std(axis=0, keepdims=True) + 1e-6).astype(np.float32)

    X_train = ((X_train - mean) / std).astype(np.float32, copy=False)
    X_val = ((X_val - mean) / std).astype(np.float32, copy=False)
    X_test = ((X_test - mean) / std).astype(np.float32, copy=False)

    print("Train:", X_train.shape, y_train.shape)
    print("Val:  ", X_val.shape, y_val.shape)
    print("Test: ", X_test.shape, y_test.shape)

    return X_train, X_val, X_test, y_train, y_val, y_test, idx_train, idx_val, idx_test, mean, std

## 7. Dataset Class

In [7]:
class TraceDataset(Dataset):
    def __init__(self, X, y, augment=False):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)
        self.augment = augment

    def __len__(self):
        return len(self.y)

    def _augment_trace(self, x):
        if AUG_SHIFT_MAX and AUG_SHIFT_MAX > 0:
            shift = int(torch.randint(-AUG_SHIFT_MAX, AUG_SHIFT_MAX + 1, (1,)).item())
            if shift != 0:
                x = torch.roll(x, shifts=shift, dims=0)

        if AUG_SCALE_STD and AUG_SCALE_STD > 0:
            scale = 1.0 + torch.randn(1).item() * AUG_SCALE_STD
            x = x * scale

        if AUG_NOISE_STD and AUG_NOISE_STD > 0:
            x = x + torch.randn_like(x) * AUG_NOISE_STD

        return x

    def __getitem__(self, idx):
        x = self.X[idx]
        y = self.y[idx]
        if self.augment:
            x = self._augment_trace(x)
        return x.unsqueeze(0), y


def make_loaders(X_train, X_val, X_test, y_train, y_val, y_test):
    train_ds = TraceDataset(X_train, y_train, augment=USE_AUGMENTATION)
    val_ds = TraceDataset(X_val, y_val, augment=False)
    test_ds = TraceDataset(X_test, y_test, augment=False)

    train_loader = DataLoader(
        train_ds,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=PIN_MEMORY,
        drop_last=False,
    )

    val_loader = DataLoader(
        val_ds,
        batch_size=BATCH_SIZE * 2,
        shuffle=False,
        num_workers=0,
        pin_memory=PIN_MEMORY,
        drop_last=False,
    )

    test_loader = DataLoader(
        test_ds,
        batch_size=BATCH_SIZE * 2,
        shuffle=False,
        num_workers=0,
        pin_memory=PIN_MEMORY,
        drop_last=False,
    )

    return train_loader, val_loader, test_loader

## 8. Custom 1D ResCNN 256-Class Model

In [8]:
class ResidualBlock1D(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=7, stride=1, dropout=0.05):
        super().__init__()
        padding = kernel_size // 2

        self.conv1 = nn.Conv1d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding, bias=False)
        self.bn1 = nn.BatchNorm1d(out_channels)
        self.conv2 = nn.Conv1d(out_channels, out_channels, kernel_size=kernel_size, stride=1, padding=padding, bias=False)
        self.bn2 = nn.BatchNorm1d(out_channels)
        self.act = nn.SiLU(inplace=True)
        self.dropout = nn.Dropout(dropout)

        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv1d(in_channels, out_channels, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm1d(out_channels),
            )
        else:
            self.shortcut = nn.Identity()

    def forward(self, x):
        identity = self.shortcut(x)
        out = self.conv1(x)
        out = self.bn1(out)
        out = self.act(out)
        out = self.conv2(out)
        out = self.bn2(out)
        out = self.dropout(out)
        out = out + identity
        out = self.act(out)
        return out


class CNN256ResCNN1D(nn.Module):
    def __init__(self, num_classes=256):
        super().__init__()

        self.stem = nn.Sequential(
            nn.Conv1d(1, 32, kernel_size=15, stride=1, padding=7, bias=False),
            nn.BatchNorm1d(32),
            nn.SiLU(inplace=True),
            nn.MaxPool1d(kernel_size=2),
        )

        self.stage1 = nn.Sequential(
            ResidualBlock1D(32, 32, kernel_size=7, stride=1, dropout=0.03),
            ResidualBlock1D(32, 32, kernel_size=7, stride=1, dropout=0.03),
        )
        self.stage2 = nn.Sequential(
            ResidualBlock1D(32, 64, kernel_size=7, stride=2, dropout=0.05),
            ResidualBlock1D(64, 64, kernel_size=7, stride=1, dropout=0.05),
        )
        self.stage3 = nn.Sequential(
            ResidualBlock1D(64, 128, kernel_size=5, stride=2, dropout=0.08),
            ResidualBlock1D(128, 128, kernel_size=5, stride=1, dropout=0.08),
        )
        self.stage4 = nn.Sequential(
            ResidualBlock1D(128, 256, kernel_size=5, stride=2, dropout=0.10),
            ResidualBlock1D(256, 256, kernel_size=5, stride=1, dropout=0.10),
        )

        self.avg_pool = nn.AdaptiveAvgPool1d(1)
        self.max_pool = nn.AdaptiveMaxPool1d(1)

        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(0.20),
            nn.Linear(512, 512),
            nn.SiLU(inplace=True),
            nn.Dropout(0.20),
            nn.Linear(512, num_classes),
        )

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv1d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm1d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, mean=0.0, std=0.01)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.stem(x)
        x = self.stage1(x)
        x = self.stage2(x)
        x = self.stage3(x)
        x = self.stage4(x)
        avg = self.avg_pool(x)
        mx = self.max_pool(x)
        x = torch.cat([avg, mx], dim=1)
        return self.head(x)


_tmp = CNN256ResCNN1D(num_classes=256)
print("Model parameters:", f"{sum(p.numel() for p in _tmp.parameters()):,}")
del _tmp

Model parameters: 2,004,896

## 9. Metrics

In [9]:
def topk_accuracy_from_logits(logits, y, ks=TOPK_VALUES):
    results = {}
    max_k = max(ks)
    topk = logits.topk(max_k, dim=1).indices
    for k in ks:
        results[f"top{k}"] = topk[:, :k].eq(y.view(-1, 1)).any(dim=1).float().mean().item()
    return results


@torch.no_grad()
def evaluate_model(model, loader, criterion):
    model.eval()
    total_loss = 0.0
    total_samples = 0
    all_logits = []
    all_y = []

    for xb, yb in loader:
        xb = xb.to(device, non_blocking=True)
        yb = yb.to(device, non_blocking=True)
        logits = model(xb)
        loss = criterion(logits, yb)

        total_loss += loss.item() * len(yb)
        total_samples += len(yb)
        all_logits.append(logits.detach().cpu())
        all_y.append(yb.detach().cpu())

    all_logits = torch.cat(all_logits, dim=0)
    all_y = torch.cat(all_y, dim=0)
    avg_loss = total_loss / max(total_samples, 1)
    topk = topk_accuracy_from_logits(all_logits, all_y, ks=TOPK_VALUES)
    return avg_loss, topk, all_logits, all_y


def grouped_topk_from_logits(logits, y, group_size=4, ks=TOPK_VALUES, seed=42):
    logits = logits.detach().cpu()
    y_np = y.detach().cpu().numpy()
    log_probs = F.log_softmax(logits, dim=1).numpy()
    rng = np.random.default_rng(seed)

    group_scores = []
    group_labels = []

    for cls in np.unique(y_np):
        idx = np.where(y_np == cls)[0]
        if len(idx) < group_size:
            continue
        rng.shuffle(idx)
        n_groups = len(idx) // group_size
        idx = idx[: n_groups * group_size]
        idx_groups = idx.reshape(n_groups, group_size)

        for g in idx_groups:
            score = log_probs[g].sum(axis=0)
            group_scores.append(score)
            group_labels.append(cls)

    result = {f"grouped_n{group_size}_groups": len(group_labels)}

    if len(group_scores) == 0:
        for k in ks:
            result[f"grouped_n{group_size}_top{k}"] = np.nan
        return result

    group_scores = torch.tensor(np.vstack(group_scores), dtype=torch.float32)
    group_labels = torch.tensor(np.array(group_labels), dtype=torch.long)
    max_k = max(ks)
    topk = group_scores.topk(max_k, dim=1).indices

    for k in ks:
        acc = topk[:, :k].eq(group_labels.view(-1, 1)).any(dim=1).float().mean().item()
        result[f"grouped_n{group_size}_top{k}"] = acc

    return result


def all_grouped_metrics(logits, y, group_sizes=GROUP_SIZES, seed=42):
    result = {}
    for n in group_sizes:
        result.update(grouped_topk_from_logits(logits, y, group_size=n, ks=TOPK_VALUES, seed=seed + n))
    return result


def make_top32_predictions_df(logits, y, idx_test):
    probs = F.softmax(logits, dim=1)
    top_probs, top_idx = probs.topk(32, dim=1)
    df = pd.DataFrame({
        "original_loaded_index": idx_test,
        "true_key_byte_value": y.numpy().astype(int),
        "true_key_byte_hex": [f"{int(v):02x}" for v in y.numpy()],
    })
    for rank in range(32):
        df[f"rank{rank+1}_value"] = top_idx[:, rank].numpy().astype(int)
        df[f"rank{rank+1}_hex"] = [f"{int(v):02x}" for v in top_idx[:, rank].numpy()]
        df[f"rank{rank+1}_prob"] = top_probs[:, rank].numpy()
    return df

## 10. Train One Byte

In [10]:
def train_one_byte(target_byte: int):
    byte_start = time.time()
    set_seed(SEED + target_byte)

    byte_result_dir = RESULTS_ROOT / f"byte_{target_byte:02d}"
    byte_model_dir = MODELS_ROOT / f"byte_{target_byte:02d}"
    byte_result_dir.mkdir(parents=True, exist_ok=True)
    byte_model_dir.mkdir(parents=True, exist_ok=True)

    summary_path = byte_result_dir / f"byte_{target_byte:02d}_summary.csv"
    if SKIP_COMPLETED_BYTES and summary_path.exists():
        print(f"Skipping byte {target_byte:02d}; existing summary found: {summary_path}")
        return pd.read_csv(summary_path).iloc[0].to_dict()

    X, y, meta = load_byte_dataset(DATASET_ROOT, target_byte)

    (
        X_train, X_val, X_test,
        y_train, y_val, y_test,
        idx_train, idx_val, idx_test,
        mean, std,
    ) = preprocess_and_split(X, y, seed=SEED + target_byte)

    if SAVE_SPLIT_MAPPING:
        split_df = meta.copy()
        split_df["original_loaded_index"] = np.arange(len(split_df))
        split_df["split"] = "unused"
        split_df.loc[idx_train, "split"] = "train"
        split_df.loc[idx_val, "split"] = "validation"
        split_df.loc[idx_test, "split"] = "test"
        split_df.to_csv(byte_result_dir / f"byte_{target_byte:02d}_split_mapping.csv", index=False)

    train_loader, val_loader, test_loader = make_loaders(X_train, X_val, X_test, y_train, y_val, y_test)

    model = CNN256ResCNN1D(num_classes=256).to(device)
    criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max",
        factor=0.5,
        patience=5,
        min_lr=1e-6,
    )

    best_val_top4 = -1.0
    best_epoch = -1
    patience_counter = 0
    history = []
    best_model_path = byte_model_dir / f"byte_{target_byte:02d}_ascon_cnn256_rescnn_best.pt"

    for epoch in range(1, EPOCHS + 1):
        model.train()
        train_loss_sum = 0.0
        train_samples = 0

        loader_iter = train_loader
        if TQDM_AVAILABLE:
            loader_iter = tqdm(train_loader, leave=False, desc=f"Byte {target_byte:02d} Epoch {epoch:02d}")

        for xb, yb in loader_iter:
            xb = xb.to(device, non_blocking=True)
            yb = yb.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()

            if GRAD_CLIP_NORM is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)

            optimizer.step()

            train_loss_sum += loss.item() * len(yb)
            train_samples += len(yb)

        train_loss = train_loss_sum / max(train_samples, 1)
        val_loss, val_topk, _, _ = evaluate_model(model, val_loader, criterion)
        current_lr = optimizer.param_groups[0]["lr"]

        row = {
            "target_byte": target_byte,
            "epoch": epoch,
            "train_loss": train_loss,
            "val_loss": val_loss,
            "lr": current_lr,
        }
        row.update({f"val_{k}": v for k, v in val_topk.items()})
        history.append(row)

        print(
            f"Byte {target_byte:02d} | Epoch {epoch:02d}/{EPOCHS} | "
            f"train_loss={train_loss:.4f} | val_loss={val_loss:.4f} | lr={current_lr:.2e} | "
            f"Top1={val_topk['top1']:.4f} | Top2={val_topk['top2']:.4f} | "
            f"Top4={val_topk['top4']:.4f} | Top8={val_topk['top8']:.4f} | "
            f"Top16={val_topk['top16']:.4f} | Top32={val_topk['top32']:.4f}"
        )

        scheduler.step(val_topk["top4"])

        if val_topk["top4"] > best_val_top4:
            best_val_top4 = val_topk["top4"]
            best_epoch = epoch
            patience_counter = 0
            checkpoint = {
                "target_byte": target_byte,
                "algorithm": "ASCON-AEAD-128",
                "model_name": "CNN256ResCNN1D",
                "model_state_dict": model.state_dict(),
                "epoch": epoch,
                "best_val_top4": best_val_top4,
                "topk_values": TOPK_VALUES,
                "mean": torch.tensor(mean, dtype=torch.float32),
                "std": torch.tensor(std, dtype=torch.float32),
                "config": training_config,
            }
            torch.save(checkpoint, best_model_path)
        else:
            patience_counter += 1

        if patience_counter >= EARLY_STOPPING_PATIENCE:
            print(f"Early stopping at epoch {epoch}. Best epoch: {best_epoch}, best val Top4: {best_val_top4:.4f}")
            break

    history_df = pd.DataFrame(history)
    history_df.to_csv(byte_result_dir / f"byte_{target_byte:02d}_training_history.csv", index=False)

    # PyTorch 2.6+ defaults to weights_only=True. This checkpoint is generated locally by this notebook.
    checkpoint = torch.load(best_model_path, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])

    test_loss, test_topk, test_logits, test_y = evaluate_model(model, test_loader, criterion)
    grouped_metrics = all_grouped_metrics(test_logits, test_y, group_sizes=GROUP_SIZES, seed=SEED + target_byte)

    if SAVE_TOP32_PREDICTIONS:
        pred_df = make_top32_predictions_df(test_logits, test_y, idx_test)
        pred_df.to_csv(byte_result_dir / f"byte_{target_byte:02d}_test_predictions_top32.csv", index=False)

    elapsed_min = (time.time() - byte_start) / 60.0

    result = {
        "target_byte": target_byte,
        "algorithm": "ASCON-AEAD-128",
        "model": "CNN256ResCNN1D",
        "best_epoch": best_epoch,
        "best_val_top4": best_val_top4,
        "test_loss": test_loss,
        "elapsed_minutes": elapsed_min,
        "train_size": len(y_train),
        "val_size": len(y_val),
        "test_size": len(y_test),
        "class_count_total": len(np.unique(y)),
        "trace_len": int(X.shape[1]),
    }
    result.update(test_topk)
    result.update(grouped_metrics)

    pd.DataFrame([result]).to_csv(summary_path, index=False)

    print(f"\nFinished ASCON byte {target_byte:02d}")
    print("Best epoch:", best_epoch)
    print("Test Top-k:", test_topk)
    print("Grouped Top4:", {k: v for k, v in grouped_metrics.items() if "top4" in k})
    print("Elapsed minutes:", f"{elapsed_min:.2f}")
    print("Saved model:", best_model_path)
    print("Saved summary:", summary_path)

    # Clean memory before next byte.
    del X, y, meta, X_train, X_val, X_test, y_train, y_val, y_test
    del train_loader, val_loader, test_loader, model, criterion, optimizer, scheduler
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result

## 11. Train Selected Bytes

In [11]:
all_results = []
start_all = time.time()

for b in BYTES_TO_TRAIN:
    result = train_one_byte(b)
    all_results.append(result)

summary_df = pd.DataFrame(all_results).sort_values("target_byte").reset_index(drop=True)
summary_path = RESULTS_ROOT / "summary_results_ascon_cnn256_rescnn.csv"
summary_df.to_csv(summary_path, index=False)

elapsed_all_hours = (time.time() - start_all) / 3600.0
print("\nAll requested ASCON bytes finished.")
print("Elapsed hours:", f"{elapsed_all_hours:.2f}")
print("Saved all-byte summary:", summary_path)

display(summary_df)

Loading ASCON byte 00
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_00
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 00 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 01/80 | train_loss=5.3844 | val_loss=5.0126 | lr=1.00e-03 | Top1=0.0173 | Top2=0.0378 | Top4=0.0716 | Top8=0.1293 | Top16=0.2291 | Top32=0.3833

Byte 00 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 02/80 | train_loss=4.6745 | val_loss=4.3525 | lr=1.00e-03 | Top1=0.0380 | Top2=0.0691 | Top4=0.1293 | Top8=0.2458 | Top16=0.4111 | Top32=0.6560

Byte 00 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 03/80 | train_loss=4.0917 | val_loss=3.7911 | lr=1.00e-03 | Top1=0.0689 | Top2=0.1376 | Top4=0.2453 | Top8=0.4309 | Top16=0.6956 | Top32=0.9300

Byte 00 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 04/80 | train_loss=3.4390 | val_loss=2.9652 | lr=1.00e-03 | Top1=0.2102 | Top2=0.3433 | Top4=0.5336 | Top8=0.7536 | Top16=0.9247 | Top32=0.9920

Byte 00 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 05/80 | train_loss=2.7361 | val_loss=2.3107 | lr=1.00e-03 | Top1=0.3171 | Top2=0.5331 | Top4=0.7600 | Top8=0.9240 | Top16=0.9876 | Top32=0.9987

Byte 00 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 06/80 | train_loss=2.3075 | val_loss=1.9918 | lr=1.00e-03 | Top1=0.4042 | Top2=0.6344 | Top4=0.8511 | Top8=0.9693 | Top16=0.9978 | Top32=0.9998

Byte 00 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 07/80 | train_loss=2.0609 | val_loss=1.7293 | lr=1.00e-03 | Top1=0.4771 | Top2=0.7269 | Top4=0.9189 | Top8=0.9922 | Top16=0.9998 | Top32=0.9998

Byte 00 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 08/80 | train_loss=1.9162 | val_loss=1.6578 | lr=1.00e-03 | Top1=0.4976 | Top2=0.7431 | Top4=0.9271 | Top8=0.9931 | Top16=0.9998 | Top32=1.0000

Byte 00 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 09/80 | train_loss=1.8047 | val_loss=1.5294 | lr=1.00e-03 | Top1=0.5558 | Top2=0.7969 | Top4=0.9538 | Top8=0.9964 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 10/80 | train_loss=1.7200 | val_loss=1.4664 | lr=1.00e-03 | Top1=0.5733 | Top2=0.8064 | Top4=0.9516 | Top8=0.9953 | Top16=0.9998 | Top32=1.0000

Byte 00 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 11/80 | train_loss=1.6521 | val_loss=1.4075 | lr=1.00e-03 | Top1=0.5869 | Top2=0.8347 | Top4=0.9647 | Top8=0.9980 | Top16=0.9998 | Top32=1.0000

Byte 00 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 12/80 | train_loss=1.5810 | val_loss=1.3493 | lr=1.00e-03 | Top1=0.6082 | Top2=0.8418 | Top4=0.9702 | Top8=0.9976 | Top16=0.9993 | Top32=0.9998

Byte 00 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 13/80 | train_loss=1.5238 | val_loss=1.2820 | lr=1.00e-03 | Top1=0.6276 | Top2=0.8687 | Top4=0.9813 | Top8=0.9991 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 14/80 | train_loss=1.4778 | val_loss=1.2691 | lr=1.00e-03 | Top1=0.6484 | Top2=0.8704 | Top4=0.9778 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 15/80 | train_loss=1.4376 | val_loss=1.2279 | lr=1.00e-03 | Top1=0.6602 | Top2=0.8876 | Top4=0.9807 | Top8=0.9980 | Top16=0.9998 | Top32=1.0000

Byte 00 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 16/80 | train_loss=1.3924 | val_loss=1.1585 | lr=1.00e-03 | Top1=0.6862 | Top2=0.9004 | Top4=0.9880 | Top8=0.9996 | Top16=0.9998 | Top32=1.0000

Byte 00 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 17/80 | train_loss=1.3534 | val_loss=1.1756 | lr=1.00e-03 | Top1=0.6824 | Top2=0.8900 | Top4=0.9842 | Top8=0.9987 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 18/80 | train_loss=1.3257 | val_loss=1.1200 | lr=1.00e-03 | Top1=0.7009 | Top2=0.9122 | Top4=0.9878 | Top8=0.9989 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 19/80 | train_loss=1.3062 | val_loss=1.0697 | lr=1.00e-03 | Top1=0.7247 | Top2=0.9227 | Top4=0.9887 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 20/80 | train_loss=1.2551 | val_loss=1.1098 | lr=1.00e-03 | Top1=0.7100 | Top2=0.9051 | Top4=0.9867 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 21/80 | train_loss=1.2296 | val_loss=1.0429 | lr=1.00e-03 | Top1=0.7420 | Top2=0.9296 | Top4=0.9898 | Top8=0.9996 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 22/80 | train_loss=1.1943 | val_loss=1.0165 | lr=1.00e-03 | Top1=0.7536 | Top2=0.9289 | Top4=0.9909 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 23/80 | train_loss=1.1696 | val_loss=0.9687 | lr=1.00e-03 | Top1=0.7760 | Top2=0.9451 | Top4=0.9944 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 24/80 | train_loss=1.1289 | val_loss=0.9964 | lr=1.00e-03 | Top1=0.7571 | Top2=0.9322 | Top4=0.9916 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 25/80 | train_loss=1.1107 | val_loss=0.9389 | lr=1.00e-03 | Top1=0.7982 | Top2=0.9513 | Top4=0.9949 | Top8=0.9996 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 26/80 | train_loss=1.0750 | val_loss=0.9067 | lr=1.00e-03 | Top1=0.8027 | Top2=0.9467 | Top4=0.9924 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 27/80 | train_loss=1.0451 | val_loss=0.9435 | lr=1.00e-03 | Top1=0.7800 | Top2=0.9491 | Top4=0.9949 | Top8=0.9993 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 28/80 | train_loss=1.0261 | val_loss=0.8615 | lr=1.00e-03 | Top1=0.8276 | Top2=0.9616 | Top4=0.9944 | Top8=0.9993 | Top16=0.9998 | Top32=0.9998

Byte 00 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 29/80 | train_loss=0.9885 | val_loss=0.8670 | lr=1.00e-03 | Top1=0.8247 | Top2=0.9578 | Top4=0.9951 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 30/80 | train_loss=0.9714 | val_loss=0.8055 | lr=1.00e-03 | Top1=0.8473 | Top2=0.9673 | Top4=0.9962 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 31/80 | train_loss=0.9383 | val_loss=0.8250 | lr=1.00e-03 | Top1=0.8473 | Top2=0.9627 | Top4=0.9969 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 32/80 | train_loss=0.9209 | val_loss=0.7698 | lr=1.00e-03 | Top1=0.8591 | Top2=0.9716 | Top4=0.9978 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 33/80 | train_loss=0.8894 | val_loss=0.7470 | lr=1.00e-03 | Top1=0.8762 | Top2=0.9718 | Top4=0.9973 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 34/80 | train_loss=0.8539 | val_loss=0.7760 | lr=1.00e-03 | Top1=0.8642 | Top2=0.9704 | Top4=0.9973 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 35/80 | train_loss=0.8341 | val_loss=0.7537 | lr=1.00e-03 | Top1=0.8753 | Top2=0.9682 | Top4=0.9962 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 36/80 | train_loss=0.8123 | val_loss=0.7160 | lr=1.00e-03 | Top1=0.8907 | Top2=0.9780 | Top4=0.9980 | Top8=0.9996 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 37/80 | train_loss=0.7820 | val_loss=0.7331 | lr=1.00e-03 | Top1=0.8842 | Top2=0.9771 | Top4=0.9958 | Top8=0.9996 | Top16=0.9998 | Top32=1.0000

Byte 00 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 38/80 | train_loss=0.7653 | val_loss=0.6999 | lr=1.00e-03 | Top1=0.8964 | Top2=0.9789 | Top4=0.9973 | Top8=0.9996 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 39/80 | train_loss=0.7574 | val_loss=0.6339 | lr=1.00e-03 | Top1=0.9222 | Top2=0.9876 | Top4=0.9987 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 40/80 | train_loss=0.7265 | val_loss=0.6319 | lr=1.00e-03 | Top1=0.9213 | Top2=0.9858 | Top4=0.9984 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 41/80 | train_loss=0.7033 | val_loss=0.6207 | lr=1.00e-03 | Top1=0.9176 | Top2=0.9871 | Top4=0.9987 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 42/80 | train_loss=0.6907 | val_loss=0.6512 | lr=1.00e-03 | Top1=0.9069 | Top2=0.9849 | Top4=0.9993 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 43/80 | train_loss=0.6729 | val_loss=0.6026 | lr=1.00e-03 | Top1=0.9284 | Top2=0.9871 | Top4=0.9991 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 44/80 | train_loss=0.6484 | val_loss=0.6057 | lr=1.00e-03 | Top1=0.9276 | Top2=0.9867 | Top4=0.9987 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 45/80 | train_loss=0.6256 | val_loss=0.5875 | lr=1.00e-03 | Top1=0.9362 | Top2=0.9904 | Top4=0.9984 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 46/80 | train_loss=0.6052 | val_loss=0.5670 | lr=1.00e-03 | Top1=0.9362 | Top2=0.9907 | Top4=0.9987 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 47/80 | train_loss=0.6004 | val_loss=0.5653 | lr=1.00e-03 | Top1=0.9402 | Top2=0.9904 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 48/80 | train_loss=0.5811 | val_loss=0.5639 | lr=1.00e-03 | Top1=0.9418 | Top2=0.9900 | Top4=0.9987 | Top8=0.9998 | Top16=0.9998 | Top32=1.0000

Byte 00 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 49/80 | train_loss=0.5707 | val_loss=0.5714 | lr=1.00e-03 | Top1=0.9400 | Top2=0.9889 | Top4=0.9980 | Top8=0.9998 | Top16=0.9998 | Top32=0.9998

Byte 00 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 50/80 | train_loss=0.5587 | val_loss=0.5677 | lr=1.00e-03 | Top1=0.9387 | Top2=0.9907 | Top4=0.9991 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 51/80 | train_loss=0.5457 | val_loss=0.5405 | lr=1.00e-03 | Top1=0.9458 | Top2=0.9893 | Top4=0.9987 | Top8=0.9998 | Top16=0.9998 | Top32=0.9998

Byte 00 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 52/80 | train_loss=0.5373 | val_loss=0.5606 | lr=1.00e-03 | Top1=0.9349 | Top2=0.9904 | Top4=0.9998 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 53/80 | train_loss=0.5194 | val_loss=0.5214 | lr=1.00e-03 | Top1=0.9538 | Top2=0.9938 | Top4=0.9980 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 54/80 | train_loss=0.5155 | val_loss=0.5356 | lr=1.00e-03 | Top1=0.9442 | Top2=0.9909 | Top4=0.9991 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 55/80 | train_loss=0.5019 | val_loss=0.5210 | lr=1.00e-03 | Top1=0.9491 | Top2=0.9940 | Top4=0.9996 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 56/80 | train_loss=0.4935 | val_loss=0.5178 | lr=1.00e-03 | Top1=0.9522 | Top2=0.9916 | Top4=0.9991 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 57/80 | train_loss=0.4892 | val_loss=0.5691 | lr=1.00e-03 | Top1=0.9269 | Top2=0.9887 | Top4=0.9989 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 58/80 | train_loss=0.4724 | val_loss=0.5027 | lr=1.00e-03 | Top1=0.9580 | Top2=0.9929 | Top4=0.9991 | Top8=0.9996 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 59/80 | train_loss=0.4314 | val_loss=0.4471 | lr=5.00e-04 | Top1=0.9722 | Top2=0.9969 | Top4=0.9993 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 60/80 | train_loss=0.4151 | val_loss=0.4498 | lr=5.00e-04 | Top1=0.9736 | Top2=0.9967 | Top4=0.9993 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 61/80 | train_loss=0.4103 | val_loss=0.4498 | lr=5.00e-04 | Top1=0.9702 | Top2=0.9967 | Top4=0.9996 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 62/80 | train_loss=0.4033 | val_loss=0.4375 | lr=5.00e-04 | Top1=0.9720 | Top2=0.9958 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 63/80 | train_loss=0.4026 | val_loss=0.4360 | lr=5.00e-04 | Top1=0.9756 | Top2=0.9971 | Top4=0.9996 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 64/80 | train_loss=0.3988 | val_loss=0.4358 | lr=5.00e-04 | Top1=0.9718 | Top2=0.9967 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 65/80 | train_loss=0.3965 | val_loss=0.4389 | lr=5.00e-04 | Top1=0.9720 | Top2=0.9962 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 66/80 | train_loss=0.3971 | val_loss=0.4443 | lr=5.00e-04 | Top1=0.9711 | Top2=0.9967 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 67/80 | train_loss=0.3960 | val_loss=0.4434 | lr=5.00e-04 | Top1=0.9698 | Top2=0.9956 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 68/80 | train_loss=0.3903 | val_loss=0.4248 | lr=5.00e-04 | Top1=0.9729 | Top2=0.9976 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 69/80 | train_loss=0.3794 | val_loss=0.4167 | lr=2.50e-04 | Top1=0.9793 | Top2=0.9964 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 70/80 | train_loss=0.3756 | val_loss=0.4159 | lr=2.50e-04 | Top1=0.9778 | Top2=0.9967 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 71/80 | train_loss=0.3745 | val_loss=0.4166 | lr=2.50e-04 | Top1=0.9780 | Top2=0.9973 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 72/80 | train_loss=0.3730 | val_loss=0.4129 | lr=2.50e-04 | Top1=0.9780 | Top2=0.9962 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 73/80 | train_loss=0.3726 | val_loss=0.4207 | lr=2.50e-04 | Top1=0.9751 | Top2=0.9964 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 74/80 | train_loss=0.3707 | val_loss=0.4091 | lr=2.50e-04 | Top1=0.9784 | Top2=0.9971 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 75/80 | train_loss=0.3667 | val_loss=0.4033 | lr=1.25e-04 | Top1=0.9811 | Top2=0.9976 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 76/80 | train_loss=0.3654 | val_loss=0.4059 | lr=1.25e-04 | Top1=0.9771 | Top2=0.9973 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 00 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 00 | Epoch 77/80 | train_loss=0.3652 | val_loss=0.4046 | lr=1.25e-04 | Top1=0.9793 | Top2=0.9976 | Top4=0.9996 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000
Early stopping at epoch 77. Best epoch: 62, best val Top4: 1.0000

Finished ASCON byte 00
Best epoch: 62
Test Top-k: {'top1': 0.9693333506584167, 'top2': 0.9948889017105103, 'top4': 0.9995555281639099, 'top8': 1.0, 'top16': 1.0, 'top32': 1.0}
Grouped Top4: {'grouped_n1_top4': 0.9995555281639099, 'grouped_n2_top4': 1.0, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 11.98
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_00\byte_00_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_00\byte_00_summary.csv

Loading ASCON byte 01
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_01
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 01 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 01/80 | train_loss=5.4974 | val_loss=5.7135 | lr=1.00e-03 | Top1=0.0064 | Top2=0.0113 | Top4=0.0227 | Top8=0.0458 | Top16=0.0898 | Top32=0.1744

Byte 01 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 02/80 | train_loss=5.2589 | val_loss=5.7070 | lr=1.00e-03 | Top1=0.0080 | Top2=0.0147 | Top4=0.0316 | Top8=0.0600 | Top16=0.1191 | Top32=0.2202

Byte 01 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 03/80 | train_loss=4.8572 | val_loss=5.4201 | lr=1.00e-03 | Top1=0.0120 | Top2=0.0249 | Top4=0.0500 | Top8=0.0951 | Top16=0.1898 | Top32=0.3580

Byte 01 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 04/80 | train_loss=4.5139 | val_loss=4.2831 | lr=1.00e-03 | Top1=0.0307 | Top2=0.0638 | Top4=0.1193 | Top8=0.2280 | Top16=0.3984 | Top32=0.6558

Byte 01 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 05/80 | train_loss=4.2732 | val_loss=4.4250 | lr=1.00e-03 | Top1=0.0264 | Top2=0.0513 | Top4=0.1000 | Top8=0.1816 | Top16=0.3469 | Top32=0.6329

Byte 01 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 06/80 | train_loss=4.1439 | val_loss=4.0470 | lr=1.00e-03 | Top1=0.0442 | Top2=0.0816 | Top4=0.1556 | Top8=0.2744 | Top16=0.4633 | Top32=0.7269

Byte 01 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 07/80 | train_loss=4.0566 | val_loss=3.9114 | lr=1.00e-03 | Top1=0.0538 | Top2=0.1004 | Top4=0.1842 | Top8=0.3436 | Top16=0.5420 | Top32=0.8024

Byte 01 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 08/80 | train_loss=3.9435 | val_loss=3.7842 | lr=1.00e-03 | Top1=0.0713 | Top2=0.1280 | Top4=0.2431 | Top8=0.4038 | Top16=0.6073 | Top32=0.8478

Byte 01 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 09/80 | train_loss=3.7156 | val_loss=3.3634 | lr=1.00e-03 | Top1=0.1204 | Top2=0.2169 | Top4=0.3707 | Top8=0.5884 | Top16=0.8133 | Top32=0.9598

Byte 01 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 10/80 | train_loss=3.4427 | val_loss=3.1189 | lr=1.00e-03 | Top1=0.1736 | Top2=0.2942 | Top4=0.4653 | Top8=0.6718 | Top16=0.8736 | Top32=0.9778

Byte 01 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 11/80 | train_loss=3.2098 | val_loss=2.9158 | lr=1.00e-03 | Top1=0.2036 | Top2=0.3493 | Top4=0.5640 | Top8=0.7738 | Top16=0.9193 | Top32=0.9893

Byte 01 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 12/80 | train_loss=2.9872 | val_loss=2.7266 | lr=1.00e-03 | Top1=0.2409 | Top2=0.4078 | Top4=0.6158 | Top8=0.8149 | Top16=0.9431 | Top32=0.9944

Byte 01 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 13/80 | train_loss=2.7840 | val_loss=2.5540 | lr=1.00e-03 | Top1=0.2658 | Top2=0.4433 | Top4=0.6616 | Top8=0.8627 | Top16=0.9758 | Top32=0.9976

Byte 01 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 14/80 | train_loss=2.6313 | val_loss=2.3381 | lr=1.00e-03 | Top1=0.3262 | Top2=0.5253 | Top4=0.7404 | Top8=0.9087 | Top16=0.9829 | Top32=0.9982

Byte 01 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 15/80 | train_loss=2.4983 | val_loss=2.2866 | lr=1.00e-03 | Top1=0.3327 | Top2=0.5289 | Top4=0.7527 | Top8=0.9116 | Top16=0.9842 | Top32=0.9989

Byte 01 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 16/80 | train_loss=2.3790 | val_loss=2.2204 | lr=1.00e-03 | Top1=0.3507 | Top2=0.5536 | Top4=0.7747 | Top8=0.9202 | Top16=0.9869 | Top32=0.9991

Byte 01 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 17/80 | train_loss=2.2770 | val_loss=2.1652 | lr=1.00e-03 | Top1=0.3640 | Top2=0.5664 | Top4=0.7898 | Top8=0.9313 | Top16=0.9864 | Top32=0.9978

Byte 01 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 18/80 | train_loss=2.2163 | val_loss=2.0823 | lr=1.00e-03 | Top1=0.4002 | Top2=0.5964 | Top4=0.7944 | Top8=0.9418 | Top16=0.9896 | Top32=0.9989

Byte 01 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 19/80 | train_loss=2.1147 | val_loss=1.9473 | lr=1.00e-03 | Top1=0.4402 | Top2=0.6549 | Top4=0.8351 | Top8=0.9593 | Top16=0.9929 | Top32=0.9996

Byte 01 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 20/80 | train_loss=2.0526 | val_loss=2.0100 | lr=1.00e-03 | Top1=0.4060 | Top2=0.6187 | Top4=0.8253 | Top8=0.9507 | Top16=0.9931 | Top32=0.9989

Byte 01 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 21/80 | train_loss=2.0003 | val_loss=1.8335 | lr=1.00e-03 | Top1=0.4618 | Top2=0.6760 | Top4=0.8720 | Top8=0.9671 | Top16=0.9962 | Top32=0.9998

Byte 01 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 22/80 | train_loss=1.9386 | val_loss=1.8223 | lr=1.00e-03 | Top1=0.4713 | Top2=0.6938 | Top4=0.8673 | Top8=0.9602 | Top16=0.9927 | Top32=0.9991

Byte 01 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 23/80 | train_loss=1.8761 | val_loss=1.8260 | lr=1.00e-03 | Top1=0.4602 | Top2=0.6889 | Top4=0.8751 | Top8=0.9702 | Top16=0.9956 | Top32=0.9993

Byte 01 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 24/80 | train_loss=1.8195 | val_loss=1.6737 | lr=1.00e-03 | Top1=0.5191 | Top2=0.7398 | Top4=0.9020 | Top8=0.9789 | Top16=0.9973 | Top32=0.9998

Byte 01 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 25/80 | train_loss=1.7731 | val_loss=1.5666 | lr=1.00e-03 | Top1=0.5573 | Top2=0.7807 | Top4=0.9258 | Top8=0.9847 | Top16=0.9980 | Top32=0.9998

Byte 01 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 26/80 | train_loss=1.7142 | val_loss=1.6151 | lr=1.00e-03 | Top1=0.5396 | Top2=0.7560 | Top4=0.9107 | Top8=0.9811 | Top16=0.9987 | Top32=0.9996

Byte 01 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 27/80 | train_loss=1.6777 | val_loss=1.5785 | lr=1.00e-03 | Top1=0.5522 | Top2=0.7671 | Top4=0.9140 | Top8=0.9844 | Top16=0.9982 | Top32=0.9998

Byte 01 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 28/80 | train_loss=1.6095 | val_loss=1.5001 | lr=1.00e-03 | Top1=0.5849 | Top2=0.7949 | Top4=0.9264 | Top8=0.9833 | Top16=0.9984 | Top32=0.9996

Byte 01 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 29/80 | train_loss=1.5608 | val_loss=1.5275 | lr=1.00e-03 | Top1=0.5611 | Top2=0.7896 | Top4=0.9280 | Top8=0.9869 | Top16=0.9987 | Top32=1.0000

Byte 01 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 30/80 | train_loss=1.5203 | val_loss=1.4530 | lr=1.00e-03 | Top1=0.5913 | Top2=0.8182 | Top4=0.9429 | Top8=0.9900 | Top16=0.9984 | Top32=0.9993

Byte 01 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 31/80 | train_loss=1.4625 | val_loss=1.4340 | lr=1.00e-03 | Top1=0.6040 | Top2=0.8144 | Top4=0.9424 | Top8=0.9904 | Top16=0.9984 | Top32=0.9998

Byte 01 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 32/80 | train_loss=1.4281 | val_loss=1.4214 | lr=1.00e-03 | Top1=0.6113 | Top2=0.8193 | Top4=0.9458 | Top8=0.9893 | Top16=0.9980 | Top32=0.9996

Byte 01 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 33/80 | train_loss=1.3724 | val_loss=1.3036 | lr=1.00e-03 | Top1=0.6598 | Top2=0.8549 | Top4=0.9569 | Top8=0.9918 | Top16=0.9989 | Top32=0.9993

Byte 01 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 34/80 | train_loss=1.3325 | val_loss=1.3863 | lr=1.00e-03 | Top1=0.6304 | Top2=0.8280 | Top4=0.9476 | Top8=0.9909 | Top16=0.9980 | Top32=0.9996

Byte 01 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 35/80 | train_loss=1.2934 | val_loss=1.4008 | lr=1.00e-03 | Top1=0.6147 | Top2=0.8278 | Top4=0.9458 | Top8=0.9896 | Top16=0.9989 | Top32=0.9996

Byte 01 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 36/80 | train_loss=1.2564 | val_loss=1.2707 | lr=1.00e-03 | Top1=0.6660 | Top2=0.8553 | Top4=0.9567 | Top8=0.9924 | Top16=0.9991 | Top32=0.9998

Byte 01 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 37/80 | train_loss=1.2076 | val_loss=1.2628 | lr=1.00e-03 | Top1=0.6682 | Top2=0.8509 | Top4=0.9593 | Top8=0.9924 | Top16=0.9993 | Top32=0.9993

Byte 01 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 38/80 | train_loss=1.1700 | val_loss=1.1382 | lr=1.00e-03 | Top1=0.7207 | Top2=0.8931 | Top4=0.9724 | Top8=0.9967 | Top16=0.9996 | Top32=0.9996

Byte 01 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 39/80 | train_loss=1.1356 | val_loss=1.1743 | lr=1.00e-03 | Top1=0.7073 | Top2=0.8804 | Top4=0.9664 | Top8=0.9942 | Top16=0.9993 | Top32=0.9998

Byte 01 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 40/80 | train_loss=1.0960 | val_loss=1.1666 | lr=1.00e-03 | Top1=0.7127 | Top2=0.8822 | Top4=0.9702 | Top8=0.9927 | Top16=0.9984 | Top32=0.9989

Byte 01 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 41/80 | train_loss=1.0757 | val_loss=1.1214 | lr=1.00e-03 | Top1=0.7300 | Top2=0.8987 | Top4=0.9713 | Top8=0.9962 | Top16=0.9993 | Top32=0.9998

Byte 01 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 42/80 | train_loss=1.0500 | val_loss=1.0702 | lr=1.00e-03 | Top1=0.7442 | Top2=0.9060 | Top4=0.9767 | Top8=0.9953 | Top16=0.9991 | Top32=0.9993

Byte 01 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 43/80 | train_loss=1.0011 | val_loss=1.0801 | lr=1.00e-03 | Top1=0.7402 | Top2=0.9036 | Top4=0.9758 | Top8=0.9973 | Top16=0.9993 | Top32=0.9998

Byte 01 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 44/80 | train_loss=0.9797 | val_loss=1.1606 | lr=1.00e-03 | Top1=0.7138 | Top2=0.8802 | Top4=0.9656 | Top8=0.9929 | Top16=0.9984 | Top32=0.9998

Byte 01 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 45/80 | train_loss=0.9411 | val_loss=1.1368 | lr=1.00e-03 | Top1=0.7287 | Top2=0.8980 | Top4=0.9738 | Top8=0.9951 | Top16=0.9973 | Top32=0.9982

Byte 01 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 46/80 | train_loss=0.9237 | val_loss=1.1396 | lr=1.00e-03 | Top1=0.7267 | Top2=0.8936 | Top4=0.9724 | Top8=0.9942 | Top16=0.9991 | Top32=0.9993

Byte 01 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 47/80 | train_loss=0.8991 | val_loss=1.0542 | lr=1.00e-03 | Top1=0.7580 | Top2=0.9127 | Top4=0.9782 | Top8=0.9960 | Top16=0.9991 | Top32=0.9996

Byte 01 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 48/80 | train_loss=0.8876 | val_loss=1.1899 | lr=1.00e-03 | Top1=0.7118 | Top2=0.8816 | Top4=0.9653 | Top8=0.9927 | Top16=0.9976 | Top32=0.9989

Byte 01 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 49/80 | train_loss=0.8567 | val_loss=0.9727 | lr=1.00e-03 | Top1=0.7847 | Top2=0.9220 | Top4=0.9829 | Top8=0.9982 | Top16=0.9991 | Top32=0.9993

Byte 01 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 50/80 | train_loss=0.8321 | val_loss=0.9702 | lr=1.00e-03 | Top1=0.7898 | Top2=0.9260 | Top4=0.9851 | Top8=0.9982 | Top16=0.9998 | Top32=0.9998

Byte 01 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 51/80 | train_loss=0.8072 | val_loss=0.9608 | lr=1.00e-03 | Top1=0.7880 | Top2=0.9298 | Top4=0.9862 | Top8=0.9967 | Top16=0.9989 | Top32=0.9996

Byte 01 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 52/80 | train_loss=0.8016 | val_loss=0.9525 | lr=1.00e-03 | Top1=0.7884 | Top2=0.9276 | Top4=0.9842 | Top8=0.9973 | Top16=0.9996 | Top32=1.0000

Byte 01 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 53/80 | train_loss=0.7867 | val_loss=0.9510 | lr=1.00e-03 | Top1=0.7931 | Top2=0.9336 | Top4=0.9842 | Top8=0.9964 | Top16=0.9982 | Top32=0.9991

Byte 01 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 54/80 | train_loss=0.7585 | val_loss=0.9536 | lr=1.00e-03 | Top1=0.7989 | Top2=0.9269 | Top4=0.9824 | Top8=0.9973 | Top16=0.9991 | Top32=0.9998

Byte 01 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 55/80 | train_loss=0.7491 | val_loss=0.9658 | lr=1.00e-03 | Top1=0.7931 | Top2=0.9322 | Top4=0.9824 | Top8=0.9976 | Top16=0.9996 | Top32=0.9998

Byte 01 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 56/80 | train_loss=0.7257 | val_loss=0.9090 | lr=1.00e-03 | Top1=0.8118 | Top2=0.9356 | Top4=0.9849 | Top8=0.9962 | Top16=0.9991 | Top32=0.9996

Byte 01 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 57/80 | train_loss=0.7258 | val_loss=0.9106 | lr=1.00e-03 | Top1=0.8044 | Top2=0.9393 | Top4=0.9842 | Top8=0.9971 | Top16=0.9989 | Top32=0.9991

Byte 01 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 58/80 | train_loss=0.6290 | val_loss=0.8031 | lr=5.00e-04 | Top1=0.8509 | Top2=0.9516 | Top4=0.9893 | Top8=0.9984 | Top16=0.9996 | Top32=0.9996

Byte 01 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 59/80 | train_loss=0.5964 | val_loss=0.7988 | lr=5.00e-04 | Top1=0.8524 | Top2=0.9569 | Top4=0.9902 | Top8=0.9978 | Top16=0.9989 | Top32=0.9996

Byte 01 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 60/80 | train_loss=0.5861 | val_loss=0.7615 | lr=5.00e-04 | Top1=0.8609 | Top2=0.9620 | Top4=0.9922 | Top8=0.9987 | Top16=0.9996 | Top32=0.9998

Byte 01 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 61/80 | train_loss=0.5724 | val_loss=0.7494 | lr=5.00e-04 | Top1=0.8600 | Top2=0.9640 | Top4=0.9936 | Top8=0.9991 | Top16=0.9991 | Top32=0.9991

Byte 01 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 62/80 | train_loss=0.5590 | val_loss=0.8104 | lr=5.00e-04 | Top1=0.8402 | Top2=0.9540 | Top4=0.9909 | Top8=0.9976 | Top16=0.9987 | Top32=0.9991

Byte 01 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 63/80 | train_loss=0.5524 | val_loss=0.7670 | lr=5.00e-04 | Top1=0.8589 | Top2=0.9593 | Top4=0.9920 | Top8=0.9973 | Top16=0.9987 | Top32=0.9993

Byte 01 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 64/80 | train_loss=0.5536 | val_loss=0.8177 | lr=5.00e-04 | Top1=0.8438 | Top2=0.9544 | Top4=0.9887 | Top8=0.9971 | Top16=0.9982 | Top32=0.9987

Byte 01 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 65/80 | train_loss=0.5428 | val_loss=0.7726 | lr=5.00e-04 | Top1=0.8587 | Top2=0.9642 | Top4=0.9902 | Top8=0.9984 | Top16=0.9993 | Top32=0.9996

Byte 01 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 66/80 | train_loss=0.5378 | val_loss=0.7903 | lr=5.00e-04 | Top1=0.8544 | Top2=0.9571 | Top4=0.9889 | Top8=0.9976 | Top16=0.9991 | Top32=0.9996

Byte 01 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 67/80 | train_loss=0.5310 | val_loss=0.7538 | lr=5.00e-04 | Top1=0.8620 | Top2=0.9578 | Top4=0.9896 | Top8=0.9976 | Top16=0.9982 | Top32=0.9991

Byte 01 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 68/80 | train_loss=0.4959 | val_loss=0.7284 | lr=2.50e-04 | Top1=0.8718 | Top2=0.9640 | Top4=0.9913 | Top8=0.9978 | Top16=0.9989 | Top32=0.9991

Byte 01 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 69/80 | train_loss=0.4863 | val_loss=0.7240 | lr=2.50e-04 | Top1=0.8711 | Top2=0.9664 | Top4=0.9913 | Top8=0.9976 | Top16=0.9982 | Top32=0.9989

Byte 01 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 70/80 | train_loss=0.4800 | val_loss=0.7349 | lr=2.50e-04 | Top1=0.8707 | Top2=0.9656 | Top4=0.9924 | Top8=0.9973 | Top16=0.9984 | Top32=0.9989

Byte 01 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 71/80 | train_loss=0.4773 | val_loss=0.7005 | lr=2.50e-04 | Top1=0.8804 | Top2=0.9671 | Top4=0.9913 | Top8=0.9982 | Top16=0.9991 | Top32=0.9993

Byte 01 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 72/80 | train_loss=0.4755 | val_loss=0.6934 | lr=2.50e-04 | Top1=0.8824 | Top2=0.9682 | Top4=0.9929 | Top8=0.9982 | Top16=0.9991 | Top32=0.9991

Byte 01 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 73/80 | train_loss=0.4669 | val_loss=0.6876 | lr=2.50e-04 | Top1=0.8858 | Top2=0.9702 | Top4=0.9927 | Top8=0.9987 | Top16=0.9993 | Top32=0.9996

Byte 01 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 74/80 | train_loss=0.4575 | val_loss=0.6944 | lr=1.25e-04 | Top1=0.8829 | Top2=0.9684 | Top4=0.9931 | Top8=0.9984 | Top16=0.9987 | Top32=0.9996

Byte 01 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 75/80 | train_loss=0.4514 | val_loss=0.6811 | lr=1.25e-04 | Top1=0.8878 | Top2=0.9707 | Top4=0.9931 | Top8=0.9984 | Top16=0.9991 | Top32=0.9996

Byte 01 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 01 | Epoch 76/80 | train_loss=0.4501 | val_loss=0.6716 | lr=1.25e-04 | Top1=0.8929 | Top2=0.9680 | Top4=0.9922 | Top8=0.9984 | Top16=0.9989 | Top32=0.9989
Early stopping at epoch 76. Best epoch: 61, best val Top4: 0.9936

Finished ASCON byte 01
Best epoch: 61
Test Top-k: {'top1': 0.8551111221313477, 'top2': 0.9588888883590698, 'top4': 0.9893333315849304, 'top8': 0.9980000257492065, 'top16': 1.0, 'top32': 1.0}
Grouped Top4: {'grouped_n1_top4': 0.9893333315849304, 'grouped_n2_top4': 0.9990854859352112, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 11.41
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_01\byte_01_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_01\byte_01_summary.csv

Loading ASCON byte 02
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_02
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 02 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 01/80 | train_loss=5.4935 | val_loss=5.2965 | lr=1.00e-03 | Top1=0.0113 | Top2=0.0222 | Top4=0.0396 | Top8=0.0798 | Top16=0.1451 | Top32=0.2558

Byte 02 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 02/80 | train_loss=5.1534 | val_loss=4.8193 | lr=1.00e-03 | Top1=0.0196 | Top2=0.0444 | Top4=0.0851 | Top8=0.1549 | Top16=0.2736 | Top32=0.4669

Byte 02 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 03/80 | train_loss=4.7074 | val_loss=4.5735 | lr=1.00e-03 | Top1=0.0220 | Top2=0.0442 | Top4=0.0849 | Top8=0.1709 | Top16=0.2982 | Top32=0.5191

Byte 02 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 04/80 | train_loss=4.3969 | val_loss=4.3325 | lr=1.00e-03 | Top1=0.0287 | Top2=0.0509 | Top4=0.1062 | Top8=0.2078 | Top16=0.3684 | Top32=0.6524

Byte 02 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 05/80 | train_loss=4.1595 | val_loss=3.9582 | lr=1.00e-03 | Top1=0.0536 | Top2=0.0962 | Top4=0.1818 | Top8=0.3349 | Top16=0.5429 | Top32=0.8062

Byte 02 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 06/80 | train_loss=3.9553 | val_loss=3.7470 | lr=1.00e-03 | Top1=0.0736 | Top2=0.1438 | Top4=0.2507 | Top8=0.4213 | Top16=0.6467 | Top32=0.8858

Byte 02 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 07/80 | train_loss=3.8188 | val_loss=3.6661 | lr=1.00e-03 | Top1=0.0840 | Top2=0.1469 | Top4=0.2620 | Top8=0.4513 | Top16=0.6913 | Top32=0.9031

Byte 02 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 08/80 | train_loss=3.6801 | val_loss=3.4652 | lr=1.00e-03 | Top1=0.1089 | Top2=0.1996 | Top4=0.3342 | Top8=0.5411 | Top16=0.7767 | Top32=0.9416

Byte 02 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 09/80 | train_loss=3.5577 | val_loss=3.3214 | lr=1.00e-03 | Top1=0.1247 | Top2=0.2189 | Top4=0.3758 | Top8=0.6124 | Top16=0.8447 | Top32=0.9704

Byte 02 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 10/80 | train_loss=3.3962 | val_loss=3.1229 | lr=1.00e-03 | Top1=0.1489 | Top2=0.2693 | Top4=0.4518 | Top8=0.6813 | Top16=0.8876 | Top32=0.9820

Byte 02 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 11/80 | train_loss=3.2500 | val_loss=2.9736 | lr=1.00e-03 | Top1=0.1878 | Top2=0.3193 | Top4=0.5136 | Top8=0.7420 | Top16=0.9122 | Top32=0.9893

Byte 02 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 12/80 | train_loss=3.1338 | val_loss=2.8893 | lr=1.00e-03 | Top1=0.2004 | Top2=0.3311 | Top4=0.5342 | Top8=0.7611 | Top16=0.9256 | Top32=0.9909

Byte 02 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 13/80 | train_loss=3.0226 | val_loss=2.9004 | lr=1.00e-03 | Top1=0.1918 | Top2=0.3229 | Top4=0.5198 | Top8=0.7527 | Top16=0.9231 | Top32=0.9922

Byte 02 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 14/80 | train_loss=2.9364 | val_loss=2.7714 | lr=1.00e-03 | Top1=0.2147 | Top2=0.3722 | Top4=0.5738 | Top8=0.8053 | Top16=0.9538 | Top32=0.9947

Byte 02 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 15/80 | train_loss=2.8452 | val_loss=2.5708 | lr=1.00e-03 | Top1=0.2640 | Top2=0.4402 | Top4=0.6682 | Top8=0.8658 | Top16=0.9693 | Top32=0.9960

Byte 02 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 16/80 | train_loss=2.7604 | val_loss=2.5802 | lr=1.00e-03 | Top1=0.2631 | Top2=0.4400 | Top4=0.6482 | Top8=0.8513 | Top16=0.9640 | Top32=0.9964

Byte 02 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 17/80 | train_loss=2.7097 | val_loss=2.5441 | lr=1.00e-03 | Top1=0.2671 | Top2=0.4487 | Top4=0.6587 | Top8=0.8600 | Top16=0.9689 | Top32=0.9953

Byte 02 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 18/80 | train_loss=2.6285 | val_loss=2.4643 | lr=1.00e-03 | Top1=0.2971 | Top2=0.4871 | Top4=0.6998 | Top8=0.8809 | Top16=0.9696 | Top32=0.9976

Byte 02 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 19/80 | train_loss=2.5928 | val_loss=2.3703 | lr=1.00e-03 | Top1=0.3140 | Top2=0.5104 | Top4=0.7224 | Top8=0.9033 | Top16=0.9784 | Top32=0.9982

Byte 02 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 20/80 | train_loss=2.5261 | val_loss=2.4379 | lr=1.00e-03 | Top1=0.3013 | Top2=0.4873 | Top4=0.7100 | Top8=0.8809 | Top16=0.9680 | Top32=0.9958

Byte 02 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 21/80 | train_loss=2.4670 | val_loss=2.3619 | lr=1.00e-03 | Top1=0.3176 | Top2=0.5160 | Top4=0.7216 | Top8=0.8971 | Top16=0.9780 | Top32=0.9980

Byte 02 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 22/80 | train_loss=2.4068 | val_loss=2.3033 | lr=1.00e-03 | Top1=0.3260 | Top2=0.5224 | Top4=0.7449 | Top8=0.9087 | Top16=0.9816 | Top32=0.9987

Byte 02 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 23/80 | train_loss=2.3651 | val_loss=2.1938 | lr=1.00e-03 | Top1=0.3624 | Top2=0.5758 | Top4=0.7711 | Top8=0.9280 | Top16=0.9871 | Top32=0.9989

Byte 02 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 24/80 | train_loss=2.3268 | val_loss=2.2305 | lr=1.00e-03 | Top1=0.3578 | Top2=0.5649 | Top4=0.7584 | Top8=0.9193 | Top16=0.9838 | Top32=0.9989

Byte 02 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 25/80 | train_loss=2.2715 | val_loss=2.1829 | lr=1.00e-03 | Top1=0.3607 | Top2=0.5676 | Top4=0.7720 | Top8=0.9273 | Top16=0.9876 | Top32=0.9996

Byte 02 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 26/80 | train_loss=2.2268 | val_loss=2.1636 | lr=1.00e-03 | Top1=0.3604 | Top2=0.5662 | Top4=0.7858 | Top8=0.9324 | Top16=0.9864 | Top32=0.9984

Byte 02 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 27/80 | train_loss=2.2016 | val_loss=2.2668 | lr=1.00e-03 | Top1=0.3402 | Top2=0.5536 | Top4=0.7464 | Top8=0.9109 | Top16=0.9787 | Top32=0.9956

Byte 02 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 28/80 | train_loss=2.1499 | val_loss=2.1781 | lr=1.00e-03 | Top1=0.3682 | Top2=0.5742 | Top4=0.7769 | Top8=0.9278 | Top16=0.9864 | Top32=0.9989

Byte 02 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 29/80 | train_loss=2.1132 | val_loss=2.1440 | lr=1.00e-03 | Top1=0.3713 | Top2=0.5833 | Top4=0.7953 | Top8=0.9349 | Top16=0.9871 | Top32=0.9982

Byte 02 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 30/80 | train_loss=2.0642 | val_loss=2.0804 | lr=1.00e-03 | Top1=0.3871 | Top2=0.6020 | Top4=0.8069 | Top8=0.9404 | Top16=0.9887 | Top32=1.0000

Byte 02 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 31/80 | train_loss=2.0371 | val_loss=2.0736 | lr=1.00e-03 | Top1=0.3882 | Top2=0.6153 | Top4=0.8062 | Top8=0.9411 | Top16=0.9893 | Top32=0.9989

Byte 02 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 32/80 | train_loss=1.9954 | val_loss=2.0290 | lr=1.00e-03 | Top1=0.4064 | Top2=0.6207 | Top4=0.8144 | Top8=0.9460 | Top16=0.9920 | Top32=0.9984

Byte 02 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 33/80 | train_loss=1.9533 | val_loss=1.9421 | lr=1.00e-03 | Top1=0.4247 | Top2=0.6491 | Top4=0.8420 | Top8=0.9582 | Top16=0.9942 | Top32=0.9996

Byte 02 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 34/80 | train_loss=1.9223 | val_loss=1.9222 | lr=1.00e-03 | Top1=0.4302 | Top2=0.6627 | Top4=0.8462 | Top8=0.9596 | Top16=0.9931 | Top32=0.9993

Byte 02 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 35/80 | train_loss=1.8709 | val_loss=1.9743 | lr=1.00e-03 | Top1=0.4322 | Top2=0.6447 | Top4=0.8264 | Top8=0.9511 | Top16=0.9916 | Top32=0.9991

Byte 02 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 36/80 | train_loss=1.8469 | val_loss=1.9487 | lr=1.00e-03 | Top1=0.4280 | Top2=0.6498 | Top4=0.8400 | Top8=0.9544 | Top16=0.9920 | Top32=0.9984

Byte 02 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 37/80 | train_loss=1.8134 | val_loss=1.9291 | lr=1.00e-03 | Top1=0.4380 | Top2=0.6580 | Top4=0.8402 | Top8=0.9571 | Top16=0.9933 | Top32=0.9991

Byte 02 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 38/80 | train_loss=1.7761 | val_loss=1.9721 | lr=1.00e-03 | Top1=0.4273 | Top2=0.6391 | Top4=0.8336 | Top8=0.9536 | Top16=0.9920 | Top32=0.9989

Byte 02 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 39/80 | train_loss=1.7413 | val_loss=1.8701 | lr=1.00e-03 | Top1=0.4613 | Top2=0.6793 | Top4=0.8569 | Top8=0.9611 | Top16=0.9929 | Top32=0.9993

Byte 02 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 40/80 | train_loss=1.7151 | val_loss=1.9550 | lr=1.00e-03 | Top1=0.4484 | Top2=0.6584 | Top4=0.8380 | Top8=0.9533 | Top16=0.9898 | Top32=0.9982

Byte 02 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 41/80 | train_loss=1.6661 | val_loss=1.8336 | lr=1.00e-03 | Top1=0.4751 | Top2=0.6916 | Top4=0.8667 | Top8=0.9622 | Top16=0.9936 | Top32=0.9998

Byte 02 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 42/80 | train_loss=1.6324 | val_loss=1.8418 | lr=1.00e-03 | Top1=0.4764 | Top2=0.6920 | Top4=0.8687 | Top8=0.9624 | Top16=0.9936 | Top32=0.9991

Byte 02 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 43/80 | train_loss=1.6003 | val_loss=1.8584 | lr=1.00e-03 | Top1=0.4724 | Top2=0.6822 | Top4=0.8596 | Top8=0.9611 | Top16=0.9931 | Top32=0.9987

Byte 02 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 44/80 | train_loss=1.5719 | val_loss=1.7788 | lr=1.00e-03 | Top1=0.4931 | Top2=0.7020 | Top4=0.8749 | Top8=0.9642 | Top16=0.9942 | Top32=0.9996

Byte 02 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 45/80 | train_loss=1.5358 | val_loss=1.8375 | lr=1.00e-03 | Top1=0.4880 | Top2=0.6949 | Top4=0.8696 | Top8=0.9624 | Top16=0.9913 | Top32=0.9987

Byte 02 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 46/80 | train_loss=1.5011 | val_loss=1.8222 | lr=1.00e-03 | Top1=0.4976 | Top2=0.7029 | Top4=0.8747 | Top8=0.9624 | Top16=0.9913 | Top32=0.9976

Byte 02 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 47/80 | train_loss=1.4858 | val_loss=1.7783 | lr=1.00e-03 | Top1=0.5078 | Top2=0.7173 | Top4=0.8816 | Top8=0.9680 | Top16=0.9938 | Top32=0.9984

Byte 02 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 48/80 | train_loss=1.4518 | val_loss=1.7821 | lr=1.00e-03 | Top1=0.5087 | Top2=0.7227 | Top4=0.8778 | Top8=0.9658 | Top16=0.9931 | Top32=0.9980

Byte 02 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 49/80 | train_loss=1.4231 | val_loss=1.9012 | lr=1.00e-03 | Top1=0.4773 | Top2=0.6862 | Top4=0.8671 | Top8=0.9582 | Top16=0.9900 | Top32=0.9971

Byte 02 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 50/80 | train_loss=1.3820 | val_loss=1.7857 | lr=1.00e-03 | Top1=0.5056 | Top2=0.7189 | Top4=0.8773 | Top8=0.9696 | Top16=0.9936 | Top32=0.9982

Byte 02 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 51/80 | train_loss=1.3578 | val_loss=1.8546 | lr=1.00e-03 | Top1=0.4882 | Top2=0.6953 | Top4=0.8691 | Top8=0.9609 | Top16=0.9924 | Top32=0.9984

Byte 02 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 52/80 | train_loss=1.3371 | val_loss=1.8527 | lr=1.00e-03 | Top1=0.4918 | Top2=0.7038 | Top4=0.8727 | Top8=0.9640 | Top16=0.9920 | Top32=0.9976

Byte 02 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 53/80 | train_loss=1.3037 | val_loss=1.8701 | lr=1.00e-03 | Top1=0.4947 | Top2=0.7056 | Top4=0.8742 | Top8=0.9613 | Top16=0.9891 | Top32=0.9947

Byte 02 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 54/80 | train_loss=1.1467 | val_loss=1.6314 | lr=5.00e-04 | Top1=0.5711 | Top2=0.7684 | Top4=0.9080 | Top8=0.9736 | Top16=0.9940 | Top32=0.9982

Byte 02 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 55/80 | train_loss=1.0954 | val_loss=1.5983 | lr=5.00e-04 | Top1=0.5664 | Top2=0.7807 | Top4=0.9147 | Top8=0.9776 | Top16=0.9944 | Top32=0.9982

Byte 02 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 56/80 | train_loss=1.0671 | val_loss=1.6411 | lr=5.00e-04 | Top1=0.5593 | Top2=0.7698 | Top4=0.9093 | Top8=0.9762 | Top16=0.9951 | Top32=0.9976

Byte 02 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 57/80 | train_loss=1.0423 | val_loss=1.6715 | lr=5.00e-04 | Top1=0.5613 | Top2=0.7622 | Top4=0.9018 | Top8=0.9753 | Top16=0.9933 | Top32=0.9973

Byte 02 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 58/80 | train_loss=1.0330 | val_loss=1.6405 | lr=5.00e-04 | Top1=0.5671 | Top2=0.7707 | Top4=0.9058 | Top8=0.9753 | Top16=0.9953 | Top32=0.9978

Byte 02 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 59/80 | train_loss=1.0064 | val_loss=1.6094 | lr=5.00e-04 | Top1=0.5762 | Top2=0.7729 | Top4=0.9131 | Top8=0.9767 | Top16=0.9951 | Top32=0.9976

Byte 02 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 60/80 | train_loss=0.9928 | val_loss=1.6043 | lr=5.00e-04 | Top1=0.5816 | Top2=0.7856 | Top4=0.9156 | Top8=0.9773 | Top16=0.9936 | Top32=0.9982

Byte 02 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 61/80 | train_loss=0.9704 | val_loss=1.6623 | lr=5.00e-04 | Top1=0.5636 | Top2=0.7667 | Top4=0.9084 | Top8=0.9762 | Top16=0.9940 | Top32=0.9976

Byte 02 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 62/80 | train_loss=0.9624 | val_loss=1.6849 | lr=5.00e-04 | Top1=0.5656 | Top2=0.7727 | Top4=0.9060 | Top8=0.9724 | Top16=0.9929 | Top32=0.9967

Byte 02 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 63/80 | train_loss=0.9417 | val_loss=1.6253 | lr=5.00e-04 | Top1=0.5796 | Top2=0.7778 | Top4=0.9133 | Top8=0.9796 | Top16=0.9949 | Top32=0.9978

Byte 02 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 64/80 | train_loss=0.9349 | val_loss=1.6718 | lr=5.00e-04 | Top1=0.5756 | Top2=0.7680 | Top4=0.9029 | Top8=0.9713 | Top16=0.9918 | Top32=0.9971

Byte 02 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 65/80 | train_loss=0.9195 | val_loss=1.6256 | lr=5.00e-04 | Top1=0.5758 | Top2=0.7764 | Top4=0.9140 | Top8=0.9760 | Top16=0.9933 | Top32=0.9971

Byte 02 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 66/80 | train_loss=0.9112 | val_loss=1.6727 | lr=5.00e-04 | Top1=0.5696 | Top2=0.7740 | Top4=0.9124 | Top8=0.9742 | Top16=0.9918 | Top32=0.9953

Byte 02 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 67/80 | train_loss=0.8409 | val_loss=1.6225 | lr=2.50e-04 | Top1=0.5900 | Top2=0.7902 | Top4=0.9158 | Top8=0.9762 | Top16=0.9916 | Top32=0.9956

Byte 02 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 68/80 | train_loss=0.8183 | val_loss=1.6246 | lr=2.50e-04 | Top1=0.5936 | Top2=0.7862 | Top4=0.9160 | Top8=0.9760 | Top16=0.9904 | Top32=0.9949

Byte 02 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 69/80 | train_loss=0.8043 | val_loss=1.5999 | lr=2.50e-04 | Top1=0.5973 | Top2=0.7969 | Top4=0.9224 | Top8=0.9776 | Top16=0.9927 | Top32=0.9962

Byte 02 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 70/80 | train_loss=0.7920 | val_loss=1.6121 | lr=2.50e-04 | Top1=0.5916 | Top2=0.7944 | Top4=0.9211 | Top8=0.9758 | Top16=0.9911 | Top32=0.9962

Byte 02 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 71/80 | train_loss=0.7861 | val_loss=1.6018 | lr=2.50e-04 | Top1=0.6031 | Top2=0.7958 | Top4=0.9202 | Top8=0.9773 | Top16=0.9920 | Top32=0.9962

Byte 02 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 72/80 | train_loss=0.7714 | val_loss=1.6556 | lr=2.50e-04 | Top1=0.5902 | Top2=0.7878 | Top4=0.9144 | Top8=0.9720 | Top16=0.9902 | Top32=0.9938

Byte 02 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 73/80 | train_loss=0.7687 | val_loss=1.6013 | lr=2.50e-04 | Top1=0.5973 | Top2=0.7953 | Top4=0.9200 | Top8=0.9771 | Top16=0.9922 | Top32=0.9960

Byte 02 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 74/80 | train_loss=0.7574 | val_loss=1.6098 | lr=2.50e-04 | Top1=0.5936 | Top2=0.7960 | Top4=0.9204 | Top8=0.9758 | Top16=0.9896 | Top32=0.9929

Byte 02 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 75/80 | train_loss=0.7488 | val_loss=1.6027 | lr=2.50e-04 | Top1=0.5964 | Top2=0.7931 | Top4=0.9196 | Top8=0.9771 | Top16=0.9922 | Top32=0.9951

Byte 02 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 76/80 | train_loss=0.7204 | val_loss=1.5930 | lr=1.25e-04 | Top1=0.6016 | Top2=0.7993 | Top4=0.9202 | Top8=0.9764 | Top16=0.9909 | Top32=0.9944

Byte 02 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 77/80 | train_loss=0.7136 | val_loss=1.6137 | lr=1.25e-04 | Top1=0.6000 | Top2=0.7964 | Top4=0.9209 | Top8=0.9758 | Top16=0.9916 | Top32=0.9947

Byte 02 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 78/80 | train_loss=0.7031 | val_loss=1.5985 | lr=1.25e-04 | Top1=0.6040 | Top2=0.7971 | Top4=0.9184 | Top8=0.9773 | Top16=0.9916 | Top32=0.9949

Byte 02 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 79/80 | train_loss=0.6981 | val_loss=1.6024 | lr=1.25e-04 | Top1=0.6047 | Top2=0.8036 | Top4=0.9196 | Top8=0.9771 | Top16=0.9900 | Top32=0.9944

Byte 02 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 02 | Epoch 80/80 | train_loss=0.6931 | val_loss=1.6057 | lr=1.25e-04 | Top1=0.6038 | Top2=0.7987 | Top4=0.9209 | Top8=0.9744 | Top16=0.9896 | Top32=0.9938

Finished ASCON byte 02
Best epoch: 69
Test Top-k: {'top1': 0.6015555262565613, 'top2': 0.7919999957084656, 'top4': 0.9200000166893005, 'top8': 0.9800000190734863, 'top16': 0.9926666617393494, 'top32': 0.9971110820770264}
Grouped Top4: {'grouped_n1_top4': 0.9200000166893005, 'grouped_n2_top4': 0.9840036630630493, 'grouped_n4_top4': 0.9980582594871521, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.00
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_02\byte_02_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_02\byte_02_summary.csv

Loading ASCON byte 03
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_03
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 03 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 01/80 | train_loss=5.5023 | val_loss=5.4416 | lr=1.00e-03 | Top1=0.0082 | Top2=0.0202 | Top4=0.0384 | Top8=0.0727 | Top16=0.1171 | Top32=0.2049

Byte 03 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 02/80 | train_loss=5.2626 | val_loss=5.0919 | lr=1.00e-03 | Top1=0.0138 | Top2=0.0247 | Top4=0.0556 | Top8=0.1122 | Top16=0.1907 | Top32=0.3413

Byte 03 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 03/80 | train_loss=4.9373 | val_loss=4.7176 | lr=1.00e-03 | Top1=0.0196 | Top2=0.0398 | Top4=0.0773 | Top8=0.1547 | Top16=0.2860 | Top32=0.4893

Byte 03 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 04/80 | train_loss=4.5642 | val_loss=4.4137 | lr=1.00e-03 | Top1=0.0329 | Top2=0.0578 | Top4=0.1073 | Top8=0.2016 | Top16=0.3493 | Top32=0.5840

Byte 03 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 05/80 | train_loss=4.3229 | val_loss=4.2273 | lr=1.00e-03 | Top1=0.0331 | Top2=0.0602 | Top4=0.1164 | Top8=0.2256 | Top16=0.3920 | Top32=0.6547

Byte 03 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 06/80 | train_loss=4.1741 | val_loss=4.1008 | lr=1.00e-03 | Top1=0.0404 | Top2=0.0729 | Top4=0.1453 | Top8=0.2740 | Top16=0.4467 | Top32=0.7136

Byte 03 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 07/80 | train_loss=4.0786 | val_loss=3.9247 | lr=1.00e-03 | Top1=0.0542 | Top2=0.0951 | Top4=0.1787 | Top8=0.3247 | Top16=0.5180 | Top32=0.8000

Byte 03 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 08/80 | train_loss=3.9931 | val_loss=3.9158 | lr=1.00e-03 | Top1=0.0540 | Top2=0.0947 | Top4=0.1751 | Top8=0.3258 | Top16=0.5364 | Top32=0.7962

Byte 03 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 09/80 | train_loss=3.9142 | val_loss=3.7816 | lr=1.00e-03 | Top1=0.0653 | Top2=0.1233 | Top4=0.2180 | Top8=0.3862 | Top16=0.6131 | Top32=0.8647

Byte 03 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 10/80 | train_loss=3.8120 | val_loss=3.5965 | lr=1.00e-03 | Top1=0.0956 | Top2=0.1664 | Top4=0.2862 | Top8=0.4751 | Top16=0.6931 | Top32=0.9113

Byte 03 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 11/80 | train_loss=3.6936 | val_loss=3.5063 | lr=1.00e-03 | Top1=0.1047 | Top2=0.1829 | Top4=0.3113 | Top8=0.5096 | Top16=0.7431 | Top32=0.9284

Byte 03 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 12/80 | train_loss=3.5903 | val_loss=3.3953 | lr=1.00e-03 | Top1=0.1131 | Top2=0.2087 | Top4=0.3560 | Top8=0.5660 | Top16=0.7922 | Top32=0.9589

Byte 03 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 13/80 | train_loss=3.4927 | val_loss=3.3709 | lr=1.00e-03 | Top1=0.1242 | Top2=0.2171 | Top4=0.3616 | Top8=0.5660 | Top16=0.8031 | Top32=0.9556

Byte 03 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 14/80 | train_loss=3.3819 | val_loss=3.2170 | lr=1.00e-03 | Top1=0.1444 | Top2=0.2493 | Top4=0.4151 | Top8=0.6322 | Top16=0.8378 | Top32=0.9676

Byte 03 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 15/80 | train_loss=3.2876 | val_loss=3.1450 | lr=1.00e-03 | Top1=0.1500 | Top2=0.2700 | Top4=0.4473 | Top8=0.6684 | Top16=0.8629 | Top32=0.9696

Byte 03 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 16/80 | train_loss=3.2014 | val_loss=2.9795 | lr=1.00e-03 | Top1=0.1927 | Top2=0.3262 | Top4=0.5196 | Top8=0.7262 | Top16=0.9002 | Top32=0.9862

Byte 03 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 17/80 | train_loss=3.0930 | val_loss=2.9652 | lr=1.00e-03 | Top1=0.1856 | Top2=0.3187 | Top4=0.5124 | Top8=0.7213 | Top16=0.9009 | Top32=0.9842

Byte 03 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 18/80 | train_loss=2.9756 | val_loss=2.7367 | lr=1.00e-03 | Top1=0.2351 | Top2=0.3989 | Top4=0.6071 | Top8=0.8067 | Top16=0.9400 | Top32=0.9920

Byte 03 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 19/80 | train_loss=2.8563 | val_loss=2.5718 | lr=1.00e-03 | Top1=0.2876 | Top2=0.4642 | Top4=0.6700 | Top8=0.8458 | Top16=0.9553 | Top32=0.9940

Byte 03 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 20/80 | train_loss=2.6998 | val_loss=2.4374 | lr=1.00e-03 | Top1=0.3156 | Top2=0.5147 | Top4=0.7178 | Top8=0.8798 | Top16=0.9698 | Top32=0.9962

Byte 03 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 21/80 | train_loss=2.5539 | val_loss=2.3645 | lr=1.00e-03 | Top1=0.3458 | Top2=0.5373 | Top4=0.7309 | Top8=0.8851 | Top16=0.9682 | Top32=0.9967

Byte 03 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 22/80 | train_loss=2.4325 | val_loss=2.0981 | lr=1.00e-03 | Top1=0.4340 | Top2=0.6431 | Top4=0.8227 | Top8=0.9347 | Top16=0.9833 | Top32=0.9982

Byte 03 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 23/80 | train_loss=2.3137 | val_loss=2.0812 | lr=1.00e-03 | Top1=0.4322 | Top2=0.6349 | Top4=0.8138 | Top8=0.9382 | Top16=0.9867 | Top32=0.9980

Byte 03 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 24/80 | train_loss=2.2009 | val_loss=1.9575 | lr=1.00e-03 | Top1=0.4676 | Top2=0.6864 | Top4=0.8518 | Top8=0.9491 | Top16=0.9909 | Top32=0.9987

Byte 03 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 25/80 | train_loss=2.1039 | val_loss=1.8851 | lr=1.00e-03 | Top1=0.4938 | Top2=0.7060 | Top4=0.8633 | Top8=0.9578 | Top16=0.9909 | Top32=0.9993

Byte 03 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 26/80 | train_loss=2.0338 | val_loss=1.8068 | lr=1.00e-03 | Top1=0.5213 | Top2=0.7276 | Top4=0.8762 | Top8=0.9660 | Top16=0.9940 | Top32=0.9996

Byte 03 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 27/80 | train_loss=1.9573 | val_loss=1.6934 | lr=1.00e-03 | Top1=0.5600 | Top2=0.7607 | Top4=0.9071 | Top8=0.9742 | Top16=0.9964 | Top32=0.9996

Byte 03 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 28/80 | train_loss=1.8762 | val_loss=1.6810 | lr=1.00e-03 | Top1=0.5682 | Top2=0.7613 | Top4=0.9024 | Top8=0.9716 | Top16=0.9940 | Top32=0.9996

Byte 03 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 29/80 | train_loss=1.8037 | val_loss=1.5715 | lr=1.00e-03 | Top1=0.5940 | Top2=0.7882 | Top4=0.9171 | Top8=0.9791 | Top16=0.9967 | Top32=0.9998

Byte 03 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 30/80 | train_loss=1.7221 | val_loss=1.5369 | lr=1.00e-03 | Top1=0.6209 | Top2=0.8011 | Top4=0.9253 | Top8=0.9771 | Top16=0.9964 | Top32=0.9998

Byte 03 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 31/80 | train_loss=1.6721 | val_loss=1.5773 | lr=1.00e-03 | Top1=0.6002 | Top2=0.7893 | Top4=0.9124 | Top8=0.9784 | Top16=0.9964 | Top32=0.9998

Byte 03 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 32/80 | train_loss=1.5986 | val_loss=1.4990 | lr=1.00e-03 | Top1=0.6342 | Top2=0.8116 | Top4=0.9293 | Top8=0.9829 | Top16=0.9973 | Top32=0.9998

Byte 03 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 33/80 | train_loss=1.5335 | val_loss=1.3983 | lr=1.00e-03 | Top1=0.6573 | Top2=0.8347 | Top4=0.9442 | Top8=0.9864 | Top16=0.9982 | Top32=0.9998

Byte 03 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 34/80 | train_loss=1.4868 | val_loss=1.3994 | lr=1.00e-03 | Top1=0.6573 | Top2=0.8327 | Top4=0.9358 | Top8=0.9851 | Top16=0.9976 | Top32=0.9996

Byte 03 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 35/80 | train_loss=1.4362 | val_loss=1.4372 | lr=1.00e-03 | Top1=0.6442 | Top2=0.8253 | Top4=0.9349 | Top8=0.9811 | Top16=0.9982 | Top32=0.9998

Byte 03 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 36/80 | train_loss=1.3825 | val_loss=1.2707 | lr=1.00e-03 | Top1=0.7076 | Top2=0.8722 | Top4=0.9571 | Top8=0.9911 | Top16=0.9984 | Top32=0.9998

Byte 03 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 37/80 | train_loss=1.3344 | val_loss=1.2555 | lr=1.00e-03 | Top1=0.7000 | Top2=0.8764 | Top4=0.9580 | Top8=0.9911 | Top16=0.9989 | Top32=1.0000

Byte 03 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 38/80 | train_loss=1.2751 | val_loss=1.2619 | lr=1.00e-03 | Top1=0.7164 | Top2=0.8729 | Top4=0.9562 | Top8=0.9898 | Top16=0.9980 | Top32=0.9998

Byte 03 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 39/80 | train_loss=1.2395 | val_loss=1.1356 | lr=1.00e-03 | Top1=0.7538 | Top2=0.8996 | Top4=0.9698 | Top8=0.9931 | Top16=0.9980 | Top32=1.0000

Byte 03 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 40/80 | train_loss=1.1829 | val_loss=1.1353 | lr=1.00e-03 | Top1=0.7462 | Top2=0.9022 | Top4=0.9731 | Top8=0.9938 | Top16=0.9987 | Top32=0.9998

Byte 03 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 41/80 | train_loss=1.1477 | val_loss=1.1228 | lr=1.00e-03 | Top1=0.7600 | Top2=0.9051 | Top4=0.9738 | Top8=0.9942 | Top16=0.9987 | Top32=0.9998

Byte 03 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 42/80 | train_loss=1.1096 | val_loss=1.1178 | lr=1.00e-03 | Top1=0.7553 | Top2=0.9038 | Top4=0.9669 | Top8=0.9942 | Top16=0.9991 | Top32=0.9998

Byte 03 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 43/80 | train_loss=1.0748 | val_loss=1.1657 | lr=1.00e-03 | Top1=0.7387 | Top2=0.8851 | Top4=0.9633 | Top8=0.9913 | Top16=0.9989 | Top32=0.9998

Byte 03 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 44/80 | train_loss=1.0366 | val_loss=1.1138 | lr=1.00e-03 | Top1=0.7520 | Top2=0.8969 | Top4=0.9727 | Top8=0.9938 | Top16=0.9989 | Top32=1.0000

Byte 03 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 45/80 | train_loss=0.9917 | val_loss=0.9874 | lr=1.00e-03 | Top1=0.7978 | Top2=0.9289 | Top4=0.9820 | Top8=0.9967 | Top16=0.9991 | Top32=1.0000

Byte 03 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 46/80 | train_loss=0.9600 | val_loss=0.9337 | lr=1.00e-03 | Top1=0.8129 | Top2=0.9382 | Top4=0.9860 | Top8=0.9971 | Top16=0.9993 | Top32=1.0000

Byte 03 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 47/80 | train_loss=0.9393 | val_loss=1.0182 | lr=1.00e-03 | Top1=0.7920 | Top2=0.9202 | Top4=0.9758 | Top8=0.9953 | Top16=0.9991 | Top32=1.0000

Byte 03 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 48/80 | train_loss=0.9143 | val_loss=0.9588 | lr=1.00e-03 | Top1=0.8011 | Top2=0.9362 | Top4=0.9836 | Top8=0.9967 | Top16=0.9993 | Top32=1.0000

Byte 03 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 49/80 | train_loss=0.8706 | val_loss=0.9606 | lr=1.00e-03 | Top1=0.8002 | Top2=0.9336 | Top4=0.9847 | Top8=0.9967 | Top16=0.9989 | Top32=1.0000

Byte 03 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 50/80 | train_loss=0.8548 | val_loss=1.0688 | lr=1.00e-03 | Top1=0.7664 | Top2=0.9109 | Top4=0.9738 | Top8=0.9940 | Top16=0.9991 | Top32=0.9996

Byte 03 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 51/80 | train_loss=0.8346 | val_loss=0.8922 | lr=1.00e-03 | Top1=0.8309 | Top2=0.9427 | Top4=0.9858 | Top8=0.9978 | Top16=0.9998 | Top32=1.0000

Byte 03 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 52/80 | train_loss=0.8037 | val_loss=0.8959 | lr=1.00e-03 | Top1=0.8249 | Top2=0.9431 | Top4=0.9851 | Top8=0.9967 | Top16=0.9991 | Top32=0.9998

Byte 03 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 53/80 | train_loss=0.6961 | val_loss=0.8227 | lr=5.00e-04 | Top1=0.8471 | Top2=0.9560 | Top4=0.9884 | Top8=0.9962 | Top16=0.9996 | Top32=1.0000

Byte 03 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 54/80 | train_loss=0.6650 | val_loss=0.7635 | lr=5.00e-04 | Top1=0.8704 | Top2=0.9662 | Top4=0.9933 | Top8=0.9993 | Top16=0.9998 | Top32=1.0000

Byte 03 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 55/80 | train_loss=0.6421 | val_loss=0.8259 | lr=5.00e-04 | Top1=0.8518 | Top2=0.9524 | Top4=0.9867 | Top8=0.9967 | Top16=0.9998 | Top32=1.0000

Byte 03 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 56/80 | train_loss=0.6340 | val_loss=0.7958 | lr=5.00e-04 | Top1=0.8542 | Top2=0.9616 | Top4=0.9916 | Top8=0.9978 | Top16=0.9996 | Top32=0.9998

Byte 03 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 57/80 | train_loss=0.6214 | val_loss=0.7675 | lr=5.00e-04 | Top1=0.8678 | Top2=0.9609 | Top4=0.9922 | Top8=0.9984 | Top16=0.9998 | Top32=1.0000

Byte 03 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 58/80 | train_loss=0.6110 | val_loss=0.7645 | lr=5.00e-04 | Top1=0.8662 | Top2=0.9631 | Top4=0.9918 | Top8=0.9987 | Top16=0.9998 | Top32=1.0000

Byte 03 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 59/80 | train_loss=0.5964 | val_loss=0.8104 | lr=5.00e-04 | Top1=0.8527 | Top2=0.9551 | Top4=0.9896 | Top8=0.9982 | Top16=0.9991 | Top32=0.9996

Byte 03 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 60/80 | train_loss=0.5894 | val_loss=0.7335 | lr=5.00e-04 | Top1=0.8793 | Top2=0.9669 | Top4=0.9938 | Top8=0.9989 | Top16=0.9996 | Top32=1.0000

Byte 03 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 61/80 | train_loss=0.5814 | val_loss=0.7476 | lr=5.00e-04 | Top1=0.8700 | Top2=0.9660 | Top4=0.9927 | Top8=0.9989 | Top16=0.9998 | Top32=1.0000

Byte 03 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 62/80 | train_loss=0.5781 | val_loss=0.7236 | lr=5.00e-04 | Top1=0.8809 | Top2=0.9691 | Top4=0.9927 | Top8=0.9987 | Top16=0.9996 | Top32=0.9996

Byte 03 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 63/80 | train_loss=0.5721 | val_loss=0.7282 | lr=5.00e-04 | Top1=0.8798 | Top2=0.9642 | Top4=0.9938 | Top8=0.9987 | Top16=0.9993 | Top32=0.9996

Byte 03 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 64/80 | train_loss=0.5585 | val_loss=0.7225 | lr=5.00e-04 | Top1=0.8831 | Top2=0.9680 | Top4=0.9931 | Top8=0.9984 | Top16=1.0000 | Top32=1.0000

Byte 03 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 65/80 | train_loss=0.5513 | val_loss=0.7547 | lr=5.00e-04 | Top1=0.8669 | Top2=0.9642 | Top4=0.9907 | Top8=0.9989 | Top16=0.9991 | Top32=0.9996

Byte 03 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 66/80 | train_loss=0.5431 | val_loss=0.7200 | lr=5.00e-04 | Top1=0.8773 | Top2=0.9684 | Top4=0.9918 | Top8=0.9982 | Top16=0.9991 | Top32=0.9998

Byte 03 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 67/80 | train_loss=0.5114 | val_loss=0.6732 | lr=2.50e-04 | Top1=0.8956 | Top2=0.9747 | Top4=0.9927 | Top8=0.9996 | Top16=0.9998 | Top32=0.9998

Byte 03 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 68/80 | train_loss=0.5054 | val_loss=0.6896 | lr=2.50e-04 | Top1=0.8876 | Top2=0.9689 | Top4=0.9942 | Top8=0.9989 | Top16=0.9996 | Top32=0.9998

Byte 03 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 69/80 | train_loss=0.4952 | val_loss=0.6711 | lr=2.50e-04 | Top1=0.8973 | Top2=0.9749 | Top4=0.9942 | Top8=0.9993 | Top16=0.9996 | Top32=0.9996

Byte 03 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 70/80 | train_loss=0.4882 | val_loss=0.6656 | lr=2.50e-04 | Top1=0.8982 | Top2=0.9727 | Top4=0.9956 | Top8=0.9996 | Top16=0.9996 | Top32=1.0000

Byte 03 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 71/80 | train_loss=0.4870 | val_loss=0.6626 | lr=2.50e-04 | Top1=0.8962 | Top2=0.9733 | Top4=0.9956 | Top8=0.9996 | Top16=0.9996 | Top32=0.9998

Byte 03 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 72/80 | train_loss=0.4891 | val_loss=0.6866 | lr=2.50e-04 | Top1=0.8936 | Top2=0.9718 | Top4=0.9953 | Top8=0.9989 | Top16=0.9996 | Top32=0.9996

Byte 03 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 73/80 | train_loss=0.4800 | val_loss=0.6573 | lr=2.50e-04 | Top1=0.8978 | Top2=0.9769 | Top4=0.9947 | Top8=0.9993 | Top16=0.9996 | Top32=0.9996

Byte 03 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 74/80 | train_loss=0.4769 | val_loss=0.6913 | lr=2.50e-04 | Top1=0.8856 | Top2=0.9702 | Top4=0.9924 | Top8=0.9989 | Top16=0.9996 | Top32=0.9996

Byte 03 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 75/80 | train_loss=0.4746 | val_loss=0.6920 | lr=2.50e-04 | Top1=0.8902 | Top2=0.9691 | Top4=0.9938 | Top8=0.9989 | Top16=0.9998 | Top32=0.9998

Byte 03 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 76/80 | train_loss=0.4718 | val_loss=0.6662 | lr=2.50e-04 | Top1=0.8984 | Top2=0.9738 | Top4=0.9958 | Top8=0.9993 | Top16=0.9998 | Top32=0.9998

Byte 03 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 77/80 | train_loss=0.4681 | val_loss=0.6492 | lr=2.50e-04 | Top1=0.9027 | Top2=0.9760 | Top4=0.9951 | Top8=0.9993 | Top16=0.9998 | Top32=0.9998

Byte 03 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 78/80 | train_loss=0.4658 | val_loss=0.6528 | lr=2.50e-04 | Top1=0.8987 | Top2=0.9747 | Top4=0.9951 | Top8=0.9996 | Top16=0.9998 | Top32=0.9998

Byte 03 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 79/80 | train_loss=0.4611 | val_loss=0.6800 | lr=2.50e-04 | Top1=0.8911 | Top2=0.9722 | Top4=0.9931 | Top8=0.9987 | Top16=0.9996 | Top32=0.9998

Byte 03 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 03 | Epoch 80/80 | train_loss=0.4619 | val_loss=0.6596 | lr=2.50e-04 | Top1=0.9011 | Top2=0.9773 | Top4=0.9938 | Top8=0.9987 | Top16=0.9998 | Top32=0.9998

Finished ASCON byte 03
Best epoch: 76
Test Top-k: {'top1': 0.8882222175598145, 'top2': 0.9706666469573975, 'top4': 0.9944444298744202, 'top8': 0.9991111159324646, 'top16': 1.0, 'top32': 1.0}
Grouped Top4: {'grouped_n1_top4': 0.9944444298744202, 'grouped_n2_top4': 1.0, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.05
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_03\byte_03_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_03\byte_03_summary.csv

Loading ASCON byte 04
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_04
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 04 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 01/80 | train_loss=5.4770 | val_loss=5.2982 | lr=1.00e-03 | Top1=0.0102 | Top2=0.0187 | Top4=0.0393 | Top8=0.0822 | Top16=0.1447 | Top32=0.2504

Byte 04 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 02/80 | train_loss=5.2038 | val_loss=5.0117 | lr=1.00e-03 | Top1=0.0167 | Top2=0.0333 | Top4=0.0620 | Top8=0.1300 | Top16=0.2189 | Top32=0.3711

Byte 04 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 03/80 | train_loss=4.6516 | val_loss=4.3956 | lr=1.00e-03 | Top1=0.0291 | Top2=0.0578 | Top4=0.1100 | Top8=0.2044 | Top16=0.3407 | Top32=0.5960

Byte 04 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 04/80 | train_loss=4.2394 | val_loss=4.0869 | lr=1.00e-03 | Top1=0.0433 | Top2=0.0776 | Top4=0.1384 | Top8=0.2591 | Top16=0.4422 | Top32=0.7156

Byte 04 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 05/80 | train_loss=4.0465 | val_loss=3.9543 | lr=1.00e-03 | Top1=0.0480 | Top2=0.0842 | Top4=0.1602 | Top8=0.2964 | Top16=0.5044 | Top32=0.7744

Byte 04 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 06/80 | train_loss=3.9464 | val_loss=3.9725 | lr=1.00e-03 | Top1=0.0453 | Top2=0.0773 | Top4=0.1524 | Top8=0.2840 | Top16=0.4873 | Top32=0.7804

Byte 04 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 07/80 | train_loss=3.8818 | val_loss=3.8571 | lr=1.00e-03 | Top1=0.0522 | Top2=0.1000 | Top4=0.1856 | Top8=0.3240 | Top16=0.5338 | Top32=0.8264

Byte 04 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 08/80 | train_loss=3.8338 | val_loss=3.7265 | lr=1.00e-03 | Top1=0.0591 | Top2=0.1153 | Top4=0.2087 | Top8=0.3802 | Top16=0.5956 | Top32=0.8656

Byte 04 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 09/80 | train_loss=3.7902 | val_loss=3.7281 | lr=1.00e-03 | Top1=0.0611 | Top2=0.1124 | Top4=0.2093 | Top8=0.3718 | Top16=0.5953 | Top32=0.8591

Byte 04 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 10/80 | train_loss=3.7436 | val_loss=3.6971 | lr=1.00e-03 | Top1=0.0611 | Top2=0.1131 | Top4=0.2124 | Top8=0.3809 | Top16=0.6162 | Top32=0.8882

Byte 04 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 11/80 | train_loss=3.7129 | val_loss=3.6685 | lr=1.00e-03 | Top1=0.0687 | Top2=0.1204 | Top4=0.2249 | Top8=0.3929 | Top16=0.6238 | Top32=0.8858

Byte 04 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 12/80 | train_loss=3.6510 | val_loss=3.5504 | lr=1.00e-03 | Top1=0.0756 | Top2=0.1447 | Top4=0.2604 | Top8=0.4462 | Top16=0.6787 | Top32=0.9200

Byte 04 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 13/80 | train_loss=3.6214 | val_loss=3.6129 | lr=1.00e-03 | Top1=0.0744 | Top2=0.1353 | Top4=0.2467 | Top8=0.4253 | Top16=0.6564 | Top32=0.8976

Byte 04 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 14/80 | train_loss=3.5931 | val_loss=3.5112 | lr=1.00e-03 | Top1=0.0836 | Top2=0.1502 | Top4=0.2724 | Top8=0.4538 | Top16=0.6920 | Top32=0.9256

Byte 04 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 15/80 | train_loss=3.5474 | val_loss=3.5090 | lr=1.00e-03 | Top1=0.0891 | Top2=0.1516 | Top4=0.2760 | Top8=0.4736 | Top16=0.7016 | Top32=0.9213

Byte 04 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 16/80 | train_loss=3.5076 | val_loss=3.4834 | lr=1.00e-03 | Top1=0.0900 | Top2=0.1622 | Top4=0.2913 | Top8=0.4802 | Top16=0.6996 | Top32=0.9204

Byte 04 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 17/80 | train_loss=3.4822 | val_loss=3.4223 | lr=1.00e-03 | Top1=0.0942 | Top2=0.1680 | Top4=0.3098 | Top8=0.5038 | Top16=0.7338 | Top32=0.9393

Byte 04 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 18/80 | train_loss=3.4569 | val_loss=3.5503 | lr=1.00e-03 | Top1=0.0827 | Top2=0.1529 | Top4=0.2744 | Top8=0.4542 | Top16=0.6860 | Top32=0.9244

Byte 04 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 19/80 | train_loss=3.4162 | val_loss=3.3504 | lr=1.00e-03 | Top1=0.1069 | Top2=0.1969 | Top4=0.3391 | Top8=0.5384 | Top16=0.7649 | Top32=0.9518

Byte 04 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 20/80 | train_loss=3.3753 | val_loss=3.3455 | lr=1.00e-03 | Top1=0.1120 | Top2=0.1984 | Top4=0.3489 | Top8=0.5669 | Top16=0.7724 | Top32=0.9489

Byte 04 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 21/80 | train_loss=3.3507 | val_loss=3.2874 | lr=1.00e-03 | Top1=0.1224 | Top2=0.2136 | Top4=0.3716 | Top8=0.5829 | Top16=0.7973 | Top32=0.9649

Byte 04 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 22/80 | train_loss=3.3011 | val_loss=3.2930 | lr=1.00e-03 | Top1=0.1240 | Top2=0.2213 | Top4=0.3753 | Top8=0.5824 | Top16=0.7927 | Top32=0.9529

Byte 04 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 23/80 | train_loss=3.2631 | val_loss=3.2247 | lr=1.00e-03 | Top1=0.1384 | Top2=0.2436 | Top4=0.4011 | Top8=0.6129 | Top16=0.8162 | Top32=0.9627

Byte 04 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 24/80 | train_loss=3.2165 | val_loss=3.1583 | lr=1.00e-03 | Top1=0.1424 | Top2=0.2507 | Top4=0.4187 | Top8=0.6329 | Top16=0.8422 | Top32=0.9724

Byte 04 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 25/80 | train_loss=3.1651 | val_loss=3.1607 | lr=1.00e-03 | Top1=0.1489 | Top2=0.2551 | Top4=0.4296 | Top8=0.6429 | Top16=0.8416 | Top32=0.9673

Byte 04 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 26/80 | train_loss=3.1243 | val_loss=3.0746 | lr=1.00e-03 | Top1=0.1591 | Top2=0.2869 | Top4=0.4636 | Top8=0.6780 | Top16=0.8596 | Top32=0.9787

Byte 04 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 27/80 | train_loss=3.0872 | val_loss=3.1386 | lr=1.00e-03 | Top1=0.1509 | Top2=0.2733 | Top4=0.4420 | Top8=0.6424 | Top16=0.8418 | Top32=0.9682

Byte 04 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 28/80 | train_loss=3.0526 | val_loss=3.1310 | lr=1.00e-03 | Top1=0.1678 | Top2=0.2798 | Top4=0.4562 | Top8=0.6518 | Top16=0.8384 | Top32=0.9642

Byte 04 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 29/80 | train_loss=2.9941 | val_loss=3.0175 | lr=1.00e-03 | Top1=0.1811 | Top2=0.3007 | Top4=0.4747 | Top8=0.6953 | Top16=0.8684 | Top32=0.9769

Byte 04 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 30/80 | train_loss=2.9574 | val_loss=3.1033 | lr=1.00e-03 | Top1=0.1656 | Top2=0.2820 | Top4=0.4684 | Top8=0.6682 | Top16=0.8493 | Top32=0.9691

Byte 04 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 31/80 | train_loss=2.9186 | val_loss=2.9537 | lr=1.00e-03 | Top1=0.1820 | Top2=0.3218 | Top4=0.5082 | Top8=0.7211 | Top16=0.8882 | Top32=0.9816

Byte 04 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 32/80 | train_loss=2.8818 | val_loss=2.9351 | lr=1.00e-03 | Top1=0.1933 | Top2=0.3249 | Top4=0.5151 | Top8=0.7178 | Top16=0.8884 | Top32=0.9836

Byte 04 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 33/80 | train_loss=2.8501 | val_loss=3.0106 | lr=1.00e-03 | Top1=0.1827 | Top2=0.3089 | Top4=0.4911 | Top8=0.7020 | Top16=0.8816 | Top32=0.9802

Byte 04 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 34/80 | train_loss=2.8061 | val_loss=2.8589 | lr=1.00e-03 | Top1=0.2049 | Top2=0.3531 | Top4=0.5502 | Top8=0.7524 | Top16=0.9080 | Top32=0.9847

Byte 04 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 35/80 | train_loss=2.7597 | val_loss=2.8970 | lr=1.00e-03 | Top1=0.2053 | Top2=0.3464 | Top4=0.5318 | Top8=0.7396 | Top16=0.9036 | Top32=0.9844

Byte 04 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 36/80 | train_loss=2.7365 | val_loss=2.9255 | lr=1.00e-03 | Top1=0.2029 | Top2=0.3404 | Top4=0.5316 | Top8=0.7402 | Top16=0.8900 | Top32=0.9816

Byte 04 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 37/80 | train_loss=2.7090 | val_loss=2.8925 | lr=1.00e-03 | Top1=0.2138 | Top2=0.3567 | Top4=0.5393 | Top8=0.7431 | Top16=0.8967 | Top32=0.9844

Byte 04 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 38/80 | train_loss=2.6518 | val_loss=3.0887 | lr=1.00e-03 | Top1=0.1898 | Top2=0.3102 | Top4=0.4869 | Top8=0.6944 | Top16=0.8691 | Top32=0.9764

Byte 04 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 39/80 | train_loss=2.6159 | val_loss=2.8877 | lr=1.00e-03 | Top1=0.2047 | Top2=0.3467 | Top4=0.5469 | Top8=0.7473 | Top16=0.9102 | Top32=0.9856

Byte 04 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 40/80 | train_loss=2.5790 | val_loss=2.7751 | lr=1.00e-03 | Top1=0.2260 | Top2=0.3731 | Top4=0.5811 | Top8=0.7816 | Top16=0.9253 | Top32=0.9900

Byte 04 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 41/80 | train_loss=2.5477 | val_loss=2.7615 | lr=1.00e-03 | Top1=0.2262 | Top2=0.3776 | Top4=0.5842 | Top8=0.7827 | Top16=0.9244 | Top32=0.9871

Byte 04 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 42/80 | train_loss=2.5186 | val_loss=2.7439 | lr=1.00e-03 | Top1=0.2447 | Top2=0.3953 | Top4=0.5936 | Top8=0.7907 | Top16=0.9282 | Top32=0.9900

Byte 04 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 43/80 | train_loss=2.4653 | val_loss=2.8972 | lr=1.00e-03 | Top1=0.2182 | Top2=0.3680 | Top4=0.5549 | Top8=0.7642 | Top16=0.9082 | Top32=0.9838

Byte 04 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 44/80 | train_loss=2.4281 | val_loss=2.8856 | lr=1.00e-03 | Top1=0.2231 | Top2=0.3691 | Top4=0.5633 | Top8=0.7653 | Top16=0.9124 | Top32=0.9849

Byte 04 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 45/80 | train_loss=2.4090 | val_loss=2.8671 | lr=1.00e-03 | Top1=0.2204 | Top2=0.3662 | Top4=0.5653 | Top8=0.7684 | Top16=0.9153 | Top32=0.9856

Byte 04 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 46/80 | train_loss=2.3836 | val_loss=2.8202 | lr=1.00e-03 | Top1=0.2353 | Top2=0.3796 | Top4=0.5733 | Top8=0.7709 | Top16=0.9196 | Top32=0.9869

Byte 04 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 47/80 | train_loss=2.3337 | val_loss=2.7566 | lr=1.00e-03 | Top1=0.2420 | Top2=0.3989 | Top4=0.6007 | Top8=0.7902 | Top16=0.9284 | Top32=0.9887

Byte 04 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 48/80 | train_loss=2.2968 | val_loss=2.7536 | lr=1.00e-03 | Top1=0.2458 | Top2=0.3947 | Top4=0.6018 | Top8=0.7931 | Top16=0.9293 | Top32=0.9887

Byte 04 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 49/80 | train_loss=2.2595 | val_loss=2.7360 | lr=1.00e-03 | Top1=0.2540 | Top2=0.4062 | Top4=0.6047 | Top8=0.7973 | Top16=0.9380 | Top32=0.9907

Byte 04 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 50/80 | train_loss=2.2391 | val_loss=2.7382 | lr=1.00e-03 | Top1=0.2531 | Top2=0.4160 | Top4=0.6069 | Top8=0.7953 | Top16=0.9340 | Top32=0.9891

Byte 04 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 51/80 | train_loss=2.1952 | val_loss=2.6913 | lr=1.00e-03 | Top1=0.2700 | Top2=0.4302 | Top4=0.6247 | Top8=0.8082 | Top16=0.9309 | Top32=0.9896

Byte 04 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 52/80 | train_loss=2.1674 | val_loss=2.6260 | lr=1.00e-03 | Top1=0.2838 | Top2=0.4460 | Top4=0.6351 | Top8=0.8222 | Top16=0.9476 | Top32=0.9927

Byte 04 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 53/80 | train_loss=2.1383 | val_loss=2.7537 | lr=1.00e-03 | Top1=0.2609 | Top2=0.4120 | Top4=0.6153 | Top8=0.8042 | Top16=0.9300 | Top32=0.9882

Byte 04 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 54/80 | train_loss=2.1083 | val_loss=2.8165 | lr=1.00e-03 | Top1=0.2493 | Top2=0.4071 | Top4=0.6007 | Top8=0.7904 | Top16=0.9296 | Top32=0.9878

Byte 04 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 55/80 | train_loss=2.0815 | val_loss=2.6582 | lr=1.00e-03 | Top1=0.2884 | Top2=0.4513 | Top4=0.6427 | Top8=0.8224 | Top16=0.9409 | Top32=0.9936

Byte 04 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 56/80 | train_loss=2.0301 | val_loss=2.6093 | lr=1.00e-03 | Top1=0.2884 | Top2=0.4542 | Top4=0.6507 | Top8=0.8407 | Top16=0.9462 | Top32=0.9909

Byte 04 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 57/80 | train_loss=2.0125 | val_loss=2.7873 | lr=1.00e-03 | Top1=0.2682 | Top2=0.4222 | Top4=0.6173 | Top8=0.8033 | Top16=0.9311 | Top32=0.9856

Byte 04 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 58/80 | train_loss=1.9755 | val_loss=2.6074 | lr=1.00e-03 | Top1=0.2942 | Top2=0.4513 | Top4=0.6462 | Top8=0.8316 | Top16=0.9482 | Top32=0.9918

Byte 04 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 59/80 | train_loss=1.9443 | val_loss=2.9588 | lr=1.00e-03 | Top1=0.2456 | Top2=0.3989 | Top4=0.5964 | Top8=0.7862 | Top16=0.9200 | Top32=0.9809

Byte 04 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 60/80 | train_loss=1.9407 | val_loss=2.6792 | lr=1.00e-03 | Top1=0.2844 | Top2=0.4456 | Top4=0.6431 | Top8=0.8240 | Top16=0.9371 | Top32=0.9893

Byte 04 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 61/80 | train_loss=1.8991 | val_loss=2.6612 | lr=1.00e-03 | Top1=0.2904 | Top2=0.4533 | Top4=0.6500 | Top8=0.8289 | Top16=0.9424 | Top32=0.9889

Byte 04 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 62/80 | train_loss=1.8693 | val_loss=2.6948 | lr=1.00e-03 | Top1=0.2920 | Top2=0.4567 | Top4=0.6467 | Top8=0.8269 | Top16=0.9420 | Top32=0.9902

Byte 04 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 63/80 | train_loss=1.6912 | val_loss=2.6661 | lr=5.00e-04 | Top1=0.3107 | Top2=0.4858 | Top4=0.6771 | Top8=0.8456 | Top16=0.9473 | Top32=0.9902

Byte 04 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 64/80 | train_loss=1.6355 | val_loss=2.5418 | lr=5.00e-04 | Top1=0.3276 | Top2=0.4964 | Top4=0.6969 | Top8=0.8596 | Top16=0.9564 | Top32=0.9924

Byte 04 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 65/80 | train_loss=1.6040 | val_loss=2.8194 | lr=5.00e-04 | Top1=0.2953 | Top2=0.4629 | Top4=0.6562 | Top8=0.8273 | Top16=0.9396 | Top32=0.9856

Byte 04 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 66/80 | train_loss=1.5709 | val_loss=2.6292 | lr=5.00e-04 | Top1=0.3167 | Top2=0.4916 | Top4=0.6924 | Top8=0.8544 | Top16=0.9576 | Top32=0.9884

Byte 04 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 67/80 | train_loss=1.5534 | val_loss=2.7023 | lr=5.00e-04 | Top1=0.3116 | Top2=0.4833 | Top4=0.6707 | Top8=0.8387 | Top16=0.9451 | Top32=0.9871

Byte 04 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 68/80 | train_loss=1.5309 | val_loss=2.8550 | lr=5.00e-04 | Top1=0.2929 | Top2=0.4598 | Top4=0.6638 | Top8=0.8300 | Top16=0.9398 | Top32=0.9860

Byte 04 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 69/80 | train_loss=1.5180 | val_loss=2.6405 | lr=5.00e-04 | Top1=0.3222 | Top2=0.4951 | Top4=0.6922 | Top8=0.8527 | Top16=0.9569 | Top32=0.9916

Byte 04 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 70/80 | train_loss=1.5059 | val_loss=2.6670 | lr=5.00e-04 | Top1=0.3180 | Top2=0.4907 | Top4=0.6838 | Top8=0.8469 | Top16=0.9511 | Top32=0.9898

Byte 04 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 71/80 | train_loss=1.3990 | val_loss=2.5136 | lr=2.50e-04 | Top1=0.3362 | Top2=0.5216 | Top4=0.7147 | Top8=0.8656 | Top16=0.9633 | Top32=0.9918

Byte 04 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 72/80 | train_loss=1.3723 | val_loss=2.6333 | lr=2.50e-04 | Top1=0.3324 | Top2=0.5056 | Top4=0.6898 | Top8=0.8553 | Top16=0.9571 | Top32=0.9907

Byte 04 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 73/80 | train_loss=1.3506 | val_loss=2.6807 | lr=2.50e-04 | Top1=0.3271 | Top2=0.5020 | Top4=0.6962 | Top8=0.8560 | Top16=0.9549 | Top32=0.9900

Byte 04 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 74/80 | train_loss=1.3431 | val_loss=2.6760 | lr=2.50e-04 | Top1=0.3267 | Top2=0.4993 | Top4=0.6967 | Top8=0.8540 | Top16=0.9520 | Top32=0.9907

Byte 04 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 75/80 | train_loss=1.3266 | val_loss=2.7834 | lr=2.50e-04 | Top1=0.3133 | Top2=0.4847 | Top4=0.6780 | Top8=0.8427 | Top16=0.9458 | Top32=0.9858

Byte 04 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 76/80 | train_loss=1.3119 | val_loss=2.9077 | lr=2.50e-04 | Top1=0.3076 | Top2=0.4747 | Top4=0.6642 | Top8=0.8302 | Top16=0.9382 | Top32=0.9791

Byte 04 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 77/80 | train_loss=1.2993 | val_loss=2.9513 | lr=2.50e-04 | Top1=0.3040 | Top2=0.4787 | Top4=0.6600 | Top8=0.8331 | Top16=0.9376 | Top32=0.9780

Byte 04 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 78/80 | train_loss=1.2567 | val_loss=2.6516 | lr=1.25e-04 | Top1=0.3340 | Top2=0.5131 | Top4=0.7009 | Top8=0.8611 | Top16=0.9569 | Top32=0.9902

Byte 04 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 79/80 | train_loss=1.2464 | val_loss=2.8010 | lr=1.25e-04 | Top1=0.3193 | Top2=0.4956 | Top4=0.6867 | Top8=0.8458 | Top16=0.9489 | Top32=0.9860

Byte 04 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 04 | Epoch 80/80 | train_loss=1.2337 | val_loss=2.8671 | lr=1.25e-04 | Top1=0.3100 | Top2=0.4782 | Top4=0.6729 | Top8=0.8418 | Top16=0.9420 | Top32=0.9822

Finished ASCON byte 04
Best epoch: 71
Test Top-k: {'top1': 0.33533334732055664, 'top2': 0.5199999809265137, 'top4': 0.7088888883590698, 'top8': 0.8682222366333008, 'top16': 0.9602222442626953, 'top32': 0.9902222156524658}
Grouped Top4: {'grouped_n1_top4': 0.7088888883590698, 'grouped_n2_top4': 0.8623685240745544, 'grouped_n4_top4': 0.951171875, 'grouped_n8_top4': 0.9937759041786194, 'grouped_n12_top4': 0.9921875, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.02
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_04\byte_04_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_04\byte_04_summary.csv

Loading ASCON byte 05
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_05
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 05 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 01/80 | train_loss=5.4965 | val_loss=5.3659 | lr=1.00e-03 | Top1=0.0098 | Top2=0.0184 | Top4=0.0327 | Top8=0.0653 | Top16=0.1240 | Top32=0.2249

Byte 05 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 02/80 | train_loss=5.1617 | val_loss=5.0605 | lr=1.00e-03 | Top1=0.0136 | Top2=0.0298 | Top4=0.0631 | Top8=0.1204 | Top16=0.2018 | Top32=0.3422

Byte 05 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 03/80 | train_loss=4.4286 | val_loss=4.1338 | lr=1.00e-03 | Top1=0.0398 | Top2=0.0687 | Top4=0.1347 | Top8=0.2462 | Top16=0.4093 | Top32=0.6778

Byte 05 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 04/80 | train_loss=4.1244 | val_loss=4.0410 | lr=1.00e-03 | Top1=0.0427 | Top2=0.0791 | Top4=0.1449 | Top8=0.2669 | Top16=0.4647 | Top32=0.7376

Byte 05 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 05/80 | train_loss=4.0134 | val_loss=3.9111 | lr=1.00e-03 | Top1=0.0482 | Top2=0.0907 | Top4=0.1682 | Top8=0.3113 | Top16=0.5076 | Top32=0.7936

Byte 05 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 06/80 | train_loss=3.9229 | val_loss=3.8484 | lr=1.00e-03 | Top1=0.0513 | Top2=0.0927 | Top4=0.1731 | Top8=0.3171 | Top16=0.5331 | Top32=0.8171

Byte 05 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 07/80 | train_loss=3.8571 | val_loss=3.8160 | lr=1.00e-03 | Top1=0.0553 | Top2=0.1040 | Top4=0.1860 | Top8=0.3387 | Top16=0.5516 | Top32=0.8287

Byte 05 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 08/80 | train_loss=3.8063 | val_loss=3.8790 | lr=1.00e-03 | Top1=0.0538 | Top2=0.0996 | Top4=0.1889 | Top8=0.3349 | Top16=0.5431 | Top32=0.8247

Byte 05 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 09/80 | train_loss=3.7678 | val_loss=3.7953 | lr=1.00e-03 | Top1=0.0518 | Top2=0.0987 | Top4=0.1851 | Top8=0.3502 | Top16=0.5836 | Top32=0.8796

Byte 05 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 10/80 | train_loss=3.7446 | val_loss=3.6875 | lr=1.00e-03 | Top1=0.0707 | Top2=0.1240 | Top4=0.2233 | Top8=0.3953 | Top16=0.6327 | Top32=0.8993

Byte 05 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 11/80 | train_loss=3.7055 | val_loss=3.6424 | lr=1.00e-03 | Top1=0.0667 | Top2=0.1176 | Top4=0.2324 | Top8=0.4071 | Top16=0.6411 | Top32=0.8980

Byte 05 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 12/80 | train_loss=3.6489 | val_loss=3.6512 | lr=1.00e-03 | Top1=0.0740 | Top2=0.1400 | Top4=0.2396 | Top8=0.4116 | Top16=0.6438 | Top32=0.8860

Byte 05 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 13/80 | train_loss=3.5979 | val_loss=3.5253 | lr=1.00e-03 | Top1=0.0880 | Top2=0.1564 | Top4=0.2742 | Top8=0.4722 | Top16=0.7113 | Top32=0.9353

Byte 05 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 14/80 | train_loss=3.4981 | val_loss=3.3814 | lr=1.00e-03 | Top1=0.1053 | Top2=0.1900 | Top4=0.3162 | Top8=0.5300 | Top16=0.7804 | Top32=0.9576

Byte 05 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 15/80 | train_loss=3.3846 | val_loss=3.2729 | lr=1.00e-03 | Top1=0.1064 | Top2=0.1967 | Top4=0.3498 | Top8=0.5773 | Top16=0.8280 | Top32=0.9767

Byte 05 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 16/80 | train_loss=3.2536 | val_loss=3.2398 | lr=1.00e-03 | Top1=0.1096 | Top2=0.2002 | Top4=0.3478 | Top8=0.5909 | Top16=0.8453 | Top32=0.9816

Byte 05 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 17/80 | train_loss=3.1505 | val_loss=3.0620 | lr=1.00e-03 | Top1=0.1442 | Top2=0.2467 | Top4=0.4093 | Top8=0.6507 | Top16=0.8831 | Top32=0.9873

Byte 05 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 18/80 | train_loss=3.0639 | val_loss=3.0609 | lr=1.00e-03 | Top1=0.1400 | Top2=0.2427 | Top4=0.4131 | Top8=0.6578 | Top16=0.8938 | Top32=0.9924

Byte 05 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 19/80 | train_loss=2.9875 | val_loss=2.9827 | lr=1.00e-03 | Top1=0.1547 | Top2=0.2680 | Top4=0.4569 | Top8=0.6900 | Top16=0.9049 | Top32=0.9920

Byte 05 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 20/80 | train_loss=2.9326 | val_loss=2.9788 | lr=1.00e-03 | Top1=0.1653 | Top2=0.2796 | Top4=0.4622 | Top8=0.6889 | Top16=0.8998 | Top32=0.9911

Byte 05 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 21/80 | train_loss=2.8747 | val_loss=2.8499 | lr=1.00e-03 | Top1=0.1944 | Top2=0.3136 | Top4=0.5129 | Top8=0.7504 | Top16=0.9338 | Top32=0.9962

Byte 05 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 22/80 | train_loss=2.8105 | val_loss=2.8041 | lr=1.00e-03 | Top1=0.1976 | Top2=0.3336 | Top4=0.5387 | Top8=0.7684 | Top16=0.9380 | Top32=0.9944

Byte 05 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 23/80 | train_loss=2.7287 | val_loss=2.7101 | lr=1.00e-03 | Top1=0.2209 | Top2=0.3689 | Top4=0.5782 | Top8=0.7987 | Top16=0.9496 | Top32=0.9964

Byte 05 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 24/80 | train_loss=2.6676 | val_loss=2.7285 | lr=1.00e-03 | Top1=0.2144 | Top2=0.3613 | Top4=0.5740 | Top8=0.7929 | Top16=0.9518 | Top32=0.9973

Byte 05 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 25/80 | train_loss=2.5875 | val_loss=2.5819 | lr=1.00e-03 | Top1=0.2533 | Top2=0.4138 | Top4=0.6176 | Top8=0.8433 | Top16=0.9673 | Top32=0.9964

Byte 05 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 26/80 | train_loss=2.5401 | val_loss=2.5853 | lr=1.00e-03 | Top1=0.2502 | Top2=0.4191 | Top4=0.6324 | Top8=0.8440 | Top16=0.9662 | Top32=0.9967

Byte 05 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 27/80 | train_loss=2.4678 | val_loss=2.5813 | lr=1.00e-03 | Top1=0.2584 | Top2=0.4149 | Top4=0.6327 | Top8=0.8484 | Top16=0.9649 | Top32=0.9978

Byte 05 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 28/80 | train_loss=2.3967 | val_loss=2.3799 | lr=1.00e-03 | Top1=0.3098 | Top2=0.4909 | Top4=0.6980 | Top8=0.8880 | Top16=0.9827 | Top32=0.9989

Byte 05 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 29/80 | train_loss=2.3327 | val_loss=2.3152 | lr=1.00e-03 | Top1=0.3276 | Top2=0.5107 | Top4=0.7182 | Top8=0.9093 | Top16=0.9836 | Top32=0.9989

Byte 05 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 30/80 | train_loss=2.2609 | val_loss=2.2186 | lr=1.00e-03 | Top1=0.3613 | Top2=0.5429 | Top4=0.7518 | Top8=0.9220 | Top16=0.9856 | Top32=0.9989

Byte 05 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 31/80 | train_loss=2.2399 | val_loss=2.2307 | lr=1.00e-03 | Top1=0.3456 | Top2=0.5262 | Top4=0.7487 | Top8=0.9229 | Top16=0.9891 | Top32=0.9996

Byte 05 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 32/80 | train_loss=2.1670 | val_loss=2.1538 | lr=1.00e-03 | Top1=0.3720 | Top2=0.5738 | Top4=0.7760 | Top8=0.9311 | Top16=0.9898 | Top32=0.9987

Byte 05 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 33/80 | train_loss=2.1015 | val_loss=2.2799 | lr=1.00e-03 | Top1=0.3471 | Top2=0.5291 | Top4=0.7493 | Top8=0.9111 | Top16=0.9842 | Top32=0.9980

Byte 05 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 34/80 | train_loss=2.0460 | val_loss=2.1422 | lr=1.00e-03 | Top1=0.3756 | Top2=0.5760 | Top4=0.7862 | Top8=0.9322 | Top16=0.9896 | Top32=0.9991

Byte 05 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 35/80 | train_loss=1.9871 | val_loss=2.1056 | lr=1.00e-03 | Top1=0.3856 | Top2=0.5820 | Top4=0.8049 | Top8=0.9387 | Top16=0.9896 | Top32=0.9984

Byte 05 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 36/80 | train_loss=1.9312 | val_loss=2.0222 | lr=1.00e-03 | Top1=0.4160 | Top2=0.6111 | Top4=0.8156 | Top8=0.9444 | Top16=0.9922 | Top32=0.9993

Byte 05 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 37/80 | train_loss=1.8929 | val_loss=2.0028 | lr=1.00e-03 | Top1=0.4200 | Top2=0.6178 | Top4=0.8211 | Top8=0.9516 | Top16=0.9951 | Top32=1.0000

Byte 05 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 38/80 | train_loss=1.8450 | val_loss=1.9075 | lr=1.00e-03 | Top1=0.4473 | Top2=0.6549 | Top4=0.8424 | Top8=0.9589 | Top16=0.9953 | Top32=0.9996

Byte 05 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 39/80 | train_loss=1.7958 | val_loss=2.0655 | lr=1.00e-03 | Top1=0.4249 | Top2=0.6204 | Top4=0.8053 | Top8=0.9358 | Top16=0.9916 | Top32=0.9987

Byte 05 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 40/80 | train_loss=1.7526 | val_loss=1.8931 | lr=1.00e-03 | Top1=0.4676 | Top2=0.6607 | Top4=0.8509 | Top8=0.9564 | Top16=0.9913 | Top32=0.9984

Byte 05 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 41/80 | train_loss=1.6880 | val_loss=1.7876 | lr=1.00e-03 | Top1=0.4996 | Top2=0.6967 | Top4=0.8660 | Top8=0.9642 | Top16=0.9949 | Top32=1.0000

Byte 05 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 42/80 | train_loss=1.6745 | val_loss=1.9735 | lr=1.00e-03 | Top1=0.4551 | Top2=0.6469 | Top4=0.8249 | Top8=0.9527 | Top16=0.9936 | Top32=0.9989

Byte 05 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 43/80 | train_loss=1.6307 | val_loss=1.8491 | lr=1.00e-03 | Top1=0.4860 | Top2=0.6869 | Top4=0.8640 | Top8=0.9651 | Top16=0.9944 | Top32=0.9991

Byte 05 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 44/80 | train_loss=1.5809 | val_loss=1.7682 | lr=1.00e-03 | Top1=0.5064 | Top2=0.7051 | Top4=0.8720 | Top8=0.9700 | Top16=0.9962 | Top32=0.9991

Byte 05 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 45/80 | train_loss=1.5296 | val_loss=1.7660 | lr=1.00e-03 | Top1=0.5049 | Top2=0.7102 | Top4=0.8751 | Top8=0.9700 | Top16=0.9940 | Top32=0.9984

Byte 05 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 46/80 | train_loss=1.4875 | val_loss=1.7301 | lr=1.00e-03 | Top1=0.5164 | Top2=0.7136 | Top4=0.8778 | Top8=0.9704 | Top16=0.9951 | Top32=0.9993

Byte 05 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 47/80 | train_loss=1.4560 | val_loss=1.7338 | lr=1.00e-03 | Top1=0.5207 | Top2=0.7193 | Top4=0.8802 | Top8=0.9711 | Top16=0.9942 | Top32=0.9982

Byte 05 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 48/80 | train_loss=1.4228 | val_loss=1.6796 | lr=1.00e-03 | Top1=0.5380 | Top2=0.7333 | Top4=0.8902 | Top8=0.9758 | Top16=0.9960 | Top32=0.9998

Byte 05 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 49/80 | train_loss=1.3881 | val_loss=1.8395 | lr=1.00e-03 | Top1=0.5182 | Top2=0.6996 | Top4=0.8716 | Top8=0.9591 | Top16=0.9904 | Top32=0.9964

Byte 05 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 50/80 | train_loss=1.3641 | val_loss=1.7175 | lr=1.00e-03 | Top1=0.5409 | Top2=0.7309 | Top4=0.8878 | Top8=0.9709 | Top16=0.9947 | Top32=0.9980

Byte 05 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 51/80 | train_loss=1.3121 | val_loss=1.6596 | lr=1.00e-03 | Top1=0.5642 | Top2=0.7473 | Top4=0.8978 | Top8=0.9724 | Top16=0.9969 | Top32=0.9991

Byte 05 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 52/80 | train_loss=1.2883 | val_loss=1.7702 | lr=1.00e-03 | Top1=0.5351 | Top2=0.7180 | Top4=0.8713 | Top8=0.9651 | Top16=0.9944 | Top32=0.9996

Byte 05 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 53/80 | train_loss=1.2556 | val_loss=1.7785 | lr=1.00e-03 | Top1=0.5309 | Top2=0.7169 | Top4=0.8760 | Top8=0.9644 | Top16=0.9940 | Top32=0.9980

Byte 05 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 54/80 | train_loss=1.2250 | val_loss=1.6874 | lr=1.00e-03 | Top1=0.5589 | Top2=0.7529 | Top4=0.9047 | Top8=0.9698 | Top16=0.9931 | Top32=0.9976

Byte 05 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 55/80 | train_loss=1.1925 | val_loss=1.7918 | lr=1.00e-03 | Top1=0.5462 | Top2=0.7322 | Top4=0.8856 | Top8=0.9653 | Top16=0.9893 | Top32=0.9936

Byte 05 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 56/80 | train_loss=1.1644 | val_loss=1.6145 | lr=1.00e-03 | Top1=0.5927 | Top2=0.7682 | Top4=0.9036 | Top8=0.9722 | Top16=0.9922 | Top32=0.9960

Byte 05 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 57/80 | train_loss=1.1294 | val_loss=1.6626 | lr=1.00e-03 | Top1=0.5822 | Top2=0.7576 | Top4=0.9033 | Top8=0.9722 | Top16=0.9924 | Top32=0.9967

Byte 05 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 58/80 | train_loss=1.1094 | val_loss=1.6059 | lr=1.00e-03 | Top1=0.5824 | Top2=0.7736 | Top4=0.9113 | Top8=0.9793 | Top16=0.9947 | Top32=0.9980

Byte 05 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 59/80 | train_loss=1.0820 | val_loss=1.6339 | lr=1.00e-03 | Top1=0.5811 | Top2=0.7640 | Top4=0.9091 | Top8=0.9753 | Top16=0.9951 | Top32=0.9980

Byte 05 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 60/80 | train_loss=1.0574 | val_loss=1.8397 | lr=1.00e-03 | Top1=0.5564 | Top2=0.7351 | Top4=0.8811 | Top8=0.9573 | Top16=0.9844 | Top32=0.9924

Byte 05 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 61/80 | train_loss=1.0380 | val_loss=1.4547 | lr=1.00e-03 | Top1=0.6296 | Top2=0.8031 | Top4=0.9336 | Top8=0.9873 | Top16=0.9987 | Top32=0.9993

Byte 05 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 62/80 | train_loss=1.0097 | val_loss=1.6423 | lr=1.00e-03 | Top1=0.5967 | Top2=0.7771 | Top4=0.9053 | Top8=0.9760 | Top16=0.9904 | Top32=0.9956

Byte 05 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 63/80 | train_loss=0.9921 | val_loss=1.6737 | lr=1.00e-03 | Top1=0.5909 | Top2=0.7636 | Top4=0.8991 | Top8=0.9680 | Top16=0.9891 | Top32=0.9940

Byte 05 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 64/80 | train_loss=0.9530 | val_loss=1.5571 | lr=1.00e-03 | Top1=0.6122 | Top2=0.7940 | Top4=0.9187 | Top8=0.9800 | Top16=0.9947 | Top32=0.9982

Byte 05 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 65/80 | train_loss=0.9512 | val_loss=1.5956 | lr=1.00e-03 | Top1=0.6140 | Top2=0.7898 | Top4=0.9209 | Top8=0.9764 | Top16=0.9922 | Top32=0.9951

Byte 05 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 66/80 | train_loss=0.9186 | val_loss=1.3502 | lr=1.00e-03 | Top1=0.6731 | Top2=0.8322 | Top4=0.9442 | Top8=0.9876 | Top16=0.9980 | Top32=0.9989

Byte 05 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 67/80 | train_loss=0.8964 | val_loss=1.4609 | lr=1.00e-03 | Top1=0.6516 | Top2=0.8151 | Top4=0.9271 | Top8=0.9829 | Top16=0.9949 | Top32=0.9978

Byte 05 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 68/80 | train_loss=0.8863 | val_loss=1.4182 | lr=1.00e-03 | Top1=0.6564 | Top2=0.8280 | Top4=0.9407 | Top8=0.9849 | Top16=0.9958 | Top32=0.9978

Byte 05 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 69/80 | train_loss=0.8682 | val_loss=1.4116 | lr=1.00e-03 | Top1=0.6631 | Top2=0.8253 | Top4=0.9367 | Top8=0.9862 | Top16=0.9969 | Top32=0.9980

Byte 05 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 70/80 | train_loss=0.8486 | val_loss=1.3825 | lr=1.00e-03 | Top1=0.6609 | Top2=0.8327 | Top4=0.9438 | Top8=0.9893 | Top16=0.9978 | Top32=0.9993

Byte 05 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 71/80 | train_loss=0.8324 | val_loss=1.3726 | lr=1.00e-03 | Top1=0.6656 | Top2=0.8367 | Top4=0.9447 | Top8=0.9902 | Top16=0.9978 | Top32=0.9989

Byte 05 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 72/80 | train_loss=0.8167 | val_loss=1.3851 | lr=1.00e-03 | Top1=0.6667 | Top2=0.8360 | Top4=0.9376 | Top8=0.9862 | Top16=0.9971 | Top32=0.9996

Byte 05 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 73/80 | train_loss=0.7997 | val_loss=1.7955 | lr=1.00e-03 | Top1=0.5844 | Top2=0.7549 | Top4=0.8913 | Top8=0.9618 | Top16=0.9809 | Top32=0.9882

Byte 05 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 74/80 | train_loss=0.7764 | val_loss=1.4385 | lr=1.00e-03 | Top1=0.6478 | Top2=0.8278 | Top4=0.9382 | Top8=0.9820 | Top16=0.9951 | Top32=0.9982

Byte 05 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 75/80 | train_loss=0.7749 | val_loss=1.5971 | lr=1.00e-03 | Top1=0.6233 | Top2=0.8013 | Top4=0.9200 | Top8=0.9769 | Top16=0.9889 | Top32=0.9940

Byte 05 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 76/80 | train_loss=0.7581 | val_loss=1.4717 | lr=1.00e-03 | Top1=0.6542 | Top2=0.8207 | Top4=0.9316 | Top8=0.9787 | Top16=0.9909 | Top32=0.9958

Byte 05 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 77/80 | train_loss=0.7538 | val_loss=1.4840 | lr=1.00e-03 | Top1=0.6576 | Top2=0.8233 | Top4=0.9289 | Top8=0.9771 | Top16=0.9922 | Top32=0.9953

Byte 05 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 78/80 | train_loss=0.6477 | val_loss=1.1934 | lr=5.00e-04 | Top1=0.7296 | Top2=0.8767 | Top4=0.9604 | Top8=0.9936 | Top16=0.9982 | Top32=0.9993

Byte 05 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 79/80 | train_loss=0.6160 | val_loss=1.3218 | lr=5.00e-04 | Top1=0.6951 | Top2=0.8571 | Top4=0.9496 | Top8=0.9862 | Top16=0.9931 | Top32=0.9953

Byte 05 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 05 | Epoch 80/80 | train_loss=0.6057 | val_loss=1.3617 | lr=5.00e-04 | Top1=0.6907 | Top2=0.8471 | Top4=0.9491 | Top8=0.9858 | Top16=0.9940 | Top32=0.9971

Finished ASCON byte 05
Best epoch: 78
Test Top-k: {'top1': 0.7386666536331177, 'top2': 0.8840000033378601, 'top4': 0.9657777547836304, 'top8': 0.9926666617393494, 'top16': 0.9973333477973938, 'top32': 0.9982222318649292}
Grouped Top4: {'grouped_n1_top4': 0.9657777547836304, 'grouped_n2_top4': 0.9940666556358337, 'grouped_n4_top4': 0.9990290999412537, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.06
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_05\byte_05_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_05\byte_05_summary.csv

Loading ASCON byte 06
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_06
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 06 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 01/80 | train_loss=5.4163 | val_loss=5.2339 | lr=1.00e-03 | Top1=0.0104 | Top2=0.0222 | Top4=0.0447 | Top8=0.0749 | Top16=0.1436 | Top32=0.2671

Byte 06 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 02/80 | train_loss=4.8450 | val_loss=4.5314 | lr=1.00e-03 | Top1=0.0253 | Top2=0.0480 | Top4=0.0960 | Top8=0.1878 | Top16=0.3480 | Top32=0.5833

Byte 06 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 03/80 | train_loss=4.2256 | val_loss=4.0792 | lr=1.00e-03 | Top1=0.0304 | Top2=0.0618 | Top4=0.1204 | Top8=0.2438 | Top16=0.4162 | Top32=0.7062

Byte 06 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 04/80 | train_loss=4.0455 | val_loss=4.0515 | lr=1.00e-03 | Top1=0.0360 | Top2=0.0724 | Top4=0.1431 | Top8=0.2731 | Top16=0.4747 | Top32=0.7807

Byte 06 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 05/80 | train_loss=3.9649 | val_loss=3.8584 | lr=1.00e-03 | Top1=0.0504 | Top2=0.0889 | Top4=0.1687 | Top8=0.3149 | Top16=0.5320 | Top32=0.8180

Byte 06 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 06/80 | train_loss=3.8846 | val_loss=3.8187 | lr=1.00e-03 | Top1=0.0571 | Top2=0.0993 | Top4=0.1849 | Top8=0.3373 | Top16=0.5553 | Top32=0.8440

Byte 06 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 07/80 | train_loss=3.8304 | val_loss=3.7658 | lr=1.00e-03 | Top1=0.0518 | Top2=0.1036 | Top4=0.1916 | Top8=0.3607 | Top16=0.5853 | Top32=0.8678

Byte 06 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 08/80 | train_loss=3.7979 | val_loss=3.7933 | lr=1.00e-03 | Top1=0.0573 | Top2=0.1049 | Top4=0.1893 | Top8=0.3516 | Top16=0.5616 | Top32=0.8336

Byte 06 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 09/80 | train_loss=3.7650 | val_loss=3.7179 | lr=1.00e-03 | Top1=0.0613 | Top2=0.1151 | Top4=0.2093 | Top8=0.3691 | Top16=0.5902 | Top32=0.8689

Byte 06 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 10/80 | train_loss=3.7223 | val_loss=3.7152 | lr=1.00e-03 | Top1=0.0567 | Top2=0.1080 | Top4=0.1993 | Top8=0.3733 | Top16=0.6011 | Top32=0.8664

Byte 06 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 11/80 | train_loss=3.7064 | val_loss=3.6489 | lr=1.00e-03 | Top1=0.0647 | Top2=0.1173 | Top4=0.2216 | Top8=0.3958 | Top16=0.6304 | Top32=0.8976

Byte 06 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 12/80 | train_loss=3.6563 | val_loss=3.6628 | lr=1.00e-03 | Top1=0.0613 | Top2=0.1087 | Top4=0.2027 | Top8=0.3791 | Top16=0.6211 | Top32=0.8989

Byte 06 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 13/80 | train_loss=3.6405 | val_loss=3.5910 | lr=1.00e-03 | Top1=0.0716 | Top2=0.1287 | Top4=0.2402 | Top8=0.4200 | Top16=0.6533 | Top32=0.9060

Byte 06 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 14/80 | train_loss=3.6297 | val_loss=3.6789 | lr=1.00e-03 | Top1=0.0573 | Top2=0.1136 | Top4=0.2093 | Top8=0.3913 | Top16=0.6324 | Top32=0.9016

Byte 06 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 15/80 | train_loss=3.5964 | val_loss=3.6604 | lr=1.00e-03 | Top1=0.0680 | Top2=0.1233 | Top4=0.2324 | Top8=0.4138 | Top16=0.6329 | Top32=0.8767

Byte 06 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 16/80 | train_loss=3.5727 | val_loss=3.6089 | lr=1.00e-03 | Top1=0.0722 | Top2=0.1260 | Top4=0.2273 | Top8=0.4171 | Top16=0.6507 | Top32=0.9013

Byte 06 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 17/80 | train_loss=3.5589 | val_loss=3.6885 | lr=1.00e-03 | Top1=0.0633 | Top2=0.1180 | Top4=0.2147 | Top8=0.3984 | Top16=0.6304 | Top32=0.9133

Byte 06 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 18/80 | train_loss=3.5284 | val_loss=3.5875 | lr=1.00e-03 | Top1=0.0842 | Top2=0.1478 | Top4=0.2536 | Top8=0.4382 | Top16=0.6698 | Top32=0.9040

Byte 06 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 19/80 | train_loss=3.5077 | val_loss=3.4884 | lr=1.00e-03 | Top1=0.0909 | Top2=0.1567 | Top4=0.2744 | Top8=0.4649 | Top16=0.7124 | Top32=0.9362

Byte 06 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 20/80 | train_loss=3.4791 | val_loss=3.5075 | lr=1.00e-03 | Top1=0.0893 | Top2=0.1576 | Top4=0.2780 | Top8=0.4649 | Top16=0.6984 | Top32=0.9164

Byte 06 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 21/80 | train_loss=3.4372 | val_loss=3.4380 | lr=1.00e-03 | Top1=0.0976 | Top2=0.1711 | Top4=0.3047 | Top8=0.5129 | Top16=0.7504 | Top32=0.9447

Byte 06 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 22/80 | train_loss=3.4223 | val_loss=3.4202 | lr=1.00e-03 | Top1=0.0951 | Top2=0.1736 | Top4=0.2993 | Top8=0.5067 | Top16=0.7533 | Top32=0.9524

Byte 06 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 23/80 | train_loss=3.3820 | val_loss=3.3903 | lr=1.00e-03 | Top1=0.1031 | Top2=0.1827 | Top4=0.3178 | Top8=0.5364 | Top16=0.7656 | Top32=0.9482

Byte 06 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 24/80 | train_loss=3.3447 | val_loss=3.3322 | lr=1.00e-03 | Top1=0.1142 | Top2=0.2018 | Top4=0.3398 | Top8=0.5596 | Top16=0.7896 | Top32=0.9642

Byte 06 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 25/80 | train_loss=3.2982 | val_loss=3.2871 | lr=1.00e-03 | Top1=0.1224 | Top2=0.2233 | Top4=0.3618 | Top8=0.5880 | Top16=0.8058 | Top32=0.9582

Byte 06 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 26/80 | train_loss=3.2288 | val_loss=3.2937 | lr=1.00e-03 | Top1=0.1149 | Top2=0.2107 | Top4=0.3604 | Top8=0.5907 | Top16=0.8022 | Top32=0.9556

Byte 06 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 27/80 | train_loss=3.1590 | val_loss=3.3741 | lr=1.00e-03 | Top1=0.1233 | Top2=0.2058 | Top4=0.3447 | Top8=0.5598 | Top16=0.7969 | Top32=0.9680

Byte 06 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 28/80 | train_loss=3.1101 | val_loss=3.0999 | lr=1.00e-03 | Top1=0.1629 | Top2=0.2720 | Top4=0.4362 | Top8=0.6656 | Top16=0.8622 | Top32=0.9798

Byte 06 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 29/80 | train_loss=3.0492 | val_loss=3.1146 | lr=1.00e-03 | Top1=0.1580 | Top2=0.2767 | Top4=0.4458 | Top8=0.6656 | Top16=0.8604 | Top32=0.9811

Byte 06 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 30/80 | train_loss=2.9803 | val_loss=3.0013 | lr=1.00e-03 | Top1=0.1836 | Top2=0.3071 | Top4=0.4856 | Top8=0.7027 | Top16=0.8882 | Top32=0.9867

Byte 06 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 31/80 | train_loss=2.9134 | val_loss=2.9272 | lr=1.00e-03 | Top1=0.2011 | Top2=0.3276 | Top4=0.5087 | Top8=0.7327 | Top16=0.9062 | Top32=0.9880

Byte 06 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 32/80 | train_loss=2.8581 | val_loss=2.9743 | lr=1.00e-03 | Top1=0.1920 | Top2=0.3187 | Top4=0.5007 | Top8=0.7202 | Top16=0.8911 | Top32=0.9807

Byte 06 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 33/80 | train_loss=2.7992 | val_loss=2.9896 | lr=1.00e-03 | Top1=0.2044 | Top2=0.3231 | Top4=0.5036 | Top8=0.7102 | Top16=0.8809 | Top32=0.9764

Byte 06 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 34/80 | train_loss=2.7290 | val_loss=2.8094 | lr=1.00e-03 | Top1=0.2333 | Top2=0.3802 | Top4=0.5680 | Top8=0.7669 | Top16=0.9182 | Top32=0.9864

Byte 06 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 35/80 | train_loss=2.6824 | val_loss=2.7114 | lr=1.00e-03 | Top1=0.2573 | Top2=0.4102 | Top4=0.5942 | Top8=0.7936 | Top16=0.9320 | Top32=0.9920

Byte 06 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 36/80 | train_loss=2.6035 | val_loss=2.8393 | lr=1.00e-03 | Top1=0.2256 | Top2=0.3696 | Top4=0.5536 | Top8=0.7591 | Top16=0.9116 | Top32=0.9891

Byte 06 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 37/80 | train_loss=2.5504 | val_loss=2.7789 | lr=1.00e-03 | Top1=0.2616 | Top2=0.4129 | Top4=0.5933 | Top8=0.7798 | Top16=0.9107 | Top32=0.9833

Byte 06 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 38/80 | train_loss=2.4897 | val_loss=2.5383 | lr=1.00e-03 | Top1=0.2980 | Top2=0.4691 | Top4=0.6649 | Top8=0.8307 | Top16=0.9513 | Top32=0.9944

Byte 06 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 39/80 | train_loss=2.4282 | val_loss=2.5505 | lr=1.00e-03 | Top1=0.3002 | Top2=0.4711 | Top4=0.6549 | Top8=0.8347 | Top16=0.9491 | Top32=0.9940

Byte 06 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 40/80 | train_loss=2.3802 | val_loss=2.5653 | lr=1.00e-03 | Top1=0.2936 | Top2=0.4604 | Top4=0.6580 | Top8=0.8364 | Top16=0.9484 | Top32=0.9920

Byte 06 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 41/80 | train_loss=2.3107 | val_loss=2.4092 | lr=1.00e-03 | Top1=0.3453 | Top2=0.5118 | Top4=0.7009 | Top8=0.8651 | Top16=0.9649 | Top32=0.9958

Byte 06 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 42/80 | train_loss=2.2442 | val_loss=2.4516 | lr=1.00e-03 | Top1=0.3269 | Top2=0.5051 | Top4=0.6927 | Top8=0.8653 | Top16=0.9616 | Top32=0.9949

Byte 06 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 43/80 | train_loss=2.1863 | val_loss=2.3564 | lr=1.00e-03 | Top1=0.3618 | Top2=0.5280 | Top4=0.7178 | Top8=0.8749 | Top16=0.9593 | Top32=0.9971

Byte 06 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 44/80 | train_loss=2.1491 | val_loss=2.3104 | lr=1.00e-03 | Top1=0.3764 | Top2=0.5440 | Top4=0.7336 | Top8=0.8831 | Top16=0.9678 | Top32=0.9960

Byte 06 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 45/80 | train_loss=2.0909 | val_loss=2.2166 | lr=1.00e-03 | Top1=0.3911 | Top2=0.5727 | Top4=0.7638 | Top8=0.8951 | Top16=0.9760 | Top32=0.9982

Byte 06 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 46/80 | train_loss=2.0205 | val_loss=2.2534 | lr=1.00e-03 | Top1=0.3884 | Top2=0.5624 | Top4=0.7513 | Top8=0.8976 | Top16=0.9764 | Top32=0.9964

Byte 06 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 47/80 | train_loss=1.9695 | val_loss=2.1252 | lr=1.00e-03 | Top1=0.4173 | Top2=0.6071 | Top4=0.7813 | Top8=0.9140 | Top16=0.9818 | Top32=0.9976

Byte 06 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 48/80 | train_loss=1.9234 | val_loss=2.1211 | lr=1.00e-03 | Top1=0.4247 | Top2=0.6031 | Top4=0.7764 | Top8=0.9178 | Top16=0.9782 | Top32=0.9973

Byte 06 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 49/80 | train_loss=1.8694 | val_loss=2.1143 | lr=1.00e-03 | Top1=0.4342 | Top2=0.6127 | Top4=0.7862 | Top8=0.9104 | Top16=0.9789 | Top32=0.9960

Byte 06 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 50/80 | train_loss=1.8108 | val_loss=2.0220 | lr=1.00e-03 | Top1=0.4458 | Top2=0.6296 | Top4=0.8087 | Top8=0.9273 | Top16=0.9840 | Top32=0.9984

Byte 06 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 51/80 | train_loss=1.7662 | val_loss=2.1345 | lr=1.00e-03 | Top1=0.4324 | Top2=0.6209 | Top4=0.7849 | Top8=0.9111 | Top16=0.9751 | Top32=0.9973

Byte 06 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 52/80 | train_loss=1.7254 | val_loss=2.1031 | lr=1.00e-03 | Top1=0.4400 | Top2=0.6140 | Top4=0.7960 | Top8=0.9182 | Top16=0.9811 | Top32=0.9973

Byte 06 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 53/80 | train_loss=1.6793 | val_loss=2.0081 | lr=1.00e-03 | Top1=0.4624 | Top2=0.6484 | Top4=0.8147 | Top8=0.9273 | Top16=0.9813 | Top32=0.9969

Byte 06 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 54/80 | train_loss=1.6366 | val_loss=1.9632 | lr=1.00e-03 | Top1=0.4784 | Top2=0.6613 | Top4=0.8218 | Top8=0.9280 | Top16=0.9864 | Top32=0.9976

Byte 06 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 55/80 | train_loss=1.6018 | val_loss=1.9607 | lr=1.00e-03 | Top1=0.4778 | Top2=0.6569 | Top4=0.8242 | Top8=0.9298 | Top16=0.9860 | Top32=0.9984

Byte 06 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 56/80 | train_loss=1.5676 | val_loss=1.8744 | lr=1.00e-03 | Top1=0.5133 | Top2=0.6851 | Top4=0.8398 | Top8=0.9433 | Top16=0.9867 | Top32=0.9976

Byte 06 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 57/80 | train_loss=1.5198 | val_loss=1.8558 | lr=1.00e-03 | Top1=0.5153 | Top2=0.6871 | Top4=0.8491 | Top8=0.9440 | Top16=0.9853 | Top32=0.9980

Byte 06 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 58/80 | train_loss=1.4791 | val_loss=1.8515 | lr=1.00e-03 | Top1=0.5151 | Top2=0.6909 | Top4=0.8467 | Top8=0.9453 | Top16=0.9867 | Top32=0.9976

Byte 06 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 59/80 | train_loss=1.4383 | val_loss=1.8140 | lr=1.00e-03 | Top1=0.5162 | Top2=0.7011 | Top4=0.8589 | Top8=0.9553 | Top16=0.9898 | Top32=0.9982

Byte 06 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 60/80 | train_loss=1.3881 | val_loss=1.7995 | lr=1.00e-03 | Top1=0.5384 | Top2=0.7171 | Top4=0.8584 | Top8=0.9509 | Top16=0.9891 | Top32=0.9987

Byte 06 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 61/80 | train_loss=1.3679 | val_loss=1.8771 | lr=1.00e-03 | Top1=0.5173 | Top2=0.6938 | Top4=0.8411 | Top8=0.9440 | Top16=0.9862 | Top32=0.9976

Byte 06 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 62/80 | train_loss=1.3334 | val_loss=1.8485 | lr=1.00e-03 | Top1=0.5247 | Top2=0.7013 | Top4=0.8556 | Top8=0.9442 | Top16=0.9856 | Top32=0.9969

Byte 06 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 63/80 | train_loss=1.3057 | val_loss=1.8085 | lr=1.00e-03 | Top1=0.5382 | Top2=0.7089 | Top4=0.8624 | Top8=0.9516 | Top16=0.9853 | Top32=0.9958

Byte 06 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 64/80 | train_loss=1.2797 | val_loss=1.8987 | lr=1.00e-03 | Top1=0.5182 | Top2=0.6960 | Top4=0.8511 | Top8=0.9438 | Top16=0.9867 | Top32=0.9967

Byte 06 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 65/80 | train_loss=1.2299 | val_loss=1.7883 | lr=1.00e-03 | Top1=0.5391 | Top2=0.7238 | Top4=0.8733 | Top8=0.9587 | Top16=0.9902 | Top32=0.9978

Byte 06 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 66/80 | train_loss=1.2245 | val_loss=1.7050 | lr=1.00e-03 | Top1=0.5727 | Top2=0.7509 | Top4=0.8824 | Top8=0.9616 | Top16=0.9896 | Top32=0.9969

Byte 06 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 67/80 | train_loss=1.2056 | val_loss=1.8960 | lr=1.00e-03 | Top1=0.5171 | Top2=0.7084 | Top4=0.8511 | Top8=0.9433 | Top16=0.9851 | Top32=0.9942

Byte 06 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 68/80 | train_loss=1.1666 | val_loss=1.6557 | lr=1.00e-03 | Top1=0.5936 | Top2=0.7558 | Top4=0.8884 | Top8=0.9622 | Top16=0.9909 | Top32=0.9973

Byte 06 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 69/80 | train_loss=1.1517 | val_loss=1.8117 | lr=1.00e-03 | Top1=0.5538 | Top2=0.7280 | Top4=0.8698 | Top8=0.9504 | Top16=0.9842 | Top32=0.9918

Byte 06 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 70/80 | train_loss=1.1439 | val_loss=1.8443 | lr=1.00e-03 | Top1=0.5451 | Top2=0.7260 | Top4=0.8698 | Top8=0.9544 | Top16=0.9887 | Top32=0.9956

Byte 06 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 71/80 | train_loss=1.1005 | val_loss=1.8301 | lr=1.00e-03 | Top1=0.5558 | Top2=0.7227 | Top4=0.8660 | Top8=0.9496 | Top16=0.9860 | Top32=0.9944

Byte 06 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 72/80 | train_loss=1.0624 | val_loss=1.7615 | lr=1.00e-03 | Top1=0.5800 | Top2=0.7464 | Top4=0.8753 | Top8=0.9547 | Top16=0.9847 | Top32=0.9942

Byte 06 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 73/80 | train_loss=1.0572 | val_loss=1.8022 | lr=1.00e-03 | Top1=0.5613 | Top2=0.7278 | Top4=0.8649 | Top8=0.9520 | Top16=0.9869 | Top32=0.9940

Byte 06 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 74/80 | train_loss=1.0283 | val_loss=1.7465 | lr=1.00e-03 | Top1=0.5776 | Top2=0.7482 | Top4=0.8822 | Top8=0.9553 | Top16=0.9891 | Top32=0.9956

Byte 06 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 75/80 | train_loss=0.8857 | val_loss=1.4833 | lr=5.00e-04 | Top1=0.6318 | Top2=0.7989 | Top4=0.9171 | Top8=0.9760 | Top16=0.9956 | Top32=0.9978

Byte 06 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 76/80 | train_loss=0.8414 | val_loss=1.5824 | lr=5.00e-04 | Top1=0.6202 | Top2=0.7791 | Top4=0.9047 | Top8=0.9702 | Top16=0.9927 | Top32=0.9962

Byte 06 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 77/80 | train_loss=0.8203 | val_loss=1.5734 | lr=5.00e-04 | Top1=0.6353 | Top2=0.7911 | Top4=0.9078 | Top8=0.9702 | Top16=0.9902 | Top32=0.9951

Byte 06 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 78/80 | train_loss=0.8085 | val_loss=1.5374 | lr=5.00e-04 | Top1=0.6389 | Top2=0.7956 | Top4=0.9069 | Top8=0.9707 | Top16=0.9902 | Top32=0.9953

Byte 06 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 79/80 | train_loss=0.7950 | val_loss=1.5237 | lr=5.00e-04 | Top1=0.6371 | Top2=0.7967 | Top4=0.9091 | Top8=0.9740 | Top16=0.9913 | Top32=0.9964

Byte 06 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 06 | Epoch 80/80 | train_loss=0.7728 | val_loss=1.5850 | lr=5.00e-04 | Top1=0.6209 | Top2=0.7904 | Top4=0.9098 | Top8=0.9720 | Top16=0.9904 | Top32=0.9949

Finished ASCON byte 06
Best epoch: 75
Test Top-k: {'top1': 0.6195555329322815, 'top2': 0.7937777638435364, 'top4': 0.9108889102935791, 'top8': 0.9704444408416748, 'top16': 0.992888867855072, 'top32': 0.9984444379806519}
Grouped Top4: {'grouped_n1_top4': 0.9108889102935791, 'grouped_n2_top4': 0.9835089445114136, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.02
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_06\byte_06_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_06\byte_06_summary.csv

Loading ASCON byte 07
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_07
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 07 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 01/80 | train_loss=5.4494 | val_loss=5.2438 | lr=1.00e-03 | Top1=0.0122 | Top2=0.0220 | Top4=0.0411 | Top8=0.0740 | Top16=0.1411 | Top32=0.2707

Byte 07 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 02/80 | train_loss=4.8970 | val_loss=4.6774 | lr=1.00e-03 | Top1=0.0236 | Top2=0.0449 | Top4=0.0798 | Top8=0.1560 | Top16=0.2920 | Top32=0.5396

Byte 07 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 03/80 | train_loss=4.2434 | val_loss=4.0941 | lr=1.00e-03 | Top1=0.0424 | Top2=0.0753 | Top4=0.1384 | Top8=0.2578 | Top16=0.4222 | Top32=0.7087

Byte 07 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 04/80 | train_loss=4.0467 | val_loss=3.9921 | lr=1.00e-03 | Top1=0.0458 | Top2=0.0880 | Top4=0.1573 | Top8=0.2869 | Top16=0.4800 | Top32=0.7393

Byte 07 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 05/80 | train_loss=3.9556 | val_loss=3.8720 | lr=1.00e-03 | Top1=0.0502 | Top2=0.0936 | Top4=0.1709 | Top8=0.3211 | Top16=0.5271 | Top32=0.7978

Byte 07 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 06/80 | train_loss=3.8584 | val_loss=3.7762 | lr=1.00e-03 | Top1=0.0562 | Top2=0.1018 | Top4=0.1949 | Top8=0.3569 | Top16=0.5656 | Top32=0.8349

Byte 07 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 07/80 | train_loss=3.8112 | val_loss=3.7323 | lr=1.00e-03 | Top1=0.0591 | Top2=0.1127 | Top4=0.1998 | Top8=0.3669 | Top16=0.6198 | Top32=0.8880

Byte 07 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 08/80 | train_loss=3.7533 | val_loss=3.7689 | lr=1.00e-03 | Top1=0.0504 | Top2=0.1044 | Top4=0.1920 | Top8=0.3547 | Top16=0.5802 | Top32=0.8638

Byte 07 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 09/80 | train_loss=3.6838 | val_loss=3.9141 | lr=1.00e-03 | Top1=0.0513 | Top2=0.0973 | Top4=0.1802 | Top8=0.3260 | Top16=0.5262 | Top32=0.8098

Byte 07 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 10/80 | train_loss=3.6461 | val_loss=3.5542 | lr=1.00e-03 | Top1=0.0802 | Top2=0.1380 | Top4=0.2504 | Top8=0.4487 | Top16=0.6813 | Top32=0.9031

Byte 07 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 11/80 | train_loss=3.5795 | val_loss=3.6445 | lr=1.00e-03 | Top1=0.0687 | Top2=0.1224 | Top4=0.2373 | Top8=0.4224 | Top16=0.6640 | Top32=0.9047

Byte 07 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 12/80 | train_loss=3.5301 | val_loss=3.4216 | lr=1.00e-03 | Top1=0.0944 | Top2=0.1713 | Top4=0.3118 | Top8=0.5144 | Top16=0.7491 | Top32=0.9387

Byte 07 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 13/80 | train_loss=3.4666 | val_loss=3.4260 | lr=1.00e-03 | Top1=0.1013 | Top2=0.1838 | Top4=0.3140 | Top8=0.5171 | Top16=0.7304 | Top32=0.9291

Byte 07 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 14/80 | train_loss=3.3996 | val_loss=3.2785 | lr=1.00e-03 | Top1=0.1227 | Top2=0.2211 | Top4=0.3651 | Top8=0.5811 | Top16=0.8069 | Top32=0.9602

Byte 07 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 15/80 | train_loss=3.3434 | val_loss=3.2417 | lr=1.00e-03 | Top1=0.1396 | Top2=0.2444 | Top4=0.3927 | Top8=0.6002 | Top16=0.8078 | Top32=0.9484

Byte 07 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 16/80 | train_loss=3.2630 | val_loss=3.2092 | lr=1.00e-03 | Top1=0.1398 | Top2=0.2478 | Top4=0.4122 | Top8=0.6207 | Top16=0.8196 | Top32=0.9542

Byte 07 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 17/80 | train_loss=3.1872 | val_loss=3.0969 | lr=1.00e-03 | Top1=0.1633 | Top2=0.2824 | Top4=0.4560 | Top8=0.6616 | Top16=0.8549 | Top32=0.9691

Byte 07 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 18/80 | train_loss=3.0931 | val_loss=3.1393 | lr=1.00e-03 | Top1=0.1656 | Top2=0.2838 | Top4=0.4540 | Top8=0.6478 | Top16=0.8447 | Top32=0.9656

Byte 07 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 19/80 | train_loss=3.0296 | val_loss=2.9040 | lr=1.00e-03 | Top1=0.2007 | Top2=0.3327 | Top4=0.5284 | Top8=0.7391 | Top16=0.9018 | Top32=0.9820

Byte 07 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 20/80 | train_loss=2.9323 | val_loss=2.8404 | lr=1.00e-03 | Top1=0.2113 | Top2=0.3578 | Top4=0.5427 | Top8=0.7567 | Top16=0.9131 | Top32=0.9880

Byte 07 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 21/80 | train_loss=2.8577 | val_loss=2.8364 | lr=1.00e-03 | Top1=0.2022 | Top2=0.3533 | Top4=0.5462 | Top8=0.7604 | Top16=0.9158 | Top32=0.9867

Byte 07 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 22/80 | train_loss=2.7715 | val_loss=2.6737 | lr=1.00e-03 | Top1=0.2487 | Top2=0.4104 | Top4=0.6116 | Top8=0.8100 | Top16=0.9373 | Top32=0.9916

Byte 07 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 23/80 | train_loss=2.7089 | val_loss=2.5595 | lr=1.00e-03 | Top1=0.2920 | Top2=0.4478 | Top4=0.6373 | Top8=0.8396 | Top16=0.9531 | Top32=0.9944

Byte 07 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 24/80 | train_loss=2.6163 | val_loss=2.4351 | lr=1.00e-03 | Top1=0.3113 | Top2=0.4913 | Top4=0.7053 | Top8=0.8751 | Top16=0.9656 | Top32=0.9949

Byte 07 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 25/80 | train_loss=2.5491 | val_loss=2.4877 | lr=1.00e-03 | Top1=0.2982 | Top2=0.4722 | Top4=0.6796 | Top8=0.8560 | Top16=0.9576 | Top32=0.9929

Byte 07 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 26/80 | train_loss=2.4529 | val_loss=2.3313 | lr=1.00e-03 | Top1=0.3329 | Top2=0.5256 | Top4=0.7333 | Top8=0.8887 | Top16=0.9731 | Top32=0.9969

Byte 07 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 27/80 | train_loss=2.3802 | val_loss=2.3504 | lr=1.00e-03 | Top1=0.3400 | Top2=0.5289 | Top4=0.7293 | Top8=0.8791 | Top16=0.9673 | Top32=0.9956

Byte 07 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 28/80 | train_loss=2.3029 | val_loss=2.2768 | lr=1.00e-03 | Top1=0.3620 | Top2=0.5480 | Top4=0.7480 | Top8=0.8953 | Top16=0.9758 | Top32=0.9956

Byte 07 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 29/80 | train_loss=2.2269 | val_loss=2.1515 | lr=1.00e-03 | Top1=0.3889 | Top2=0.5860 | Top4=0.7807 | Top8=0.9198 | Top16=0.9796 | Top32=0.9967

Byte 07 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 30/80 | train_loss=2.1621 | val_loss=2.1867 | lr=1.00e-03 | Top1=0.3791 | Top2=0.5742 | Top4=0.7680 | Top8=0.9091 | Top16=0.9807 | Top32=0.9964

Byte 07 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 31/80 | train_loss=2.0993 | val_loss=2.1072 | lr=1.00e-03 | Top1=0.4138 | Top2=0.5996 | Top4=0.7860 | Top8=0.9258 | Top16=0.9829 | Top32=0.9962

Byte 07 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 32/80 | train_loss=2.0249 | val_loss=2.1287 | lr=1.00e-03 | Top1=0.4084 | Top2=0.6062 | Top4=0.7936 | Top8=0.9233 | Top16=0.9813 | Top32=0.9967

Byte 07 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 33/80 | train_loss=1.9867 | val_loss=2.1304 | lr=1.00e-03 | Top1=0.4102 | Top2=0.5971 | Top4=0.7818 | Top8=0.9156 | Top16=0.9798 | Top32=0.9962

Byte 07 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 34/80 | train_loss=1.9302 | val_loss=2.0709 | lr=1.00e-03 | Top1=0.4287 | Top2=0.6242 | Top4=0.8044 | Top8=0.9247 | Top16=0.9764 | Top32=0.9947

Byte 07 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 35/80 | train_loss=1.8781 | val_loss=1.8777 | lr=1.00e-03 | Top1=0.4853 | Top2=0.6696 | Top4=0.8456 | Top8=0.9500 | Top16=0.9898 | Top32=0.9989

Byte 07 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 36/80 | train_loss=1.8276 | val_loss=1.8674 | lr=1.00e-03 | Top1=0.4871 | Top2=0.6822 | Top4=0.8473 | Top8=0.9509 | Top16=0.9893 | Top32=0.9980

Byte 07 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 37/80 | train_loss=1.7718 | val_loss=1.7905 | lr=1.00e-03 | Top1=0.5138 | Top2=0.6993 | Top4=0.8618 | Top8=0.9560 | Top16=0.9911 | Top32=0.9989

Byte 07 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 38/80 | train_loss=1.7135 | val_loss=1.7566 | lr=1.00e-03 | Top1=0.5227 | Top2=0.7184 | Top4=0.8744 | Top8=0.9580 | Top16=0.9904 | Top32=0.9973

Byte 07 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 39/80 | train_loss=1.6902 | val_loss=1.7851 | lr=1.00e-03 | Top1=0.5251 | Top2=0.7040 | Top4=0.8680 | Top8=0.9580 | Top16=0.9896 | Top32=0.9978

Byte 07 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 40/80 | train_loss=1.6361 | val_loss=1.8093 | lr=1.00e-03 | Top1=0.5078 | Top2=0.6982 | Top4=0.8629 | Top8=0.9551 | Top16=0.9896 | Top32=0.9982

Byte 07 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 41/80 | train_loss=1.5903 | val_loss=1.7472 | lr=1.00e-03 | Top1=0.5224 | Top2=0.7220 | Top4=0.8771 | Top8=0.9649 | Top16=0.9913 | Top32=0.9984

Byte 07 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 42/80 | train_loss=1.5632 | val_loss=1.7135 | lr=1.00e-03 | Top1=0.5413 | Top2=0.7304 | Top4=0.8798 | Top8=0.9633 | Top16=0.9927 | Top32=0.9980

Byte 07 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 43/80 | train_loss=1.5108 | val_loss=1.7051 | lr=1.00e-03 | Top1=0.5456 | Top2=0.7311 | Top4=0.8833 | Top8=0.9644 | Top16=0.9929 | Top32=0.9982

Byte 07 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 44/80 | train_loss=1.4848 | val_loss=1.6893 | lr=1.00e-03 | Top1=0.5496 | Top2=0.7404 | Top4=0.8873 | Top8=0.9662 | Top16=0.9920 | Top32=0.9978

Byte 07 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 45/80 | train_loss=1.4564 | val_loss=1.7987 | lr=1.00e-03 | Top1=0.5267 | Top2=0.7142 | Top4=0.8684 | Top8=0.9547 | Top16=0.9902 | Top32=0.9973

Byte 07 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 46/80 | train_loss=1.4242 | val_loss=1.5526 | lr=1.00e-03 | Top1=0.5836 | Top2=0.7676 | Top4=0.9087 | Top8=0.9784 | Top16=0.9938 | Top32=0.9978

Byte 07 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 47/80 | train_loss=1.3708 | val_loss=1.6397 | lr=1.00e-03 | Top1=0.5787 | Top2=0.7584 | Top4=0.8938 | Top8=0.9656 | Top16=0.9936 | Top32=0.9980

Byte 07 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 48/80 | train_loss=1.3710 | val_loss=1.7587 | lr=1.00e-03 | Top1=0.5449 | Top2=0.7322 | Top4=0.8798 | Top8=0.9564 | Top16=0.9889 | Top32=0.9953

Byte 07 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 49/80 | train_loss=1.3295 | val_loss=1.7838 | lr=1.00e-03 | Top1=0.5493 | Top2=0.7316 | Top4=0.8844 | Top8=0.9604 | Top16=0.9889 | Top32=0.9960

Byte 07 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 50/80 | train_loss=1.3014 | val_loss=1.5089 | lr=1.00e-03 | Top1=0.6089 | Top2=0.7931 | Top4=0.9176 | Top8=0.9771 | Top16=0.9938 | Top32=0.9976

Byte 07 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 51/80 | train_loss=1.2777 | val_loss=1.5475 | lr=1.00e-03 | Top1=0.6067 | Top2=0.7898 | Top4=0.9180 | Top8=0.9749 | Top16=0.9922 | Top32=0.9980

Byte 07 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 52/80 | train_loss=1.2515 | val_loss=1.5793 | lr=1.00e-03 | Top1=0.5998 | Top2=0.7813 | Top4=0.9116 | Top8=0.9702 | Top16=0.9936 | Top32=0.9982

Byte 07 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 53/80 | train_loss=1.2240 | val_loss=1.6759 | lr=1.00e-03 | Top1=0.5787 | Top2=0.7631 | Top4=0.8969 | Top8=0.9709 | Top16=0.9911 | Top32=0.9960

Byte 07 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 54/80 | train_loss=1.1875 | val_loss=1.4884 | lr=1.00e-03 | Top1=0.6113 | Top2=0.7976 | Top4=0.9211 | Top8=0.9773 | Top16=0.9936 | Top32=0.9973

Byte 07 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 55/80 | train_loss=1.1730 | val_loss=1.7234 | lr=1.00e-03 | Top1=0.5602 | Top2=0.7491 | Top4=0.8929 | Top8=0.9644 | Top16=0.9924 | Top32=0.9967

Byte 07 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 56/80 | train_loss=1.1531 | val_loss=1.5238 | lr=1.00e-03 | Top1=0.6111 | Top2=0.7949 | Top4=0.9207 | Top8=0.9769 | Top16=0.9933 | Top32=0.9984

Byte 07 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 57/80 | train_loss=1.1266 | val_loss=1.4467 | lr=1.00e-03 | Top1=0.6431 | Top2=0.8100 | Top4=0.9264 | Top8=0.9789 | Top16=0.9944 | Top32=0.9987

Byte 07 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 58/80 | train_loss=1.1186 | val_loss=1.5949 | lr=1.00e-03 | Top1=0.6044 | Top2=0.7896 | Top4=0.9073 | Top8=0.9713 | Top16=0.9920 | Top32=0.9967

Byte 07 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 59/80 | train_loss=1.0908 | val_loss=1.5234 | lr=1.00e-03 | Top1=0.6224 | Top2=0.7896 | Top4=0.9169 | Top8=0.9751 | Top16=0.9944 | Top32=0.9976

Byte 07 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 60/80 | train_loss=1.0823 | val_loss=1.5321 | lr=1.00e-03 | Top1=0.6120 | Top2=0.7984 | Top4=0.9178 | Top8=0.9767 | Top16=0.9927 | Top32=0.9971

Byte 07 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 61/80 | train_loss=1.0503 | val_loss=1.5335 | lr=1.00e-03 | Top1=0.6349 | Top2=0.8027 | Top4=0.9209 | Top8=0.9760 | Top16=0.9911 | Top32=0.9947

Byte 07 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 62/80 | train_loss=1.0344 | val_loss=1.4281 | lr=1.00e-03 | Top1=0.6456 | Top2=0.8236 | Top4=0.9289 | Top8=0.9804 | Top16=0.9938 | Top32=0.9964

Byte 07 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 63/80 | train_loss=0.9986 | val_loss=1.4322 | lr=1.00e-03 | Top1=0.6444 | Top2=0.8220 | Top4=0.9349 | Top8=0.9816 | Top16=0.9949 | Top32=0.9973

Byte 07 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 64/80 | train_loss=1.0067 | val_loss=1.5561 | lr=1.00e-03 | Top1=0.6109 | Top2=0.7982 | Top4=0.9191 | Top8=0.9724 | Top16=0.9922 | Top32=0.9962

Byte 07 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 65/80 | train_loss=0.9820 | val_loss=1.4937 | lr=1.00e-03 | Top1=0.6364 | Top2=0.8118 | Top4=0.9298 | Top8=0.9798 | Top16=0.9936 | Top32=0.9971

Byte 07 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 66/80 | train_loss=0.9594 | val_loss=1.4815 | lr=1.00e-03 | Top1=0.6438 | Top2=0.8178 | Top4=0.9271 | Top8=0.9789 | Top16=0.9944 | Top32=0.9978

Byte 07 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 67/80 | train_loss=0.9608 | val_loss=1.5224 | lr=1.00e-03 | Top1=0.6364 | Top2=0.8069 | Top4=0.9260 | Top8=0.9764 | Top16=0.9891 | Top32=0.9940

Byte 07 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 68/80 | train_loss=0.9396 | val_loss=1.5488 | lr=1.00e-03 | Top1=0.6291 | Top2=0.8102 | Top4=0.9251 | Top8=0.9753 | Top16=0.9924 | Top32=0.9951

Byte 07 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 69/80 | train_loss=0.9313 | val_loss=1.5882 | lr=1.00e-03 | Top1=0.6247 | Top2=0.8040 | Top4=0.9253 | Top8=0.9760 | Top16=0.9924 | Top32=0.9958

Byte 07 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 70/80 | train_loss=0.7900 | val_loss=1.2911 | lr=5.00e-04 | Top1=0.6971 | Top2=0.8549 | Top4=0.9542 | Top8=0.9844 | Top16=0.9938 | Top32=0.9967

Byte 07 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 71/80 | train_loss=0.7553 | val_loss=1.3575 | lr=5.00e-04 | Top1=0.6778 | Top2=0.8491 | Top4=0.9462 | Top8=0.9844 | Top16=0.9933 | Top32=0.9967

Byte 07 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 72/80 | train_loss=0.7431 | val_loss=1.3372 | lr=5.00e-04 | Top1=0.6944 | Top2=0.8558 | Top4=0.9476 | Top8=0.9836 | Top16=0.9920 | Top32=0.9942

Byte 07 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 73/80 | train_loss=0.7243 | val_loss=1.2908 | lr=5.00e-04 | Top1=0.7022 | Top2=0.8622 | Top4=0.9529 | Top8=0.9858 | Top16=0.9938 | Top32=0.9960

Byte 07 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 74/80 | train_loss=0.7136 | val_loss=1.3945 | lr=5.00e-04 | Top1=0.6829 | Top2=0.8471 | Top4=0.9422 | Top8=0.9800 | Top16=0.9929 | Top32=0.9956

Byte 07 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 75/80 | train_loss=0.7093 | val_loss=1.3203 | lr=5.00e-04 | Top1=0.7033 | Top2=0.8562 | Top4=0.9493 | Top8=0.9847 | Top16=0.9922 | Top32=0.9956

Byte 07 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 76/80 | train_loss=0.6972 | val_loss=1.2721 | lr=5.00e-04 | Top1=0.7100 | Top2=0.8644 | Top4=0.9536 | Top8=0.9849 | Top16=0.9947 | Top32=0.9978

Byte 07 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 77/80 | train_loss=0.6310 | val_loss=1.2630 | lr=2.50e-04 | Top1=0.7164 | Top2=0.8758 | Top4=0.9578 | Top8=0.9860 | Top16=0.9927 | Top32=0.9956

Byte 07 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 78/80 | train_loss=0.6195 | val_loss=1.2523 | lr=2.50e-04 | Top1=0.7178 | Top2=0.8716 | Top4=0.9540 | Top8=0.9862 | Top16=0.9931 | Top32=0.9956

Byte 07 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 79/80 | train_loss=0.6162 | val_loss=1.3080 | lr=2.50e-04 | Top1=0.7093 | Top2=0.8631 | Top4=0.9507 | Top8=0.9816 | Top16=0.9900 | Top32=0.9944

Byte 07 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 07 | Epoch 80/80 | train_loss=0.6123 | val_loss=1.2341 | lr=2.50e-04 | Top1=0.7222 | Top2=0.8760 | Top4=0.9571 | Top8=0.9862 | Top16=0.9927 | Top32=0.9953

Finished ASCON byte 07
Best epoch: 77
Test Top-k: {'top1': 0.7073333263397217, 'top2': 0.8586666584014893, 'top4': 0.9457777738571167, 'top8': 0.9851111173629761, 'top16': 0.9933333396911621, 'top32': 0.995555579662323}
Grouped Top4: {'grouped_n1_top4': 0.9457777738571167, 'grouped_n2_top4': 0.9926470518112183, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.02
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_07\byte_07_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_07\byte_07_summary.csv

Loading ASCON byte 08
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_08
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 08 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 01/80 | train_loss=5.3745 | val_loss=5.2478 | lr=1.00e-03 | Top1=0.0131 | Top2=0.0271 | Top4=0.0489 | Top8=0.0940 | Top16=0.1704 | Top32=0.2984

Byte 08 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 02/80 | train_loss=4.9440 | val_loss=4.7183 | lr=1.00e-03 | Top1=0.0338 | Top2=0.0576 | Top4=0.1058 | Top8=0.1858 | Top16=0.3193 | Top32=0.5056

Byte 08 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 03/80 | train_loss=4.4042 | val_loss=4.0970 | lr=1.00e-03 | Top1=0.0684 | Top2=0.1242 | Top4=0.2089 | Top8=0.3522 | Top16=0.5222 | Top32=0.7387

Byte 08 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 04/80 | train_loss=3.8098 | val_loss=3.3817 | lr=1.00e-03 | Top1=0.1553 | Top2=0.2651 | Top4=0.4167 | Top8=0.5964 | Top16=0.7813 | Top32=0.9282

Byte 08 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 05/80 | train_loss=3.2540 | val_loss=2.8469 | lr=1.00e-03 | Top1=0.2338 | Top2=0.3787 | Top4=0.5760 | Top8=0.7758 | Top16=0.9218 | Top32=0.9847

Byte 08 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 06/80 | train_loss=2.8854 | val_loss=2.4750 | lr=1.00e-03 | Top1=0.3140 | Top2=0.4967 | Top4=0.6920 | Top8=0.8744 | Top16=0.9720 | Top32=0.9978

Byte 08 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 07/80 | train_loss=2.5947 | val_loss=2.3366 | lr=1.00e-03 | Top1=0.3478 | Top2=0.5287 | Top4=0.7373 | Top8=0.9022 | Top16=0.9776 | Top32=0.9980

Byte 08 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 08/80 | train_loss=2.3542 | val_loss=2.1296 | lr=1.00e-03 | Top1=0.4113 | Top2=0.5993 | Top4=0.7751 | Top8=0.9196 | Top16=0.9811 | Top32=0.9980

Byte 08 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 09/80 | train_loss=2.1386 | val_loss=1.7148 | lr=1.00e-03 | Top1=0.5391 | Top2=0.7509 | Top4=0.9107 | Top8=0.9842 | Top16=0.9980 | Top32=0.9998

Byte 08 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 10/80 | train_loss=1.9381 | val_loss=1.5900 | lr=1.00e-03 | Top1=0.5847 | Top2=0.7784 | Top4=0.9218 | Top8=0.9867 | Top16=0.9993 | Top32=1.0000

Byte 08 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 11/80 | train_loss=1.7682 | val_loss=1.4268 | lr=1.00e-03 | Top1=0.6464 | Top2=0.8424 | Top4=0.9524 | Top8=0.9929 | Top16=0.9991 | Top32=0.9998

Byte 08 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 12/80 | train_loss=1.6255 | val_loss=1.3059 | lr=1.00e-03 | Top1=0.6998 | Top2=0.8660 | Top4=0.9696 | Top8=0.9962 | Top16=0.9998 | Top32=1.0000

Byte 08 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 13/80 | train_loss=1.5130 | val_loss=1.2251 | lr=1.00e-03 | Top1=0.7191 | Top2=0.8964 | Top4=0.9780 | Top8=0.9967 | Top16=0.9996 | Top32=1.0000

Byte 08 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 14/80 | train_loss=1.4197 | val_loss=1.1077 | lr=1.00e-03 | Top1=0.7664 | Top2=0.9231 | Top4=0.9853 | Top8=0.9987 | Top16=0.9998 | Top32=1.0000

Byte 08 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 15/80 | train_loss=1.3421 | val_loss=1.0364 | lr=1.00e-03 | Top1=0.7896 | Top2=0.9362 | Top4=0.9869 | Top8=0.9989 | Top16=0.9996 | Top32=1.0000

Byte 08 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 16/80 | train_loss=1.2874 | val_loss=1.0169 | lr=1.00e-03 | Top1=0.7978 | Top2=0.9373 | Top4=0.9889 | Top8=0.9984 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 17/80 | train_loss=1.2254 | val_loss=1.0098 | lr=1.00e-03 | Top1=0.7967 | Top2=0.9344 | Top4=0.9880 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 18/80 | train_loss=1.1726 | val_loss=0.9525 | lr=1.00e-03 | Top1=0.8156 | Top2=0.9447 | Top4=0.9916 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 19/80 | train_loss=1.1211 | val_loss=0.8675 | lr=1.00e-03 | Top1=0.8602 | Top2=0.9702 | Top4=0.9942 | Top8=0.9993 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 20/80 | train_loss=1.0916 | val_loss=0.8554 | lr=1.00e-03 | Top1=0.8584 | Top2=0.9676 | Top4=0.9958 | Top8=0.9996 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 21/80 | train_loss=1.0390 | val_loss=0.8347 | lr=1.00e-03 | Top1=0.8620 | Top2=0.9667 | Top4=0.9971 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 22/80 | train_loss=1.0074 | val_loss=0.7943 | lr=1.00e-03 | Top1=0.8791 | Top2=0.9693 | Top4=0.9953 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 23/80 | train_loss=0.9712 | val_loss=0.8505 | lr=1.00e-03 | Top1=0.8516 | Top2=0.9591 | Top4=0.9958 | Top8=0.9991 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 24/80 | train_loss=0.9454 | val_loss=0.7285 | lr=1.00e-03 | Top1=0.9107 | Top2=0.9827 | Top4=0.9984 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 25/80 | train_loss=0.9039 | val_loss=0.7160 | lr=1.00e-03 | Top1=0.9080 | Top2=0.9840 | Top4=0.9987 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 26/80 | train_loss=0.8790 | val_loss=0.6851 | lr=1.00e-03 | Top1=0.9231 | Top2=0.9871 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 27/80 | train_loss=0.8624 | val_loss=0.6826 | lr=1.00e-03 | Top1=0.9164 | Top2=0.9842 | Top4=0.9993 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 28/80 | train_loss=0.8368 | val_loss=0.6601 | lr=1.00e-03 | Top1=0.9269 | Top2=0.9869 | Top4=0.9984 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 29/80 | train_loss=0.8053 | val_loss=0.6826 | lr=1.00e-03 | Top1=0.9209 | Top2=0.9820 | Top4=0.9976 | Top8=0.9996 | Top16=0.9998 | Top32=1.0000

Byte 08 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 30/80 | train_loss=0.7930 | val_loss=0.6658 | lr=1.00e-03 | Top1=0.9198 | Top2=0.9829 | Top4=0.9991 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 31/80 | train_loss=0.7622 | val_loss=0.6344 | lr=1.00e-03 | Top1=0.9331 | Top2=0.9902 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 32/80 | train_loss=0.7441 | val_loss=0.6293 | lr=1.00e-03 | Top1=0.9316 | Top2=0.9909 | Top4=0.9991 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 33/80 | train_loss=0.7232 | val_loss=0.6202 | lr=1.00e-03 | Top1=0.9338 | Top2=0.9856 | Top4=0.9980 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 34/80 | train_loss=0.7076 | val_loss=0.6136 | lr=1.00e-03 | Top1=0.9429 | Top2=0.9882 | Top4=0.9982 | Top8=0.9998 | Top16=0.9998 | Top32=1.0000

Byte 08 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 35/80 | train_loss=0.6927 | val_loss=0.5772 | lr=1.00e-03 | Top1=0.9567 | Top2=0.9940 | Top4=0.9993 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 36/80 | train_loss=0.6687 | val_loss=0.6022 | lr=1.00e-03 | Top1=0.9376 | Top2=0.9900 | Top4=0.9984 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 37/80 | train_loss=0.6578 | val_loss=0.5702 | lr=1.00e-03 | Top1=0.9498 | Top2=0.9936 | Top4=0.9989 | Top8=0.9998 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 38/80 | train_loss=0.5783 | val_loss=0.5172 | lr=5.00e-04 | Top1=0.9673 | Top2=0.9951 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 39/80 | train_loss=0.5561 | val_loss=0.5040 | lr=5.00e-04 | Top1=0.9727 | Top2=0.9973 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 40/80 | train_loss=0.5406 | val_loss=0.5046 | lr=5.00e-04 | Top1=0.9707 | Top2=0.9973 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 41/80 | train_loss=0.5348 | val_loss=0.4926 | lr=5.00e-04 | Top1=0.9720 | Top2=0.9973 | Top4=0.9993 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 42/80 | train_loss=0.5242 | val_loss=0.5180 | lr=5.00e-04 | Top1=0.9653 | Top2=0.9938 | Top4=0.9993 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 43/80 | train_loss=0.5185 | val_loss=0.5136 | lr=5.00e-04 | Top1=0.9624 | Top2=0.9958 | Top4=0.9991 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 44/80 | train_loss=0.5094 | val_loss=0.4866 | lr=5.00e-04 | Top1=0.9713 | Top2=0.9973 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 45/80 | train_loss=0.5017 | val_loss=0.4890 | lr=5.00e-04 | Top1=0.9673 | Top2=0.9969 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 46/80 | train_loss=0.4767 | val_loss=0.4648 | lr=2.50e-04 | Top1=0.9769 | Top2=0.9976 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 47/80 | train_loss=0.4647 | val_loss=0.4567 | lr=2.50e-04 | Top1=0.9767 | Top2=0.9980 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 48/80 | train_loss=0.4580 | val_loss=0.4558 | lr=2.50e-04 | Top1=0.9789 | Top2=0.9984 | Top4=0.9996 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 49/80 | train_loss=0.4536 | val_loss=0.4441 | lr=2.50e-04 | Top1=0.9811 | Top2=0.9987 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 50/80 | train_loss=0.4491 | val_loss=0.4406 | lr=2.50e-04 | Top1=0.9829 | Top2=0.9987 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 51/80 | train_loss=0.4505 | val_loss=0.4505 | lr=2.50e-04 | Top1=0.9782 | Top2=0.9976 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 52/80 | train_loss=0.4380 | val_loss=0.4372 | lr=1.25e-04 | Top1=0.9824 | Top2=0.9987 | Top4=1.0000 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 53/80 | train_loss=0.4331 | val_loss=0.4327 | lr=1.25e-04 | Top1=0.9836 | Top2=0.9989 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000

Byte 08 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 08 | Epoch 54/80 | train_loss=0.4320 | val_loss=0.4342 | lr=1.25e-04 | Top1=0.9831 | Top2=0.9989 | Top4=0.9998 | Top8=1.0000 | Top16=1.0000 | Top32=1.0000
Early stopping at epoch 54. Best epoch: 39, best val Top4: 1.0000

Finished ASCON byte 08
Best epoch: 39
Test Top-k: {'top1': 0.9722222089767456, 'top2': 0.996666669845581, 'top4': 1.0, 'top8': 1.0, 'top16': 1.0, 'top32': 1.0}
Grouped Top4: {'grouped_n1_top4': 1.0, 'grouped_n2_top4': 1.0, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 8.13
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_08\byte_08_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_08\byte_08_summary.csv

Loading ASCON byte 09
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_09
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 09 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 01/80 | train_loss=5.4310 | val_loss=5.1647 | lr=1.00e-03 | Top1=0.0129 | Top2=0.0253 | Top4=0.0491 | Top8=0.0960 | Top16=0.1820 | Top32=0.3304

Byte 09 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 02/80 | train_loss=4.9148 | val_loss=4.7841 | lr=1.00e-03 | Top1=0.0227 | Top2=0.0418 | Top4=0.0831 | Top8=0.1538 | Top16=0.2622 | Top32=0.4520

Byte 09 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 03/80 | train_loss=4.5748 | val_loss=4.3393 | lr=1.00e-03 | Top1=0.0333 | Top2=0.0636 | Top4=0.1233 | Top8=0.2296 | Top16=0.3880 | Top32=0.6291

Byte 09 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 04/80 | train_loss=4.3395 | val_loss=4.2933 | lr=1.00e-03 | Top1=0.0249 | Top2=0.0529 | Top4=0.1082 | Top8=0.2118 | Top16=0.3916 | Top32=0.6624

Byte 09 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 05/80 | train_loss=4.1995 | val_loss=4.4987 | lr=1.00e-03 | Top1=0.0284 | Top2=0.0502 | Top4=0.0918 | Top8=0.1698 | Top16=0.3173 | Top32=0.5862

Byte 09 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 06/80 | train_loss=4.0853 | val_loss=3.9400 | lr=1.00e-03 | Top1=0.0522 | Top2=0.0936 | Top4=0.1796 | Top8=0.3244 | Top16=0.5256 | Top32=0.7993

Byte 09 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 07/80 | train_loss=3.9829 | val_loss=3.8648 | lr=1.00e-03 | Top1=0.0544 | Top2=0.0982 | Top4=0.1924 | Top8=0.3580 | Top16=0.5796 | Top32=0.8336

Byte 09 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 08/80 | train_loss=3.8855 | val_loss=3.7903 | lr=1.00e-03 | Top1=0.0571 | Top2=0.1102 | Top4=0.2109 | Top8=0.3709 | Top16=0.6089 | Top32=0.8647

Byte 09 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 09/80 | train_loss=3.8164 | val_loss=3.7340 | lr=1.00e-03 | Top1=0.0578 | Top2=0.1089 | Top4=0.2131 | Top8=0.3771 | Top16=0.6336 | Top32=0.9073

Byte 09 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 10/80 | train_loss=3.7303 | val_loss=3.6554 | lr=1.00e-03 | Top1=0.0702 | Top2=0.1364 | Top4=0.2396 | Top8=0.4204 | Top16=0.6644 | Top32=0.8980

Byte 09 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 11/80 | train_loss=3.7027 | val_loss=3.5806 | lr=1.00e-03 | Top1=0.0696 | Top2=0.1333 | Top4=0.2562 | Top8=0.4436 | Top16=0.6867 | Top32=0.9273

Byte 09 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 12/80 | train_loss=3.6495 | val_loss=3.4497 | lr=1.00e-03 | Top1=0.0920 | Top2=0.1740 | Top4=0.3013 | Top8=0.5096 | Top16=0.7569 | Top32=0.9469

Byte 09 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 13/80 | train_loss=3.5913 | val_loss=3.5282 | lr=1.00e-03 | Top1=0.0753 | Top2=0.1478 | Top4=0.2638 | Top8=0.4667 | Top16=0.7258 | Top32=0.9453

Byte 09 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 14/80 | train_loss=3.5457 | val_loss=3.4019 | lr=1.00e-03 | Top1=0.0969 | Top2=0.1784 | Top4=0.3144 | Top8=0.5164 | Top16=0.7684 | Top32=0.9578

Byte 09 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 15/80 | train_loss=3.5127 | val_loss=3.4142 | lr=1.00e-03 | Top1=0.0891 | Top2=0.1740 | Top4=0.3138 | Top8=0.5176 | Top16=0.7618 | Top32=0.9584

Byte 09 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 16/80 | train_loss=3.4858 | val_loss=3.4054 | lr=1.00e-03 | Top1=0.1011 | Top2=0.1880 | Top4=0.3142 | Top8=0.5247 | Top16=0.7658 | Top32=0.9518

Byte 09 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 17/80 | train_loss=3.4287 | val_loss=3.3347 | lr=1.00e-03 | Top1=0.1147 | Top2=0.1953 | Top4=0.3513 | Top8=0.5636 | Top16=0.7898 | Top32=0.9600

Byte 09 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 18/80 | train_loss=3.3962 | val_loss=3.3313 | lr=1.00e-03 | Top1=0.1129 | Top2=0.2022 | Top4=0.3544 | Top8=0.5618 | Top16=0.7967 | Top32=0.9547

Byte 09 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 19/80 | train_loss=3.3458 | val_loss=3.3484 | lr=1.00e-03 | Top1=0.1082 | Top2=0.1938 | Top4=0.3349 | Top8=0.5560 | Top16=0.7931 | Top32=0.9616

Byte 09 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 20/80 | train_loss=3.2987 | val_loss=3.2361 | lr=1.00e-03 | Top1=0.1271 | Top2=0.2302 | Top4=0.3791 | Top8=0.6069 | Top16=0.8340 | Top32=0.9713

Byte 09 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 21/80 | train_loss=3.2585 | val_loss=3.1917 | lr=1.00e-03 | Top1=0.1309 | Top2=0.2427 | Top4=0.3984 | Top8=0.6387 | Top16=0.8618 | Top32=0.9804

Byte 09 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 22/80 | train_loss=3.1624 | val_loss=3.2066 | lr=1.00e-03 | Top1=0.1309 | Top2=0.2407 | Top4=0.4096 | Top8=0.6316 | Top16=0.8540 | Top32=0.9829

Byte 09 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 23/80 | train_loss=3.1207 | val_loss=3.0667 | lr=1.00e-03 | Top1=0.1562 | Top2=0.2827 | Top4=0.4720 | Top8=0.6902 | Top16=0.8898 | Top32=0.9818

Byte 09 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 24/80 | train_loss=3.0674 | val_loss=3.0275 | lr=1.00e-03 | Top1=0.1640 | Top2=0.2878 | Top4=0.4702 | Top8=0.7007 | Top16=0.8931 | Top32=0.9898

Byte 09 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 25/80 | train_loss=2.9972 | val_loss=3.1576 | lr=1.00e-03 | Top1=0.1536 | Top2=0.2671 | Top4=0.4453 | Top8=0.6758 | Top16=0.8849 | Top32=0.9867

Byte 09 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 26/80 | train_loss=2.9348 | val_loss=2.9583 | lr=1.00e-03 | Top1=0.1909 | Top2=0.3211 | Top4=0.4969 | Top8=0.7276 | Top16=0.9071 | Top32=0.9827

Byte 09 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 27/80 | train_loss=2.8840 | val_loss=2.8481 | lr=1.00e-03 | Top1=0.2078 | Top2=0.3513 | Top4=0.5502 | Top8=0.7622 | Top16=0.9167 | Top32=0.9871

Byte 09 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 28/80 | train_loss=2.8294 | val_loss=2.8187 | lr=1.00e-03 | Top1=0.2149 | Top2=0.3544 | Top4=0.5656 | Top8=0.7807 | Top16=0.9264 | Top32=0.9916

Byte 09 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 29/80 | train_loss=2.7809 | val_loss=2.7046 | lr=1.00e-03 | Top1=0.2393 | Top2=0.3902 | Top4=0.5942 | Top8=0.8047 | Top16=0.9433 | Top32=0.9927

Byte 09 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 30/80 | train_loss=2.7189 | val_loss=2.6678 | lr=1.00e-03 | Top1=0.2507 | Top2=0.4120 | Top4=0.6167 | Top8=0.8109 | Top16=0.9378 | Top32=0.9922

Byte 09 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 31/80 | train_loss=2.6683 | val_loss=2.6668 | lr=1.00e-03 | Top1=0.2464 | Top2=0.4104 | Top4=0.6184 | Top8=0.8151 | Top16=0.9449 | Top32=0.9918

Byte 09 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 32/80 | train_loss=2.6146 | val_loss=2.5667 | lr=1.00e-03 | Top1=0.2818 | Top2=0.4511 | Top4=0.6607 | Top8=0.8491 | Top16=0.9567 | Top32=0.9931

Byte 09 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 33/80 | train_loss=2.5641 | val_loss=2.5901 | lr=1.00e-03 | Top1=0.2764 | Top2=0.4418 | Top4=0.6493 | Top8=0.8384 | Top16=0.9447 | Top32=0.9918

Byte 09 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 34/80 | train_loss=2.4944 | val_loss=2.5408 | lr=1.00e-03 | Top1=0.2876 | Top2=0.4520 | Top4=0.6611 | Top8=0.8593 | Top16=0.9593 | Top32=0.9944

Byte 09 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 35/80 | train_loss=2.4647 | val_loss=2.4648 | lr=1.00e-03 | Top1=0.3098 | Top2=0.4829 | Top4=0.6978 | Top8=0.8578 | Top16=0.9591 | Top32=0.9949

Byte 09 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 36/80 | train_loss=2.4157 | val_loss=2.4594 | lr=1.00e-03 | Top1=0.3029 | Top2=0.4813 | Top4=0.6920 | Top8=0.8616 | Top16=0.9651 | Top32=0.9951

Byte 09 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 37/80 | train_loss=2.3577 | val_loss=2.4306 | lr=1.00e-03 | Top1=0.3127 | Top2=0.4904 | Top4=0.6993 | Top8=0.8767 | Top16=0.9707 | Top32=0.9967

Byte 09 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 38/80 | train_loss=2.2959 | val_loss=2.3088 | lr=1.00e-03 | Top1=0.3464 | Top2=0.5391 | Top4=0.7460 | Top8=0.8980 | Top16=0.9704 | Top32=0.9964

Byte 09 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 39/80 | train_loss=2.2444 | val_loss=2.2347 | lr=1.00e-03 | Top1=0.3664 | Top2=0.5689 | Top4=0.7693 | Top8=0.9116 | Top16=0.9762 | Top32=0.9964

Byte 09 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 40/80 | train_loss=2.1789 | val_loss=2.2473 | lr=1.00e-03 | Top1=0.3767 | Top2=0.5647 | Top4=0.7607 | Top8=0.9093 | Top16=0.9756 | Top32=0.9940

Byte 09 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 41/80 | train_loss=2.1291 | val_loss=2.2343 | lr=1.00e-03 | Top1=0.3764 | Top2=0.5682 | Top4=0.7631 | Top8=0.9038 | Top16=0.9771 | Top32=0.9967

Byte 09 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 42/80 | train_loss=2.1001 | val_loss=2.1855 | lr=1.00e-03 | Top1=0.3882 | Top2=0.5907 | Top4=0.7793 | Top8=0.9178 | Top16=0.9764 | Top32=0.9964

Byte 09 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 43/80 | train_loss=2.0357 | val_loss=2.0683 | lr=1.00e-03 | Top1=0.4118 | Top2=0.6207 | Top4=0.8173 | Top8=0.9313 | Top16=0.9838 | Top32=0.9980

Byte 09 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 44/80 | train_loss=1.9892 | val_loss=2.0733 | lr=1.00e-03 | Top1=0.4207 | Top2=0.6222 | Top4=0.8027 | Top8=0.9291 | Top16=0.9838 | Top32=0.9958

Byte 09 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 45/80 | train_loss=1.9293 | val_loss=2.1578 | lr=1.00e-03 | Top1=0.3998 | Top2=0.5911 | Top4=0.7804 | Top8=0.9249 | Top16=0.9831 | Top32=0.9971

Byte 09 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 46/80 | train_loss=1.8916 | val_loss=2.0843 | lr=1.00e-03 | Top1=0.4111 | Top2=0.6118 | Top4=0.8076 | Top8=0.9344 | Top16=0.9827 | Top32=0.9969

Byte 09 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 47/80 | train_loss=1.8550 | val_loss=2.0154 | lr=1.00e-03 | Top1=0.4358 | Top2=0.6364 | Top4=0.8196 | Top8=0.9342 | Top16=0.9851 | Top32=0.9973

Byte 09 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 48/80 | train_loss=1.8145 | val_loss=2.0710 | lr=1.00e-03 | Top1=0.4264 | Top2=0.6236 | Top4=0.8078 | Top8=0.9311 | Top16=0.9824 | Top32=0.9964

Byte 09 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 49/80 | train_loss=1.7673 | val_loss=1.9987 | lr=1.00e-03 | Top1=0.4531 | Top2=0.6453 | Top4=0.8240 | Top8=0.9398 | Top16=0.9856 | Top32=0.9982

Byte 09 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 50/80 | train_loss=1.7308 | val_loss=1.9687 | lr=1.00e-03 | Top1=0.4562 | Top2=0.6556 | Top4=0.8298 | Top8=0.9460 | Top16=0.9878 | Top32=0.9976

Byte 09 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 51/80 | train_loss=1.7010 | val_loss=1.9568 | lr=1.00e-03 | Top1=0.4620 | Top2=0.6564 | Top4=0.8393 | Top8=0.9458 | Top16=0.9880 | Top32=0.9978

Byte 09 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 52/80 | train_loss=1.6620 | val_loss=1.9754 | lr=1.00e-03 | Top1=0.4671 | Top2=0.6656 | Top4=0.8396 | Top8=0.9478 | Top16=0.9831 | Top32=0.9953

Byte 09 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 53/80 | train_loss=1.6302 | val_loss=2.1126 | lr=1.00e-03 | Top1=0.4193 | Top2=0.6198 | Top4=0.8118 | Top8=0.9349 | Top16=0.9856 | Top32=0.9958

Byte 09 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 54/80 | train_loss=1.5882 | val_loss=1.9300 | lr=1.00e-03 | Top1=0.4720 | Top2=0.6831 | Top4=0.8489 | Top8=0.9444 | Top16=0.9864 | Top32=0.9962

Byte 09 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 55/80 | train_loss=1.5641 | val_loss=1.9508 | lr=1.00e-03 | Top1=0.4756 | Top2=0.6696 | Top4=0.8398 | Top8=0.9416 | Top16=0.9864 | Top32=0.9962

Byte 09 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 56/80 | train_loss=1.5268 | val_loss=1.8679 | lr=1.00e-03 | Top1=0.4956 | Top2=0.6942 | Top4=0.8540 | Top8=0.9531 | Top16=0.9889 | Top32=0.9978

Byte 09 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 57/80 | train_loss=1.5084 | val_loss=1.8551 | lr=1.00e-03 | Top1=0.4873 | Top2=0.6947 | Top4=0.8633 | Top8=0.9560 | Top16=0.9900 | Top32=0.9980

Byte 09 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 58/80 | train_loss=1.4885 | val_loss=1.8832 | lr=1.00e-03 | Top1=0.4956 | Top2=0.6938 | Top4=0.8500 | Top8=0.9544 | Top16=0.9887 | Top32=0.9973

Byte 09 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 59/80 | train_loss=1.4349 | val_loss=1.7964 | lr=1.00e-03 | Top1=0.5142 | Top2=0.7158 | Top4=0.8720 | Top8=0.9640 | Top16=0.9920 | Top32=0.9987

Byte 09 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 60/80 | train_loss=1.4295 | val_loss=1.9252 | lr=1.00e-03 | Top1=0.4869 | Top2=0.6858 | Top4=0.8544 | Top8=0.9511 | Top16=0.9880 | Top32=0.9969

Byte 09 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 61/80 | train_loss=1.3898 | val_loss=1.9811 | lr=1.00e-03 | Top1=0.4729 | Top2=0.6762 | Top4=0.8438 | Top8=0.9502 | Top16=0.9864 | Top32=0.9964

Byte 09 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 62/80 | train_loss=1.3654 | val_loss=1.8789 | lr=1.00e-03 | Top1=0.4884 | Top2=0.6940 | Top4=0.8584 | Top8=0.9580 | Top16=0.9900 | Top32=0.9973

Byte 09 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 63/80 | train_loss=1.3497 | val_loss=1.8867 | lr=1.00e-03 | Top1=0.5022 | Top2=0.6978 | Top4=0.8660 | Top8=0.9547 | Top16=0.9878 | Top32=0.9960

Byte 09 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 64/80 | train_loss=1.3207 | val_loss=1.9342 | lr=1.00e-03 | Top1=0.4860 | Top2=0.6876 | Top4=0.8553 | Top8=0.9549 | Top16=0.9891 | Top32=0.9956

Byte 09 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 65/80 | train_loss=1.3045 | val_loss=1.8780 | lr=1.00e-03 | Top1=0.4871 | Top2=0.7009 | Top4=0.8653 | Top8=0.9600 | Top16=0.9902 | Top32=0.9969

Byte 09 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 66/80 | train_loss=1.1467 | val_loss=1.7237 | lr=5.00e-04 | Top1=0.5438 | Top2=0.7460 | Top4=0.9009 | Top8=0.9693 | Top16=0.9920 | Top32=0.9962

Byte 09 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 67/80 | train_loss=1.0985 | val_loss=1.7686 | lr=5.00e-04 | Top1=0.5333 | Top2=0.7402 | Top4=0.8880 | Top8=0.9633 | Top16=0.9909 | Top32=0.9969

Byte 09 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 68/80 | train_loss=1.0768 | val_loss=1.6772 | lr=5.00e-04 | Top1=0.5558 | Top2=0.7616 | Top4=0.9007 | Top8=0.9722 | Top16=0.9947 | Top32=0.9971

Byte 09 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 69/80 | train_loss=1.0502 | val_loss=1.7531 | lr=5.00e-04 | Top1=0.5500 | Top2=0.7458 | Top4=0.8893 | Top8=0.9640 | Top16=0.9869 | Top32=0.9940

Byte 09 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 70/80 | train_loss=1.0338 | val_loss=1.7616 | lr=5.00e-04 | Top1=0.5378 | Top2=0.7451 | Top4=0.8891 | Top8=0.9676 | Top16=0.9909 | Top32=0.9956

Byte 09 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 71/80 | train_loss=1.0225 | val_loss=1.6677 | lr=5.00e-04 | Top1=0.5584 | Top2=0.7611 | Top4=0.9042 | Top8=0.9729 | Top16=0.9931 | Top32=0.9971

Byte 09 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 72/80 | train_loss=1.0004 | val_loss=1.7750 | lr=5.00e-04 | Top1=0.5540 | Top2=0.7460 | Top4=0.8902 | Top8=0.9636 | Top16=0.9880 | Top32=0.9938

Byte 09 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 73/80 | train_loss=0.9902 | val_loss=1.7768 | lr=5.00e-04 | Top1=0.5516 | Top2=0.7433 | Top4=0.8949 | Top8=0.9653 | Top16=0.9882 | Top32=0.9944

Byte 09 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 74/80 | train_loss=0.9787 | val_loss=1.8612 | lr=5.00e-04 | Top1=0.5293 | Top2=0.7320 | Top4=0.8831 | Top8=0.9573 | Top16=0.9840 | Top32=0.9927

Byte 09 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 75/80 | train_loss=0.9659 | val_loss=1.7539 | lr=5.00e-04 | Top1=0.5509 | Top2=0.7522 | Top4=0.8989 | Top8=0.9664 | Top16=0.9887 | Top32=0.9944

Byte 09 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 76/80 | train_loss=0.9576 | val_loss=1.7295 | lr=5.00e-04 | Top1=0.5651 | Top2=0.7553 | Top4=0.8929 | Top8=0.9680 | Top16=0.9880 | Top32=0.9949

Byte 09 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 77/80 | train_loss=0.9476 | val_loss=1.8094 | lr=5.00e-04 | Top1=0.5449 | Top2=0.7478 | Top4=0.8876 | Top8=0.9600 | Top16=0.9856 | Top32=0.9929

Byte 09 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 78/80 | train_loss=0.8743 | val_loss=1.6746 | lr=2.50e-04 | Top1=0.5718 | Top2=0.7667 | Top4=0.9051 | Top8=0.9704 | Top16=0.9913 | Top32=0.9958

Byte 09 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 79/80 | train_loss=0.8536 | val_loss=1.6903 | lr=2.50e-04 | Top1=0.5700 | Top2=0.7733 | Top4=0.9058 | Top8=0.9684 | Top16=0.9900 | Top32=0.9944

Byte 09 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 09 | Epoch 80/80 | train_loss=0.8382 | val_loss=1.6404 | lr=2.50e-04 | Top1=0.5822 | Top2=0.7780 | Top4=0.9098 | Top8=0.9753 | Top16=0.9933 | Top32=0.9958

Finished ASCON byte 09
Best epoch: 80
Test Top-k: {'top1': 0.5831111073493958, 'top2': 0.7799999713897705, 'top4': 0.9095555543899536, 'top8': 0.9722222089767456, 'top16': 0.9902222156524658, 'top32': 0.9935555458068848}
Grouped Top4: {'grouped_n1_top4': 0.9095555543899536, 'grouped_n2_top4': 0.9848623871803284, 'grouped_n4_top4': 0.9990205764770508, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.03
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_09\byte_09_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_09\byte_09_summary.csv

Loading ASCON byte 10
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_10
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 10 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 01/80 | train_loss=5.4955 | val_loss=5.3686 | lr=1.00e-03 | Top1=0.0118 | Top2=0.0207 | Top4=0.0416 | Top8=0.0762 | Top16=0.1316 | Top32=0.2371

Byte 10 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 02/80 | train_loss=5.2311 | val_loss=5.0395 | lr=1.00e-03 | Top1=0.0169 | Top2=0.0344 | Top4=0.0653 | Top8=0.1222 | Top16=0.2093 | Top32=0.3591

Byte 10 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 03/80 | train_loss=4.8640 | val_loss=4.5204 | lr=1.00e-03 | Top1=0.0307 | Top2=0.0516 | Top4=0.1036 | Top8=0.1922 | Top16=0.3411 | Top32=0.5671

Byte 10 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 04/80 | train_loss=4.5051 | val_loss=4.2687 | lr=1.00e-03 | Top1=0.0369 | Top2=0.0696 | Top4=0.1300 | Top8=0.2387 | Top16=0.4036 | Top32=0.6687

Byte 10 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 05/80 | train_loss=4.2585 | val_loss=4.1548 | lr=1.00e-03 | Top1=0.0416 | Top2=0.0791 | Top4=0.1456 | Top8=0.2684 | Top16=0.4584 | Top32=0.7202

Byte 10 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 06/80 | train_loss=4.0932 | val_loss=3.8257 | lr=1.00e-03 | Top1=0.0720 | Top2=0.1322 | Top4=0.2402 | Top8=0.4044 | Top16=0.6362 | Top32=0.8604

Byte 10 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 07/80 | train_loss=3.9005 | val_loss=3.6167 | lr=1.00e-03 | Top1=0.0913 | Top2=0.1691 | Top4=0.2984 | Top8=0.4976 | Top16=0.7136 | Top32=0.9238

Byte 10 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 08/80 | train_loss=3.7418 | val_loss=3.5606 | lr=1.00e-03 | Top1=0.0973 | Top2=0.1780 | Top4=0.3078 | Top8=0.5129 | Top16=0.7396 | Top32=0.9336

Byte 10 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 09/80 | train_loss=3.6223 | val_loss=3.4588 | lr=1.00e-03 | Top1=0.1071 | Top2=0.1987 | Top4=0.3544 | Top8=0.5531 | Top16=0.7684 | Top32=0.9464

Byte 10 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 10/80 | train_loss=3.5132 | val_loss=3.2456 | lr=1.00e-03 | Top1=0.1244 | Top2=0.2378 | Top4=0.4038 | Top8=0.6262 | Top16=0.8471 | Top32=0.9776

Byte 10 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 11/80 | train_loss=3.3977 | val_loss=3.2995 | lr=1.00e-03 | Top1=0.1147 | Top2=0.2120 | Top4=0.3691 | Top8=0.6016 | Top16=0.8147 | Top32=0.9713

Byte 10 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 12/80 | train_loss=3.3293 | val_loss=3.0960 | lr=1.00e-03 | Top1=0.1444 | Top2=0.2724 | Top4=0.4587 | Top8=0.6904 | Top16=0.8800 | Top32=0.9833

Byte 10 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 13/80 | train_loss=3.2519 | val_loss=3.0101 | lr=1.00e-03 | Top1=0.1649 | Top2=0.2973 | Top4=0.4884 | Top8=0.7187 | Top16=0.9044 | Top32=0.9878

Byte 10 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 14/80 | train_loss=3.1660 | val_loss=2.9608 | lr=1.00e-03 | Top1=0.1742 | Top2=0.3156 | Top4=0.5093 | Top8=0.7244 | Top16=0.8958 | Top32=0.9844

Byte 10 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 15/80 | train_loss=3.1191 | val_loss=2.8546 | lr=1.00e-03 | Top1=0.1884 | Top2=0.3404 | Top4=0.5422 | Top8=0.7704 | Top16=0.9273 | Top32=0.9916

Byte 10 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 16/80 | train_loss=3.0203 | val_loss=2.8398 | lr=1.00e-03 | Top1=0.1893 | Top2=0.3422 | Top4=0.5582 | Top8=0.7769 | Top16=0.9322 | Top32=0.9940

Byte 10 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 17/80 | train_loss=2.9885 | val_loss=2.7885 | lr=1.00e-03 | Top1=0.1971 | Top2=0.3478 | Top4=0.5549 | Top8=0.7873 | Top16=0.9433 | Top32=0.9947

Byte 10 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 18/80 | train_loss=2.9243 | val_loss=2.7304 | lr=1.00e-03 | Top1=0.2247 | Top2=0.3818 | Top4=0.5867 | Top8=0.8009 | Top16=0.9418 | Top32=0.9913

Byte 10 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 19/80 | train_loss=2.8947 | val_loss=2.6540 | lr=1.00e-03 | Top1=0.2247 | Top2=0.4029 | Top4=0.6258 | Top8=0.8267 | Top16=0.9504 | Top32=0.9949

Byte 10 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 20/80 | train_loss=2.8385 | val_loss=2.8262 | lr=1.00e-03 | Top1=0.1971 | Top2=0.3429 | Top4=0.5502 | Top8=0.7662 | Top16=0.9289 | Top32=0.9927

Byte 10 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 21/80 | train_loss=2.7878 | val_loss=2.5682 | lr=1.00e-03 | Top1=0.2507 | Top2=0.4258 | Top4=0.6507 | Top8=0.8478 | Top16=0.9602 | Top32=0.9958

Byte 10 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 22/80 | train_loss=2.7555 | val_loss=2.4916 | lr=1.00e-03 | Top1=0.2660 | Top2=0.4609 | Top4=0.6827 | Top8=0.8720 | Top16=0.9722 | Top32=0.9982

Byte 10 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 23/80 | train_loss=2.6769 | val_loss=2.4423 | lr=1.00e-03 | Top1=0.2922 | Top2=0.4800 | Top4=0.7018 | Top8=0.8780 | Top16=0.9711 | Top32=0.9964

Byte 10 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 24/80 | train_loss=2.6314 | val_loss=2.4241 | lr=1.00e-03 | Top1=0.2873 | Top2=0.4787 | Top4=0.6998 | Top8=0.8851 | Top16=0.9738 | Top32=0.9982

Byte 10 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 25/80 | train_loss=2.5914 | val_loss=2.3328 | lr=1.00e-03 | Top1=0.3236 | Top2=0.5100 | Top4=0.7391 | Top8=0.9040 | Top16=0.9780 | Top32=0.9976

Byte 10 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 26/80 | train_loss=2.5379 | val_loss=2.3300 | lr=1.00e-03 | Top1=0.3193 | Top2=0.5222 | Top4=0.7304 | Top8=0.9016 | Top16=0.9787 | Top32=0.9987

Byte 10 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 27/80 | train_loss=2.4843 | val_loss=2.2824 | lr=1.00e-03 | Top1=0.3229 | Top2=0.5267 | Top4=0.7549 | Top8=0.9189 | Top16=0.9802 | Top32=0.9984

Byte 10 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 28/80 | train_loss=2.4524 | val_loss=2.2497 | lr=1.00e-03 | Top1=0.3282 | Top2=0.5422 | Top4=0.7667 | Top8=0.9211 | Top16=0.9847 | Top32=0.9989

Byte 10 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 29/80 | train_loss=2.4068 | val_loss=2.1944 | lr=1.00e-03 | Top1=0.3484 | Top2=0.5616 | Top4=0.7702 | Top8=0.9271 | Top16=0.9878 | Top32=0.9991

Byte 10 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 30/80 | train_loss=2.3754 | val_loss=2.1584 | lr=1.00e-03 | Top1=0.3651 | Top2=0.5718 | Top4=0.7833 | Top8=0.9338 | Top16=0.9880 | Top32=0.9982

Byte 10 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 31/80 | train_loss=2.3184 | val_loss=2.1367 | lr=1.00e-03 | Top1=0.3622 | Top2=0.5809 | Top4=0.8007 | Top8=0.9413 | Top16=0.9864 | Top32=0.9996

Byte 10 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 32/80 | train_loss=2.2896 | val_loss=2.0985 | lr=1.00e-03 | Top1=0.3802 | Top2=0.6060 | Top4=0.8067 | Top8=0.9447 | Top16=0.9889 | Top32=0.9996

Byte 10 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 33/80 | train_loss=2.2483 | val_loss=2.0499 | lr=1.00e-03 | Top1=0.3924 | Top2=0.6144 | Top4=0.8238 | Top8=0.9484 | Top16=0.9907 | Top32=0.9998

Byte 10 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 34/80 | train_loss=2.2066 | val_loss=2.0133 | lr=1.00e-03 | Top1=0.3971 | Top2=0.6311 | Top4=0.8340 | Top8=0.9584 | Top16=0.9936 | Top32=0.9993

Byte 10 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 35/80 | train_loss=2.1768 | val_loss=1.9632 | lr=1.00e-03 | Top1=0.4164 | Top2=0.6509 | Top4=0.8476 | Top8=0.9587 | Top16=0.9951 | Top32=0.9996

Byte 10 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 36/80 | train_loss=2.1364 | val_loss=1.9726 | lr=1.00e-03 | Top1=0.4156 | Top2=0.6387 | Top4=0.8458 | Top8=0.9536 | Top16=0.9913 | Top32=0.9993

Byte 10 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 37/80 | train_loss=2.0991 | val_loss=1.9211 | lr=1.00e-03 | Top1=0.4344 | Top2=0.6602 | Top4=0.8580 | Top8=0.9633 | Top16=0.9940 | Top32=0.9998

Byte 10 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 38/80 | train_loss=2.0712 | val_loss=1.9537 | lr=1.00e-03 | Top1=0.4293 | Top2=0.6542 | Top4=0.8438 | Top8=0.9593 | Top16=0.9931 | Top32=0.9993

Byte 10 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 39/80 | train_loss=2.0178 | val_loss=1.8359 | lr=1.00e-03 | Top1=0.4716 | Top2=0.6913 | Top4=0.8711 | Top8=0.9700 | Top16=0.9958 | Top32=0.9993

Byte 10 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 40/80 | train_loss=1.9837 | val_loss=1.8349 | lr=1.00e-03 | Top1=0.4716 | Top2=0.7036 | Top4=0.8769 | Top8=0.9678 | Top16=0.9947 | Top32=0.9991

Byte 10 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 41/80 | train_loss=1.9287 | val_loss=1.8490 | lr=1.00e-03 | Top1=0.4747 | Top2=0.6891 | Top4=0.8691 | Top8=0.9676 | Top16=0.9956 | Top32=0.9998

Byte 10 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 42/80 | train_loss=1.8809 | val_loss=1.7944 | lr=1.00e-03 | Top1=0.4856 | Top2=0.7116 | Top4=0.8822 | Top8=0.9711 | Top16=0.9951 | Top32=0.9998

Byte 10 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 43/80 | train_loss=1.8584 | val_loss=1.8910 | lr=1.00e-03 | Top1=0.4680 | Top2=0.6860 | Top4=0.8549 | Top8=0.9624 | Top16=0.9931 | Top32=0.9991

Byte 10 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 44/80 | train_loss=1.8240 | val_loss=1.7790 | lr=1.00e-03 | Top1=0.4953 | Top2=0.7160 | Top4=0.8811 | Top8=0.9649 | Top16=0.9929 | Top32=0.9993

Byte 10 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 45/80 | train_loss=1.7884 | val_loss=1.7865 | lr=1.00e-03 | Top1=0.4847 | Top2=0.7176 | Top4=0.8802 | Top8=0.9684 | Top16=0.9931 | Top32=0.9989

Byte 10 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 46/80 | train_loss=1.7316 | val_loss=1.6932 | lr=1.00e-03 | Top1=0.5264 | Top2=0.7453 | Top4=0.9009 | Top8=0.9771 | Top16=0.9969 | Top32=0.9996

Byte 10 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 47/80 | train_loss=1.6929 | val_loss=1.7006 | lr=1.00e-03 | Top1=0.5144 | Top2=0.7391 | Top4=0.9002 | Top8=0.9776 | Top16=0.9978 | Top32=0.9996

Byte 10 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 48/80 | train_loss=1.6652 | val_loss=1.7563 | lr=1.00e-03 | Top1=0.5051 | Top2=0.7300 | Top4=0.8887 | Top8=0.9711 | Top16=0.9956 | Top32=0.9996

Byte 10 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 49/80 | train_loss=1.6333 | val_loss=1.6381 | lr=1.00e-03 | Top1=0.5411 | Top2=0.7642 | Top4=0.9153 | Top8=0.9833 | Top16=0.9964 | Top32=0.9996

Byte 10 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 50/80 | train_loss=1.5858 | val_loss=1.6498 | lr=1.00e-03 | Top1=0.5429 | Top2=0.7687 | Top4=0.9071 | Top8=0.9773 | Top16=0.9949 | Top32=0.9996

Byte 10 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 51/80 | train_loss=1.5670 | val_loss=1.5539 | lr=1.00e-03 | Top1=0.5671 | Top2=0.7931 | Top4=0.9244 | Top8=0.9856 | Top16=0.9969 | Top32=0.9998

Byte 10 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 52/80 | train_loss=1.5259 | val_loss=1.5306 | lr=1.00e-03 | Top1=0.5864 | Top2=0.8011 | Top4=0.9287 | Top8=0.9833 | Top16=0.9973 | Top32=0.9998

Byte 10 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 53/80 | train_loss=1.4892 | val_loss=1.5646 | lr=1.00e-03 | Top1=0.5709 | Top2=0.7833 | Top4=0.9193 | Top8=0.9818 | Top16=0.9967 | Top32=0.9996

Byte 10 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 54/80 | train_loss=1.4505 | val_loss=1.4659 | lr=1.00e-03 | Top1=0.6067 | Top2=0.8147 | Top4=0.9362 | Top8=0.9873 | Top16=0.9967 | Top32=0.9998

Byte 10 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 55/80 | train_loss=1.4319 | val_loss=1.5922 | lr=1.00e-03 | Top1=0.5696 | Top2=0.7818 | Top4=0.9200 | Top8=0.9784 | Top16=0.9960 | Top32=0.9996

Byte 10 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 56/80 | train_loss=1.3914 | val_loss=1.4793 | lr=1.00e-03 | Top1=0.6113 | Top2=0.8078 | Top4=0.9296 | Top8=0.9831 | Top16=0.9980 | Top32=0.9998

Byte 10 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 57/80 | train_loss=1.3643 | val_loss=1.4947 | lr=1.00e-03 | Top1=0.5984 | Top2=0.8071 | Top4=0.9289 | Top8=0.9820 | Top16=0.9980 | Top32=0.9998

Byte 10 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 58/80 | train_loss=1.3190 | val_loss=1.5065 | lr=1.00e-03 | Top1=0.5880 | Top2=0.8031 | Top4=0.9244 | Top8=0.9809 | Top16=0.9976 | Top32=1.0000

Byte 10 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 59/80 | train_loss=1.2941 | val_loss=1.5005 | lr=1.00e-03 | Top1=0.6053 | Top2=0.8031 | Top4=0.9262 | Top8=0.9820 | Top16=0.9987 | Top32=0.9996

Byte 10 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 60/80 | train_loss=1.2608 | val_loss=1.4373 | lr=1.00e-03 | Top1=0.6269 | Top2=0.8280 | Top4=0.9331 | Top8=0.9813 | Top16=0.9967 | Top32=0.9998

Byte 10 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 61/80 | train_loss=1.1197 | val_loss=1.3336 | lr=5.00e-04 | Top1=0.6516 | Top2=0.8467 | Top4=0.9493 | Top8=0.9889 | Top16=0.9989 | Top32=1.0000

Byte 10 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 62/80 | train_loss=1.0785 | val_loss=1.2982 | lr=5.00e-04 | Top1=0.6773 | Top2=0.8540 | Top4=0.9496 | Top8=0.9896 | Top16=0.9989 | Top32=0.9998

Byte 10 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 63/80 | train_loss=1.0555 | val_loss=1.3464 | lr=5.00e-04 | Top1=0.6489 | Top2=0.8482 | Top4=0.9473 | Top8=0.9896 | Top16=0.9980 | Top32=0.9998

Byte 10 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 64/80 | train_loss=1.0181 | val_loss=1.3060 | lr=5.00e-04 | Top1=0.6718 | Top2=0.8549 | Top4=0.9520 | Top8=0.9909 | Top16=0.9984 | Top32=0.9998

Byte 10 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 65/80 | train_loss=0.9998 | val_loss=1.3213 | lr=5.00e-04 | Top1=0.6640 | Top2=0.8509 | Top4=0.9480 | Top8=0.9882 | Top16=0.9978 | Top32=0.9996

Byte 10 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 66/80 | train_loss=0.9900 | val_loss=1.3272 | lr=5.00e-04 | Top1=0.6729 | Top2=0.8533 | Top4=0.9482 | Top8=0.9873 | Top16=0.9973 | Top32=0.9996

Byte 10 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 67/80 | train_loss=0.9627 | val_loss=1.3415 | lr=5.00e-04 | Top1=0.6702 | Top2=0.8444 | Top4=0.9480 | Top8=0.9884 | Top16=0.9982 | Top32=0.9991

Byte 10 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 68/80 | train_loss=0.9523 | val_loss=1.2739 | lr=5.00e-04 | Top1=0.6856 | Top2=0.8622 | Top4=0.9571 | Top8=0.9893 | Top16=0.9978 | Top32=0.9993

Byte 10 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 69/80 | train_loss=0.9425 | val_loss=1.3118 | lr=5.00e-04 | Top1=0.6744 | Top2=0.8480 | Top4=0.9462 | Top8=0.9889 | Top16=0.9971 | Top32=0.9998

Byte 10 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 70/80 | train_loss=0.9165 | val_loss=1.3034 | lr=5.00e-04 | Top1=0.6804 | Top2=0.8513 | Top4=0.9504 | Top8=0.9904 | Top16=0.9978 | Top32=0.9996

Byte 10 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 71/80 | train_loss=0.9060 | val_loss=1.2997 | lr=5.00e-04 | Top1=0.6769 | Top2=0.8607 | Top4=0.9476 | Top8=0.9891 | Top16=0.9982 | Top32=0.9993

Byte 10 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 72/80 | train_loss=0.8884 | val_loss=1.3219 | lr=5.00e-04 | Top1=0.6749 | Top2=0.8509 | Top4=0.9476 | Top8=0.9864 | Top16=0.9980 | Top32=0.9998

Byte 10 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 73/80 | train_loss=0.8782 | val_loss=1.2673 | lr=5.00e-04 | Top1=0.6904 | Top2=0.8607 | Top4=0.9558 | Top8=0.9898 | Top16=0.9973 | Top32=0.9991

Byte 10 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 74/80 | train_loss=0.8674 | val_loss=1.2981 | lr=5.00e-04 | Top1=0.6809 | Top2=0.8542 | Top4=0.9496 | Top8=0.9873 | Top16=0.9976 | Top32=0.9991

Byte 10 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 75/80 | train_loss=0.8046 | val_loss=1.2327 | lr=2.50e-04 | Top1=0.6949 | Top2=0.8742 | Top4=0.9596 | Top8=0.9898 | Top16=0.9989 | Top32=0.9998

Byte 10 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 76/80 | train_loss=0.7836 | val_loss=1.1963 | lr=2.50e-04 | Top1=0.7104 | Top2=0.8791 | Top4=0.9622 | Top8=0.9911 | Top16=0.9980 | Top32=0.9996

Byte 10 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 77/80 | train_loss=0.7728 | val_loss=1.1990 | lr=2.50e-04 | Top1=0.7129 | Top2=0.8753 | Top4=0.9624 | Top8=0.9924 | Top16=0.9987 | Top32=0.9996

Byte 10 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 78/80 | train_loss=0.7606 | val_loss=1.2038 | lr=2.50e-04 | Top1=0.7078 | Top2=0.8773 | Top4=0.9620 | Top8=0.9911 | Top16=0.9987 | Top32=0.9993

Byte 10 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 79/80 | train_loss=0.7583 | val_loss=1.2192 | lr=2.50e-04 | Top1=0.7064 | Top2=0.8736 | Top4=0.9562 | Top8=0.9907 | Top16=0.9989 | Top32=0.9998

Byte 10 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 10 | Epoch 80/80 | train_loss=0.7515 | val_loss=1.2142 | lr=2.50e-04 | Top1=0.7049 | Top2=0.8738 | Top4=0.9584 | Top8=0.9913 | Top16=0.9978 | Top32=0.9989

Finished ASCON byte 10
Best epoch: 77
Test Top-k: {'top1': 0.7075555324554443, 'top2': 0.8764444589614868, 'top4': 0.9620000123977661, 'top8': 0.9900000095367432, 'top16': 0.9973333477973938, 'top32': 0.9984444379806519}
Grouped Top4: {'grouped_n1_top4': 0.9620000123977661, 'grouped_n2_top4': 0.9977179169654846, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.02
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_10\byte_10_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_10\byte_10_summary.csv

Loading ASCON byte 11
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_11
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 11 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 01/80 | train_loss=5.5281 | val_loss=5.4783 | lr=1.00e-03 | Top1=0.0111 | Top2=0.0160 | Top4=0.0320 | Top8=0.0569 | Top16=0.1033 | Top32=0.1809

Byte 11 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 02/80 | train_loss=5.3769 | val_loss=5.1603 | lr=1.00e-03 | Top1=0.0178 | Top2=0.0344 | Top4=0.0604 | Top8=0.1153 | Top16=0.1947 | Top32=0.3429

Byte 11 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 03/80 | train_loss=4.9637 | val_loss=4.9405 | lr=1.00e-03 | Top1=0.0227 | Top2=0.0384 | Top4=0.0684 | Top8=0.1336 | Top16=0.2318 | Top32=0.3958

Byte 11 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 04/80 | train_loss=4.6177 | val_loss=4.4202 | lr=1.00e-03 | Top1=0.0291 | Top2=0.0547 | Top4=0.1120 | Top8=0.2091 | Top16=0.3489 | Top32=0.5816

Byte 11 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 05/80 | train_loss=4.3853 | val_loss=4.2355 | lr=1.00e-03 | Top1=0.0307 | Top2=0.0618 | Top4=0.1264 | Top8=0.2402 | Top16=0.4171 | Top32=0.6667

Byte 11 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 06/80 | train_loss=4.2392 | val_loss=4.1097 | lr=1.00e-03 | Top1=0.0438 | Top2=0.0780 | Top4=0.1418 | Top8=0.2609 | Top16=0.4471 | Top32=0.7100

Byte 11 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 07/80 | train_loss=4.1335 | val_loss=4.2121 | lr=1.00e-03 | Top1=0.0338 | Top2=0.0673 | Top4=0.1273 | Top8=0.2300 | Top16=0.4104 | Top32=0.6964

Byte 11 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 08/80 | train_loss=4.0744 | val_loss=3.9530 | lr=1.00e-03 | Top1=0.0431 | Top2=0.0933 | Top4=0.1742 | Top8=0.3169 | Top16=0.5322 | Top32=0.7940

Byte 11 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 09/80 | train_loss=3.9978 | val_loss=4.0092 | lr=1.00e-03 | Top1=0.0469 | Top2=0.0862 | Top4=0.1629 | Top8=0.3071 | Top16=0.5076 | Top32=0.7789

Byte 11 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 10/80 | train_loss=3.9517 | val_loss=3.8310 | lr=1.00e-03 | Top1=0.0631 | Top2=0.1156 | Top4=0.2067 | Top8=0.3578 | Top16=0.5747 | Top32=0.8273

Byte 11 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 11/80 | train_loss=3.9047 | val_loss=3.8452 | lr=1.00e-03 | Top1=0.0569 | Top2=0.1069 | Top4=0.1947 | Top8=0.3464 | Top16=0.5744 | Top32=0.8316

Byte 11 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 12/80 | train_loss=3.8425 | val_loss=3.6868 | lr=1.00e-03 | Top1=0.0729 | Top2=0.1364 | Top4=0.2473 | Top8=0.4249 | Top16=0.6524 | Top32=0.8891

Byte 11 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 13/80 | train_loss=3.7839 | val_loss=3.7152 | lr=1.00e-03 | Top1=0.0680 | Top2=0.1249 | Top4=0.2316 | Top8=0.4129 | Top16=0.6482 | Top32=0.8849

Byte 11 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 14/80 | train_loss=3.7120 | val_loss=3.4986 | lr=1.00e-03 | Top1=0.0960 | Top2=0.1836 | Top4=0.3222 | Top8=0.5076 | Top16=0.7396 | Top32=0.9316

Byte 11 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 15/80 | train_loss=3.6021 | val_loss=3.3981 | lr=1.00e-03 | Top1=0.1120 | Top2=0.2044 | Top4=0.3478 | Top8=0.5556 | Top16=0.7796 | Top32=0.9484

Byte 11 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 16/80 | train_loss=3.5023 | val_loss=3.3078 | lr=1.00e-03 | Top1=0.1176 | Top2=0.2193 | Top4=0.3813 | Top8=0.6002 | Top16=0.8209 | Top32=0.9702

Byte 11 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 17/80 | train_loss=3.4099 | val_loss=3.1622 | lr=1.00e-03 | Top1=0.1627 | Top2=0.2727 | Top4=0.4509 | Top8=0.6642 | Top16=0.8567 | Top32=0.9720

Byte 11 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 18/80 | train_loss=3.3089 | val_loss=3.0494 | lr=1.00e-03 | Top1=0.1704 | Top2=0.2998 | Top4=0.4851 | Top8=0.7136 | Top16=0.8962 | Top32=0.9836

Byte 11 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 19/80 | train_loss=3.1695 | val_loss=2.8480 | lr=1.00e-03 | Top1=0.2342 | Top2=0.3853 | Top4=0.5869 | Top8=0.7793 | Top16=0.9222 | Top32=0.9869

Byte 11 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 20/80 | train_loss=3.0065 | val_loss=2.8809 | lr=1.00e-03 | Top1=0.2171 | Top2=0.3687 | Top4=0.5644 | Top8=0.7664 | Top16=0.9111 | Top32=0.9789

Byte 11 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 21/80 | train_loss=2.8652 | val_loss=2.5371 | lr=1.00e-03 | Top1=0.3060 | Top2=0.4933 | Top4=0.6904 | Top8=0.8733 | Top16=0.9684 | Top32=0.9958

Byte 11 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 22/80 | train_loss=2.7446 | val_loss=2.4484 | lr=1.00e-03 | Top1=0.3307 | Top2=0.5178 | Top4=0.7096 | Top8=0.8722 | Top16=0.9664 | Top32=0.9938

Byte 11 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 23/80 | train_loss=2.6467 | val_loss=2.3259 | lr=1.00e-03 | Top1=0.3718 | Top2=0.5700 | Top4=0.7511 | Top8=0.9056 | Top16=0.9760 | Top32=0.9980

Byte 11 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 24/80 | train_loss=2.5218 | val_loss=2.2160 | lr=1.00e-03 | Top1=0.4156 | Top2=0.6133 | Top4=0.7893 | Top8=0.9180 | Top16=0.9756 | Top32=0.9967

Byte 11 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 25/80 | train_loss=2.4246 | val_loss=2.1676 | lr=1.00e-03 | Top1=0.4133 | Top2=0.6240 | Top4=0.7998 | Top8=0.9264 | Top16=0.9844 | Top32=0.9989

Byte 11 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 26/80 | train_loss=2.3097 | val_loss=1.9581 | lr=1.00e-03 | Top1=0.5020 | Top2=0.6962 | Top4=0.8493 | Top8=0.9533 | Top16=0.9898 | Top32=0.9989

Byte 11 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 27/80 | train_loss=2.1919 | val_loss=1.9622 | lr=1.00e-03 | Top1=0.4809 | Top2=0.6820 | Top4=0.8511 | Top8=0.9500 | Top16=0.9896 | Top32=0.9991

Byte 11 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 28/80 | train_loss=2.0882 | val_loss=1.7690 | lr=1.00e-03 | Top1=0.5584 | Top2=0.7551 | Top4=0.8920 | Top8=0.9629 | Top16=0.9913 | Top32=0.9987

Byte 11 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 29/80 | train_loss=1.9759 | val_loss=1.6915 | lr=1.00e-03 | Top1=0.5731 | Top2=0.7702 | Top4=0.9029 | Top8=0.9713 | Top16=0.9947 | Top32=0.9996

Byte 11 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 30/80 | train_loss=1.8688 | val_loss=1.7895 | lr=1.00e-03 | Top1=0.5371 | Top2=0.7324 | Top4=0.8793 | Top8=0.9600 | Top16=0.9913 | Top32=0.9996

Byte 11 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 31/80 | train_loss=1.7761 | val_loss=1.5737 | lr=1.00e-03 | Top1=0.6060 | Top2=0.7960 | Top4=0.9120 | Top8=0.9753 | Top16=0.9951 | Top32=0.9993

Byte 11 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 32/80 | train_loss=1.6959 | val_loss=1.4632 | lr=1.00e-03 | Top1=0.6487 | Top2=0.8300 | Top4=0.9331 | Top8=0.9818 | Top16=0.9956 | Top32=0.9996

Byte 11 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 33/80 | train_loss=1.6290 | val_loss=1.4175 | lr=1.00e-03 | Top1=0.6560 | Top2=0.8447 | Top4=0.9418 | Top8=0.9842 | Top16=0.9971 | Top32=1.0000

Byte 11 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 34/80 | train_loss=1.5616 | val_loss=1.3299 | lr=1.00e-03 | Top1=0.6911 | Top2=0.8624 | Top4=0.9464 | Top8=0.9880 | Top16=0.9978 | Top32=0.9998

Byte 11 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 35/80 | train_loss=1.5010 | val_loss=1.3159 | lr=1.00e-03 | Top1=0.6904 | Top2=0.8582 | Top4=0.9504 | Top8=0.9862 | Top16=0.9989 | Top32=0.9998

Byte 11 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 36/80 | train_loss=1.4368 | val_loss=1.2714 | lr=1.00e-03 | Top1=0.7060 | Top2=0.8689 | Top4=0.9569 | Top8=0.9902 | Top16=0.9982 | Top32=1.0000

Byte 11 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 37/80 | train_loss=1.3534 | val_loss=1.2535 | lr=1.00e-03 | Top1=0.7076 | Top2=0.8769 | Top4=0.9573 | Top8=0.9891 | Top16=0.9967 | Top32=0.9996

Byte 11 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 38/80 | train_loss=1.3104 | val_loss=1.2448 | lr=1.00e-03 | Top1=0.7016 | Top2=0.8751 | Top4=0.9571 | Top8=0.9882 | Top16=0.9976 | Top32=1.0000

Byte 11 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 39/80 | train_loss=1.2463 | val_loss=1.2388 | lr=1.00e-03 | Top1=0.7089 | Top2=0.8691 | Top4=0.9527 | Top8=0.9891 | Top16=0.9984 | Top32=0.9996

Byte 11 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 40/80 | train_loss=1.1891 | val_loss=1.1403 | lr=1.00e-03 | Top1=0.7498 | Top2=0.8962 | Top4=0.9647 | Top8=0.9916 | Top16=0.9993 | Top32=0.9998

Byte 11 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 41/80 | train_loss=1.1506 | val_loss=1.0799 | lr=1.00e-03 | Top1=0.7691 | Top2=0.9100 | Top4=0.9700 | Top8=0.9922 | Top16=0.9987 | Top32=0.9998

Byte 11 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 42/80 | train_loss=1.0940 | val_loss=1.0403 | lr=1.00e-03 | Top1=0.7709 | Top2=0.9138 | Top4=0.9720 | Top8=0.9953 | Top16=0.9989 | Top32=0.9998

Byte 11 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 43/80 | train_loss=1.0453 | val_loss=1.0835 | lr=1.00e-03 | Top1=0.7567 | Top2=0.9033 | Top4=0.9671 | Top8=0.9913 | Top16=0.9978 | Top32=0.9996

Byte 11 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 44/80 | train_loss=1.0205 | val_loss=1.0125 | lr=1.00e-03 | Top1=0.7869 | Top2=0.9138 | Top4=0.9744 | Top8=0.9951 | Top16=0.9998 | Top32=0.9998

Byte 11 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 45/80 | train_loss=0.9834 | val_loss=0.9737 | lr=1.00e-03 | Top1=0.7960 | Top2=0.9264 | Top4=0.9767 | Top8=0.9947 | Top16=0.9996 | Top32=0.9998

Byte 11 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 46/80 | train_loss=0.9414 | val_loss=0.9640 | lr=1.00e-03 | Top1=0.8031 | Top2=0.9231 | Top4=0.9780 | Top8=0.9944 | Top16=0.9991 | Top32=1.0000

Byte 11 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 47/80 | train_loss=0.8985 | val_loss=0.9615 | lr=1.00e-03 | Top1=0.8038 | Top2=0.9242 | Top4=0.9780 | Top8=0.9962 | Top16=0.9993 | Top32=0.9998

Byte 11 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 48/80 | train_loss=0.8561 | val_loss=0.8619 | lr=1.00e-03 | Top1=0.8340 | Top2=0.9418 | Top4=0.9849 | Top8=0.9971 | Top16=1.0000 | Top32=1.0000

Byte 11 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 49/80 | train_loss=0.8343 | val_loss=0.8550 | lr=1.00e-03 | Top1=0.8409 | Top2=0.9464 | Top4=0.9847 | Top8=0.9967 | Top16=0.9996 | Top32=1.0000

Byte 11 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 50/80 | train_loss=0.8177 | val_loss=0.8811 | lr=1.00e-03 | Top1=0.8300 | Top2=0.9409 | Top4=0.9809 | Top8=0.9951 | Top16=0.9989 | Top32=1.0000

Byte 11 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 51/80 | train_loss=0.7935 | val_loss=0.8408 | lr=1.00e-03 | Top1=0.8424 | Top2=0.9473 | Top4=0.9838 | Top8=0.9967 | Top16=0.9989 | Top32=0.9996

Byte 11 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 52/80 | train_loss=0.7745 | val_loss=0.8539 | lr=1.00e-03 | Top1=0.8356 | Top2=0.9451 | Top4=0.9862 | Top8=0.9980 | Top16=0.9996 | Top32=1.0000

Byte 11 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 53/80 | train_loss=0.7453 | val_loss=0.8121 | lr=1.00e-03 | Top1=0.8493 | Top2=0.9556 | Top4=0.9867 | Top8=0.9969 | Top16=0.9998 | Top32=1.0000

Byte 11 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 54/80 | train_loss=0.7269 | val_loss=0.8296 | lr=1.00e-03 | Top1=0.8451 | Top2=0.9464 | Top4=0.9840 | Top8=0.9969 | Top16=0.9989 | Top32=0.9993

Byte 11 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 55/80 | train_loss=0.7020 | val_loss=0.8073 | lr=1.00e-03 | Top1=0.8500 | Top2=0.9511 | Top4=0.9880 | Top8=0.9978 | Top16=0.9998 | Top32=0.9998

Byte 11 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 56/80 | train_loss=0.6873 | val_loss=0.8609 | lr=1.00e-03 | Top1=0.8336 | Top2=0.9431 | Top4=0.9827 | Top8=0.9962 | Top16=0.9987 | Top32=0.9996

Byte 11 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 57/80 | train_loss=0.6791 | val_loss=0.8722 | lr=1.00e-03 | Top1=0.8296 | Top2=0.9460 | Top4=0.9831 | Top8=0.9962 | Top16=0.9993 | Top32=0.9996

Byte 11 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 58/80 | train_loss=0.6616 | val_loss=0.7658 | lr=1.00e-03 | Top1=0.8618 | Top2=0.9560 | Top4=0.9887 | Top8=0.9976 | Top16=0.9998 | Top32=1.0000

Byte 11 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 59/80 | train_loss=0.6593 | val_loss=0.8515 | lr=1.00e-03 | Top1=0.8440 | Top2=0.9458 | Top4=0.9811 | Top8=0.9936 | Top16=0.9987 | Top32=0.9989

Byte 11 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 60/80 | train_loss=0.6362 | val_loss=0.7701 | lr=1.00e-03 | Top1=0.8573 | Top2=0.9553 | Top4=0.9902 | Top8=0.9969 | Top16=0.9996 | Top32=0.9998

Byte 11 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 61/80 | train_loss=0.6256 | val_loss=0.7719 | lr=1.00e-03 | Top1=0.8636 | Top2=0.9589 | Top4=0.9889 | Top8=0.9971 | Top16=0.9993 | Top32=0.9998

Byte 11 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 62/80 | train_loss=0.6203 | val_loss=0.7887 | lr=1.00e-03 | Top1=0.8582 | Top2=0.9571 | Top4=0.9882 | Top8=0.9971 | Top16=0.9993 | Top32=0.9998

Byte 11 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 63/80 | train_loss=0.6012 | val_loss=0.7975 | lr=1.00e-03 | Top1=0.8522 | Top2=0.9533 | Top4=0.9876 | Top8=0.9971 | Top16=0.9991 | Top32=0.9998

Byte 11 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 64/80 | train_loss=0.5979 | val_loss=0.7632 | lr=1.00e-03 | Top1=0.8733 | Top2=0.9600 | Top4=0.9884 | Top8=0.9971 | Top16=0.9989 | Top32=0.9998

Byte 11 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 65/80 | train_loss=0.5871 | val_loss=0.7482 | lr=1.00e-03 | Top1=0.8736 | Top2=0.9642 | Top4=0.9889 | Top8=0.9967 | Top16=0.9989 | Top32=0.9993

Byte 11 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 66/80 | train_loss=0.5785 | val_loss=0.7654 | lr=1.00e-03 | Top1=0.8633 | Top2=0.9582 | Top4=0.9904 | Top8=0.9980 | Top16=0.9996 | Top32=1.0000

Byte 11 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 67/80 | train_loss=0.5716 | val_loss=0.7261 | lr=1.00e-03 | Top1=0.8758 | Top2=0.9611 | Top4=0.9909 | Top8=0.9967 | Top16=0.9982 | Top32=0.9996

Byte 11 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 68/80 | train_loss=0.5624 | val_loss=0.7432 | lr=1.00e-03 | Top1=0.8716 | Top2=0.9640 | Top4=0.9893 | Top8=0.9976 | Top16=0.9993 | Top32=0.9998

Byte 11 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 69/80 | train_loss=0.5522 | val_loss=0.7841 | lr=1.00e-03 | Top1=0.8696 | Top2=0.9547 | Top4=0.9851 | Top8=0.9958 | Top16=0.9978 | Top32=0.9984

Byte 11 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 70/80 | train_loss=0.5503 | val_loss=0.7402 | lr=1.00e-03 | Top1=0.8713 | Top2=0.9609 | Top4=0.9911 | Top8=0.9978 | Top16=0.9991 | Top32=0.9998

Byte 11 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 71/80 | train_loss=0.5377 | val_loss=0.7654 | lr=1.00e-03 | Top1=0.8607 | Top2=0.9604 | Top4=0.9884 | Top8=0.9978 | Top16=0.9996 | Top32=0.9996

Byte 11 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 72/80 | train_loss=0.5393 | val_loss=0.7460 | lr=1.00e-03 | Top1=0.8698 | Top2=0.9596 | Top4=0.9884 | Top8=0.9971 | Top16=0.9987 | Top32=0.9993

Byte 11 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 73/80 | train_loss=0.5322 | val_loss=0.7437 | lr=1.00e-03 | Top1=0.8729 | Top2=0.9576 | Top4=0.9904 | Top8=0.9973 | Top16=0.9984 | Top32=0.9996

Byte 11 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 74/80 | train_loss=0.5211 | val_loss=0.7836 | lr=1.00e-03 | Top1=0.8560 | Top2=0.9551 | Top4=0.9880 | Top8=0.9958 | Top16=0.9976 | Top32=0.9991

Byte 11 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 75/80 | train_loss=0.5151 | val_loss=0.7032 | lr=1.00e-03 | Top1=0.8867 | Top2=0.9649 | Top4=0.9918 | Top8=0.9991 | Top16=0.9998 | Top32=1.0000

Byte 11 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 76/80 | train_loss=0.5118 | val_loss=0.6879 | lr=1.00e-03 | Top1=0.8909 | Top2=0.9658 | Top4=0.9916 | Top8=0.9980 | Top16=0.9993 | Top32=1.0000

Byte 11 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 77/80 | train_loss=0.5102 | val_loss=0.7131 | lr=1.00e-03 | Top1=0.8807 | Top2=0.9640 | Top4=0.9902 | Top8=0.9964 | Top16=0.9993 | Top32=0.9998

Byte 11 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 78/80 | train_loss=0.5046 | val_loss=0.7184 | lr=1.00e-03 | Top1=0.8791 | Top2=0.9631 | Top4=0.9911 | Top8=0.9976 | Top16=0.9991 | Top32=1.0000

Byte 11 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 79/80 | train_loss=0.4994 | val_loss=0.7120 | lr=1.00e-03 | Top1=0.8813 | Top2=0.9638 | Top4=0.9900 | Top8=0.9964 | Top16=0.9980 | Top32=0.9991

Byte 11 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 11 | Epoch 80/80 | train_loss=0.4928 | val_loss=0.7150 | lr=1.00e-03 | Top1=0.8796 | Top2=0.9660 | Top4=0.9920 | Top8=0.9973 | Top16=0.9996 | Top32=0.9998

Finished ASCON byte 11
Best epoch: 80
Test Top-k: {'top1': 0.8848888874053955, 'top2': 0.9639999866485596, 'top4': 0.9906666874885559, 'top8': 0.996666669845581, 'top16': 0.9977777600288391, 'top32': 0.9993333220481873}
Grouped Top4: {'grouped_n1_top4': 0.9906666874885559, 'grouped_n2_top4': 0.999541699886322, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.02
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_11\byte_11_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_11\byte_11_summary.csv

Loading ASCON byte 12
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_12
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 12 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 01/80 | train_loss=5.4804 | val_loss=5.3844 | lr=1.00e-03 | Top1=0.0091 | Top2=0.0191 | Top4=0.0369 | Top8=0.0693 | Top16=0.1176 | Top32=0.2298

Byte 12 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 02/80 | train_loss=5.1695 | val_loss=4.9952 | lr=1.00e-03 | Top1=0.0178 | Top2=0.0353 | Top4=0.0651 | Top8=0.1202 | Top16=0.2180 | Top32=0.3942

Byte 12 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 03/80 | train_loss=4.6604 | val_loss=4.4080 | lr=1.00e-03 | Top1=0.0307 | Top2=0.0604 | Top4=0.1098 | Top8=0.2056 | Top16=0.3544 | Top32=0.5949

Byte 12 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 04/80 | train_loss=4.2117 | val_loss=4.0383 | lr=1.00e-03 | Top1=0.0482 | Top2=0.0851 | Top4=0.1520 | Top8=0.2800 | Top16=0.4504 | Top32=0.7280

Byte 12 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 05/80 | train_loss=4.0410 | val_loss=3.9664 | lr=1.00e-03 | Top1=0.0509 | Top2=0.0900 | Top4=0.1587 | Top8=0.2962 | Top16=0.4898 | Top32=0.7678

Byte 12 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 06/80 | train_loss=3.9624 | val_loss=3.8394 | lr=1.00e-03 | Top1=0.0576 | Top2=0.1016 | Top4=0.1829 | Top8=0.3404 | Top16=0.5544 | Top32=0.8284

Byte 12 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 07/80 | train_loss=3.8855 | val_loss=3.7673 | lr=1.00e-03 | Top1=0.0589 | Top2=0.1073 | Top4=0.2091 | Top8=0.3709 | Top16=0.5829 | Top32=0.8536

Byte 12 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 08/80 | train_loss=3.8189 | val_loss=3.7387 | lr=1.00e-03 | Top1=0.0624 | Top2=0.1187 | Top4=0.2144 | Top8=0.3824 | Top16=0.6171 | Top32=0.8724

Byte 12 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 09/80 | train_loss=3.7616 | val_loss=3.6837 | lr=1.00e-03 | Top1=0.0693 | Top2=0.1278 | Top4=0.2369 | Top8=0.4044 | Top16=0.6218 | Top32=0.8738

Byte 12 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 10/80 | train_loss=3.6961 | val_loss=3.5958 | lr=1.00e-03 | Top1=0.0869 | Top2=0.1531 | Top4=0.2720 | Top8=0.4456 | Top16=0.6769 | Top32=0.9044

Byte 12 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 11/80 | train_loss=3.6354 | val_loss=3.5349 | lr=1.00e-03 | Top1=0.0880 | Top2=0.1544 | Top4=0.2780 | Top8=0.4613 | Top16=0.6962 | Top32=0.9229

Byte 12 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 12/80 | train_loss=3.5755 | val_loss=3.5272 | lr=1.00e-03 | Top1=0.0976 | Top2=0.1713 | Top4=0.2927 | Top8=0.4704 | Top16=0.6991 | Top32=0.9064

Byte 12 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 13/80 | train_loss=3.5127 | val_loss=3.3776 | lr=1.00e-03 | Top1=0.1093 | Top2=0.1964 | Top4=0.3353 | Top8=0.5356 | Top16=0.7598 | Top32=0.9449

Byte 12 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 14/80 | train_loss=3.4471 | val_loss=3.4936 | lr=1.00e-03 | Top1=0.0947 | Top2=0.1713 | Top4=0.2993 | Top8=0.4969 | Top16=0.7224 | Top32=0.9356

Byte 12 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 15/80 | train_loss=3.3839 | val_loss=3.2608 | lr=1.00e-03 | Top1=0.1282 | Top2=0.2229 | Top4=0.3818 | Top8=0.6033 | Top16=0.8069 | Top32=0.9584

Byte 12 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 16/80 | train_loss=3.3316 | val_loss=3.2594 | lr=1.00e-03 | Top1=0.1307 | Top2=0.2336 | Top4=0.4002 | Top8=0.6047 | Top16=0.8118 | Top32=0.9551

Byte 12 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 17/80 | train_loss=3.2691 | val_loss=3.1597 | lr=1.00e-03 | Top1=0.1511 | Top2=0.2653 | Top4=0.4253 | Top8=0.6304 | Top16=0.8287 | Top32=0.9667

Byte 12 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 18/80 | train_loss=3.2079 | val_loss=3.1236 | lr=1.00e-03 | Top1=0.1540 | Top2=0.2709 | Top4=0.4351 | Top8=0.6584 | Top16=0.8464 | Top32=0.9669

Byte 12 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 19/80 | train_loss=3.1678 | val_loss=3.0672 | lr=1.00e-03 | Top1=0.1578 | Top2=0.2809 | Top4=0.4564 | Top8=0.6622 | Top16=0.8600 | Top32=0.9731

Byte 12 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 20/80 | train_loss=3.1103 | val_loss=3.0489 | lr=1.00e-03 | Top1=0.1711 | Top2=0.2909 | Top4=0.4629 | Top8=0.6751 | Top16=0.8558 | Top32=0.9776

Byte 12 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 21/80 | train_loss=3.0808 | val_loss=3.0788 | lr=1.00e-03 | Top1=0.1707 | Top2=0.2856 | Top4=0.4540 | Top8=0.6593 | Top16=0.8469 | Top32=0.9669

Byte 12 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 22/80 | train_loss=3.0467 | val_loss=2.9952 | lr=1.00e-03 | Top1=0.1802 | Top2=0.3096 | Top4=0.4793 | Top8=0.6920 | Top16=0.8782 | Top32=0.9780

Byte 12 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 23/80 | train_loss=3.0156 | val_loss=3.0072 | lr=1.00e-03 | Top1=0.1858 | Top2=0.3051 | Top4=0.4827 | Top8=0.6913 | Top16=0.8722 | Top32=0.9718

Byte 12 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 24/80 | train_loss=2.9617 | val_loss=3.0076 | lr=1.00e-03 | Top1=0.1687 | Top2=0.2976 | Top4=0.4796 | Top8=0.6871 | Top16=0.8740 | Top32=0.9793

Byte 12 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 25/80 | train_loss=2.9425 | val_loss=3.0190 | lr=1.00e-03 | Top1=0.1724 | Top2=0.2969 | Top4=0.4760 | Top8=0.6904 | Top16=0.8707 | Top32=0.9756

Byte 12 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 26/80 | train_loss=2.9156 | val_loss=2.9071 | lr=1.00e-03 | Top1=0.1958 | Top2=0.3296 | Top4=0.5127 | Top8=0.7313 | Top16=0.9009 | Top32=0.9831

Byte 12 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 27/80 | train_loss=2.8703 | val_loss=2.8793 | lr=1.00e-03 | Top1=0.2040 | Top2=0.3484 | Top4=0.5373 | Top8=0.7324 | Top16=0.8949 | Top32=0.9827

Byte 12 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 28/80 | train_loss=2.8400 | val_loss=2.8747 | lr=1.00e-03 | Top1=0.2129 | Top2=0.3453 | Top4=0.5322 | Top8=0.7389 | Top16=0.8978 | Top32=0.9798

Byte 12 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 29/80 | train_loss=2.8025 | val_loss=2.8863 | lr=1.00e-03 | Top1=0.2127 | Top2=0.3493 | Top4=0.5262 | Top8=0.7338 | Top16=0.8978 | Top32=0.9831

Byte 12 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 30/80 | train_loss=2.7666 | val_loss=2.8117 | lr=1.00e-03 | Top1=0.2291 | Top2=0.3716 | Top4=0.5558 | Top8=0.7529 | Top16=0.9036 | Top32=0.9840

Byte 12 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 31/80 | train_loss=2.7390 | val_loss=2.8191 | lr=1.00e-03 | Top1=0.2251 | Top2=0.3651 | Top4=0.5540 | Top8=0.7536 | Top16=0.9107 | Top32=0.9818

Byte 12 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 32/80 | train_loss=2.7115 | val_loss=2.8401 | lr=1.00e-03 | Top1=0.2260 | Top2=0.3660 | Top4=0.5540 | Top8=0.7480 | Top16=0.9042 | Top32=0.9796

Byte 12 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 33/80 | train_loss=2.6904 | val_loss=2.8761 | lr=1.00e-03 | Top1=0.2140 | Top2=0.3573 | Top4=0.5436 | Top8=0.7409 | Top16=0.9053 | Top32=0.9811

Byte 12 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 34/80 | train_loss=2.6590 | val_loss=2.8005 | lr=1.00e-03 | Top1=0.2364 | Top2=0.3824 | Top4=0.5769 | Top8=0.7596 | Top16=0.9109 | Top32=0.9813

Byte 12 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 35/80 | train_loss=2.6129 | val_loss=2.7897 | lr=1.00e-03 | Top1=0.2222 | Top2=0.3782 | Top4=0.5704 | Top8=0.7631 | Top16=0.9133 | Top32=0.9851

Byte 12 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 36/80 | train_loss=2.5953 | val_loss=2.8215 | lr=1.00e-03 | Top1=0.2260 | Top2=0.3744 | Top4=0.5624 | Top8=0.7584 | Top16=0.9087 | Top32=0.9836

Byte 12 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 37/80 | train_loss=2.5781 | val_loss=2.7625 | lr=1.00e-03 | Top1=0.2458 | Top2=0.3933 | Top4=0.5876 | Top8=0.7773 | Top16=0.9142 | Top32=0.9844

Byte 12 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 38/80 | train_loss=2.5269 | val_loss=2.7490 | lr=1.00e-03 | Top1=0.2451 | Top2=0.3942 | Top4=0.5847 | Top8=0.7836 | Top16=0.9218 | Top32=0.9858

Byte 12 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 39/80 | train_loss=2.4794 | val_loss=2.7097 | lr=1.00e-03 | Top1=0.2582 | Top2=0.4133 | Top4=0.5987 | Top8=0.7867 | Top16=0.9213 | Top32=0.9880

Byte 12 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 40/80 | train_loss=2.4354 | val_loss=2.6331 | lr=1.00e-03 | Top1=0.2771 | Top2=0.4367 | Top4=0.6338 | Top8=0.8073 | Top16=0.9293 | Top32=0.9880

Byte 12 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 41/80 | train_loss=2.4118 | val_loss=2.7225 | lr=1.00e-03 | Top1=0.2567 | Top2=0.4196 | Top4=0.6031 | Top8=0.7911 | Top16=0.9238 | Top32=0.9858

Byte 12 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 42/80 | train_loss=2.3782 | val_loss=2.6606 | lr=1.00e-03 | Top1=0.2811 | Top2=0.4329 | Top4=0.6200 | Top8=0.7913 | Top16=0.9336 | Top32=0.9902

Byte 12 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 43/80 | train_loss=2.3547 | val_loss=2.7374 | lr=1.00e-03 | Top1=0.2656 | Top2=0.4149 | Top4=0.6013 | Top8=0.7818 | Top16=0.9216 | Top32=0.9878

Byte 12 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 44/80 | train_loss=2.3261 | val_loss=2.5961 | lr=1.00e-03 | Top1=0.2889 | Top2=0.4556 | Top4=0.6433 | Top8=0.8184 | Top16=0.9331 | Top32=0.9878

Byte 12 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 45/80 | train_loss=2.2866 | val_loss=2.6179 | lr=1.00e-03 | Top1=0.2844 | Top2=0.4498 | Top4=0.6444 | Top8=0.8202 | Top16=0.9367 | Top32=0.9896

Byte 12 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 46/80 | train_loss=2.2430 | val_loss=2.6147 | lr=1.00e-03 | Top1=0.2887 | Top2=0.4547 | Top4=0.6544 | Top8=0.8251 | Top16=0.9422 | Top32=0.9907

Byte 12 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 47/80 | train_loss=2.2035 | val_loss=2.5816 | lr=1.00e-03 | Top1=0.2909 | Top2=0.4556 | Top4=0.6476 | Top8=0.8191 | Top16=0.9402 | Top32=0.9898

Byte 12 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 48/80 | train_loss=2.1678 | val_loss=2.5609 | lr=1.00e-03 | Top1=0.3073 | Top2=0.4778 | Top4=0.6611 | Top8=0.8269 | Top16=0.9418 | Top32=0.9878

Byte 12 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 49/80 | train_loss=2.1288 | val_loss=2.6322 | lr=1.00e-03 | Top1=0.2956 | Top2=0.4576 | Top4=0.6482 | Top8=0.8191 | Top16=0.9413 | Top32=0.9889

Byte 12 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 50/80 | train_loss=2.0918 | val_loss=2.5477 | lr=1.00e-03 | Top1=0.3149 | Top2=0.4898 | Top4=0.6744 | Top8=0.8302 | Top16=0.9404 | Top32=0.9913

Byte 12 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 51/80 | train_loss=2.0739 | val_loss=2.5030 | lr=1.00e-03 | Top1=0.3122 | Top2=0.4916 | Top4=0.6709 | Top8=0.8473 | Top16=0.9516 | Top32=0.9916

Byte 12 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 52/80 | train_loss=2.0273 | val_loss=2.5403 | lr=1.00e-03 | Top1=0.3073 | Top2=0.4918 | Top4=0.6793 | Top8=0.8447 | Top16=0.9500 | Top32=0.9898

Byte 12 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 53/80 | train_loss=1.9820 | val_loss=2.5211 | lr=1.00e-03 | Top1=0.3202 | Top2=0.4922 | Top4=0.6829 | Top8=0.8382 | Top16=0.9489 | Top32=0.9893

Byte 12 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 54/80 | train_loss=1.9768 | val_loss=2.5144 | lr=1.00e-03 | Top1=0.3218 | Top2=0.4989 | Top4=0.6873 | Top8=0.8460 | Top16=0.9509 | Top32=0.9911

Byte 12 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 55/80 | train_loss=1.9363 | val_loss=2.5003 | lr=1.00e-03 | Top1=0.3280 | Top2=0.5076 | Top4=0.7031 | Top8=0.8518 | Top16=0.9507 | Top32=0.9924

Byte 12 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 56/80 | train_loss=1.9231 | val_loss=2.4907 | lr=1.00e-03 | Top1=0.3282 | Top2=0.5133 | Top4=0.6918 | Top8=0.8538 | Top16=0.9516 | Top32=0.9900

Byte 12 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 57/80 | train_loss=1.8859 | val_loss=2.5071 | lr=1.00e-03 | Top1=0.3309 | Top2=0.5084 | Top4=0.6964 | Top8=0.8609 | Top16=0.9547 | Top32=0.9933

Byte 12 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 58/80 | train_loss=1.8468 | val_loss=2.5075 | lr=1.00e-03 | Top1=0.3347 | Top2=0.5136 | Top4=0.6913 | Top8=0.8509 | Top16=0.9516 | Top32=0.9916

Byte 12 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 59/80 | train_loss=1.8158 | val_loss=2.5505 | lr=1.00e-03 | Top1=0.3367 | Top2=0.5096 | Top4=0.6836 | Top8=0.8480 | Top16=0.9529 | Top32=0.9878

Byte 12 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 60/80 | train_loss=1.7930 | val_loss=2.6304 | lr=1.00e-03 | Top1=0.3238 | Top2=0.4962 | Top4=0.6784 | Top8=0.8476 | Top16=0.9493 | Top32=0.9880

Byte 12 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 61/80 | train_loss=1.7725 | val_loss=2.4862 | lr=1.00e-03 | Top1=0.3420 | Top2=0.5238 | Top4=0.7042 | Top8=0.8689 | Top16=0.9538 | Top32=0.9878

Byte 12 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 62/80 | train_loss=1.7305 | val_loss=2.5002 | lr=1.00e-03 | Top1=0.3420 | Top2=0.5222 | Top4=0.6993 | Top8=0.8587 | Top16=0.9582 | Top32=0.9916

Byte 12 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 63/80 | train_loss=1.7160 | val_loss=2.5424 | lr=1.00e-03 | Top1=0.3380 | Top2=0.5216 | Top4=0.6960 | Top8=0.8616 | Top16=0.9524 | Top32=0.9904

Byte 12 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 64/80 | train_loss=1.6972 | val_loss=2.5772 | lr=1.00e-03 | Top1=0.3304 | Top2=0.5060 | Top4=0.6944 | Top8=0.8524 | Top16=0.9502 | Top32=0.9867

Byte 12 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 65/80 | train_loss=1.6638 | val_loss=2.5199 | lr=1.00e-03 | Top1=0.3440 | Top2=0.5242 | Top4=0.7109 | Top8=0.8649 | Top16=0.9544 | Top32=0.9916

Byte 12 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 66/80 | train_loss=1.6163 | val_loss=2.5876 | lr=1.00e-03 | Top1=0.3464 | Top2=0.5184 | Top4=0.7031 | Top8=0.8564 | Top16=0.9524 | Top32=0.9884

Byte 12 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 67/80 | train_loss=1.6230 | val_loss=2.5613 | lr=1.00e-03 | Top1=0.3342 | Top2=0.5056 | Top4=0.6942 | Top8=0.8544 | Top16=0.9500 | Top32=0.9880

Byte 12 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 68/80 | train_loss=1.5990 | val_loss=2.6497 | lr=1.00e-03 | Top1=0.3362 | Top2=0.5100 | Top4=0.6976 | Top8=0.8507 | Top16=0.9469 | Top32=0.9869

Byte 12 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 69/80 | train_loss=1.5768 | val_loss=2.5470 | lr=1.00e-03 | Top1=0.3391 | Top2=0.5109 | Top4=0.6969 | Top8=0.8569 | Top16=0.9453 | Top32=0.9884

Byte 12 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 70/80 | train_loss=1.5376 | val_loss=2.5819 | lr=1.00e-03 | Top1=0.3462 | Top2=0.5213 | Top4=0.6989 | Top8=0.8611 | Top16=0.9520 | Top32=0.9887

Byte 12 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 71/80 | train_loss=1.5279 | val_loss=2.6050 | lr=1.00e-03 | Top1=0.3444 | Top2=0.5180 | Top4=0.7007 | Top8=0.8582 | Top16=0.9504 | Top32=0.9867

Byte 12 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 72/80 | train_loss=1.3447 | val_loss=2.5804 | lr=5.00e-04 | Top1=0.3618 | Top2=0.5607 | Top4=0.7269 | Top8=0.8753 | Top16=0.9542 | Top32=0.9838

Byte 12 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 73/80 | train_loss=1.2799 | val_loss=2.5635 | lr=5.00e-04 | Top1=0.3589 | Top2=0.5331 | Top4=0.7147 | Top8=0.8711 | Top16=0.9598 | Top32=0.9902

Byte 12 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 74/80 | train_loss=1.2604 | val_loss=2.5464 | lr=5.00e-04 | Top1=0.3620 | Top2=0.5478 | Top4=0.7284 | Top8=0.8760 | Top16=0.9571 | Top32=0.9864

Byte 12 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 75/80 | train_loss=1.2415 | val_loss=2.6234 | lr=5.00e-04 | Top1=0.3591 | Top2=0.5429 | Top4=0.7184 | Top8=0.8740 | Top16=0.9540 | Top32=0.9838

Byte 12 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 76/80 | train_loss=1.2194 | val_loss=2.6215 | lr=5.00e-04 | Top1=0.3687 | Top2=0.5529 | Top4=0.7189 | Top8=0.8680 | Top16=0.9560 | Top32=0.9853

Byte 12 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 77/80 | train_loss=1.2017 | val_loss=2.5730 | lr=5.00e-04 | Top1=0.3604 | Top2=0.5469 | Top4=0.7284 | Top8=0.8856 | Top16=0.9593 | Top32=0.9871

Byte 12 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 78/80 | train_loss=1.1855 | val_loss=2.6136 | lr=5.00e-04 | Top1=0.3693 | Top2=0.5491 | Top4=0.7269 | Top8=0.8729 | Top16=0.9544 | Top32=0.9840

Byte 12 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 79/80 | train_loss=1.1750 | val_loss=2.5769 | lr=5.00e-04 | Top1=0.3753 | Top2=0.5536 | Top4=0.7304 | Top8=0.8747 | Top16=0.9562 | Top32=0.9847

Byte 12 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 12 | Epoch 80/80 | train_loss=1.1470 | val_loss=2.5889 | lr=5.00e-04 | Top1=0.3702 | Top2=0.5458 | Top4=0.7247 | Top8=0.8787 | Top16=0.9542 | Top32=0.9838

Finished ASCON byte 12
Best epoch: 79
Test Top-k: {'top1': 0.3880000114440918, 'top2': 0.5631111264228821, 'top4': 0.7371110916137695, 'top8': 0.8775555491447449, 'top16': 0.9535555839538574, 'top32': 0.9871110916137695}
Grouped Top4: {'grouped_n1_top4': 0.7371110916137695, 'grouped_n2_top4': 0.885478675365448, 'grouped_n4_top4': 0.9717073440551758, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.02
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_12\byte_12_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_12\byte_12_summary.csv

Loading ASCON byte 13
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_13
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 13 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 01/80 | train_loss=5.4702 | val_loss=5.3316 | lr=1.00e-03 | Top1=0.0104 | Top2=0.0198 | Top4=0.0371 | Top8=0.0740 | Top16=0.1396 | Top32=0.2502

Byte 13 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 02/80 | train_loss=5.1038 | val_loss=4.7510 | lr=1.00e-03 | Top1=0.0240 | Top2=0.0433 | Top4=0.0804 | Top8=0.1520 | Top16=0.2822 | Top32=0.5111

Byte 13 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 03/80 | train_loss=4.4038 | val_loss=4.1498 | lr=1.00e-03 | Top1=0.0376 | Top2=0.0649 | Top4=0.1242 | Top8=0.2411 | Top16=0.4131 | Top32=0.6844

Byte 13 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 04/80 | train_loss=4.1242 | val_loss=3.9780 | lr=1.00e-03 | Top1=0.0427 | Top2=0.0824 | Top4=0.1524 | Top8=0.2996 | Top16=0.4816 | Top32=0.7593

Byte 13 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 05/80 | train_loss=4.0150 | val_loss=3.9324 | lr=1.00e-03 | Top1=0.0449 | Top2=0.0820 | Top4=0.1593 | Top8=0.2971 | Top16=0.5007 | Top32=0.7720

Byte 13 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 06/80 | train_loss=3.9527 | val_loss=3.9156 | lr=1.00e-03 | Top1=0.0453 | Top2=0.0862 | Top4=0.1669 | Top8=0.3013 | Top16=0.5087 | Top32=0.7949

Byte 13 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 07/80 | train_loss=3.9079 | val_loss=3.8703 | lr=1.00e-03 | Top1=0.0556 | Top2=0.0964 | Top4=0.1804 | Top8=0.3276 | Top16=0.5347 | Top32=0.8076

Byte 13 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 08/80 | train_loss=3.8401 | val_loss=3.7366 | lr=1.00e-03 | Top1=0.0582 | Top2=0.1184 | Top4=0.2124 | Top8=0.3827 | Top16=0.5989 | Top32=0.8660

Byte 13 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 09/80 | train_loss=3.7933 | val_loss=3.7416 | lr=1.00e-03 | Top1=0.0616 | Top2=0.1118 | Top4=0.2040 | Top8=0.3747 | Top16=0.5938 | Top32=0.8631

Byte 13 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 10/80 | train_loss=3.7602 | val_loss=3.6918 | lr=1.00e-03 | Top1=0.0613 | Top2=0.1140 | Top4=0.2276 | Top8=0.3993 | Top16=0.6224 | Top32=0.8678

Byte 13 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 11/80 | train_loss=3.7124 | val_loss=3.6385 | lr=1.00e-03 | Top1=0.0693 | Top2=0.1333 | Top4=0.2384 | Top8=0.4109 | Top16=0.6493 | Top32=0.8882

Byte 13 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 12/80 | train_loss=3.6592 | val_loss=3.6000 | lr=1.00e-03 | Top1=0.0798 | Top2=0.1380 | Top4=0.2529 | Top8=0.4387 | Top16=0.6642 | Top32=0.9000

Byte 13 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 13/80 | train_loss=3.6201 | val_loss=3.5719 | lr=1.00e-03 | Top1=0.0813 | Top2=0.1476 | Top4=0.2671 | Top8=0.4500 | Top16=0.6907 | Top32=0.9269

Byte 13 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 14/80 | train_loss=3.5522 | val_loss=3.5013 | lr=1.00e-03 | Top1=0.0971 | Top2=0.1709 | Top4=0.3067 | Top8=0.4996 | Top16=0.7184 | Top32=0.9233

Byte 13 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 15/80 | train_loss=3.4952 | val_loss=3.4153 | lr=1.00e-03 | Top1=0.1131 | Top2=0.1913 | Top4=0.3320 | Top8=0.5238 | Top16=0.7533 | Top32=0.9396

Byte 13 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 16/80 | train_loss=3.4212 | val_loss=3.3784 | lr=1.00e-03 | Top1=0.1140 | Top2=0.1996 | Top4=0.3451 | Top8=0.5438 | Top16=0.7738 | Top32=0.9482

Byte 13 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 17/80 | train_loss=3.3798 | val_loss=3.3175 | lr=1.00e-03 | Top1=0.1296 | Top2=0.2218 | Top4=0.3773 | Top8=0.5878 | Top16=0.7864 | Top32=0.9453

Byte 13 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 18/80 | train_loss=3.3026 | val_loss=3.1592 | lr=1.00e-03 | Top1=0.1569 | Top2=0.2640 | Top4=0.4247 | Top8=0.6338 | Top16=0.8387 | Top32=0.9720

Byte 13 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 19/80 | train_loss=3.2271 | val_loss=3.1361 | lr=1.00e-03 | Top1=0.1558 | Top2=0.2707 | Top4=0.4380 | Top8=0.6482 | Top16=0.8489 | Top32=0.9758

Byte 13 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 20/80 | train_loss=3.1421 | val_loss=3.0474 | lr=1.00e-03 | Top1=0.1784 | Top2=0.2993 | Top4=0.4847 | Top8=0.6998 | Top16=0.8740 | Top32=0.9724

Byte 13 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 21/80 | train_loss=3.0220 | val_loss=2.8955 | lr=1.00e-03 | Top1=0.2020 | Top2=0.3420 | Top4=0.5329 | Top8=0.7507 | Top16=0.9122 | Top32=0.9898

Byte 13 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 22/80 | train_loss=2.8965 | val_loss=2.8095 | lr=1.00e-03 | Top1=0.2242 | Top2=0.3716 | Top4=0.5611 | Top8=0.7724 | Top16=0.9258 | Top32=0.9931

Byte 13 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 23/80 | train_loss=2.7987 | val_loss=2.7270 | lr=1.00e-03 | Top1=0.2304 | Top2=0.3860 | Top4=0.5873 | Top8=0.7942 | Top16=0.9371 | Top32=0.9942

Byte 13 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 24/80 | train_loss=2.7023 | val_loss=2.6108 | lr=1.00e-03 | Top1=0.2551 | Top2=0.4204 | Top4=0.6222 | Top8=0.8293 | Top16=0.9558 | Top32=0.9969

Byte 13 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 25/80 | train_loss=2.6350 | val_loss=2.5341 | lr=1.00e-03 | Top1=0.2820 | Top2=0.4544 | Top4=0.6642 | Top8=0.8536 | Top16=0.9642 | Top32=0.9967

Byte 13 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 26/80 | train_loss=2.5748 | val_loss=2.5417 | lr=1.00e-03 | Top1=0.2804 | Top2=0.4402 | Top4=0.6451 | Top8=0.8496 | Top16=0.9656 | Top32=0.9969

Byte 13 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 27/80 | train_loss=2.5006 | val_loss=2.4443 | lr=1.00e-03 | Top1=0.2998 | Top2=0.4747 | Top4=0.6829 | Top8=0.8696 | Top16=0.9720 | Top32=0.9973

Byte 13 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 28/80 | train_loss=2.4450 | val_loss=2.4219 | lr=1.00e-03 | Top1=0.3169 | Top2=0.4913 | Top4=0.6980 | Top8=0.8716 | Top16=0.9664 | Top32=0.9982

Byte 13 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 29/80 | train_loss=2.4112 | val_loss=2.3217 | lr=1.00e-03 | Top1=0.3436 | Top2=0.5336 | Top4=0.7318 | Top8=0.8964 | Top16=0.9802 | Top32=0.9993

Byte 13 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 30/80 | train_loss=2.3322 | val_loss=2.2915 | lr=1.00e-03 | Top1=0.3531 | Top2=0.5320 | Top4=0.7342 | Top8=0.8989 | Top16=0.9818 | Top32=0.9987

Byte 13 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 31/80 | train_loss=2.2843 | val_loss=2.2622 | lr=1.00e-03 | Top1=0.3604 | Top2=0.5409 | Top4=0.7440 | Top8=0.9044 | Top16=0.9838 | Top32=0.9993

Byte 13 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 32/80 | train_loss=2.2287 | val_loss=2.2321 | lr=1.00e-03 | Top1=0.3624 | Top2=0.5640 | Top4=0.7587 | Top8=0.9122 | Top16=0.9813 | Top32=0.9984

Byte 13 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 33/80 | train_loss=2.1892 | val_loss=2.1656 | lr=1.00e-03 | Top1=0.3920 | Top2=0.5813 | Top4=0.7713 | Top8=0.9184 | Top16=0.9873 | Top32=0.9989

Byte 13 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 34/80 | train_loss=2.1263 | val_loss=2.1013 | lr=1.00e-03 | Top1=0.4100 | Top2=0.6129 | Top4=0.7960 | Top8=0.9298 | Top16=0.9884 | Top32=0.9989

Byte 13 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 35/80 | train_loss=2.0680 | val_loss=2.2947 | lr=1.00e-03 | Top1=0.3540 | Top2=0.5376 | Top4=0.7336 | Top8=0.8980 | Top16=0.9793 | Top32=0.9982

Byte 13 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 36/80 | train_loss=2.0106 | val_loss=2.2279 | lr=1.00e-03 | Top1=0.3740 | Top2=0.5538 | Top4=0.7589 | Top8=0.9087 | Top16=0.9811 | Top32=0.9984

Byte 13 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 37/80 | train_loss=1.9656 | val_loss=2.0940 | lr=1.00e-03 | Top1=0.4009 | Top2=0.6080 | Top4=0.7947 | Top8=0.9316 | Top16=0.9878 | Top32=0.9984

Byte 13 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 38/80 | train_loss=1.9240 | val_loss=2.0325 | lr=1.00e-03 | Top1=0.4236 | Top2=0.6224 | Top4=0.8058 | Top8=0.9360 | Top16=0.9916 | Top32=0.9993

Byte 13 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 39/80 | train_loss=1.8472 | val_loss=1.9430 | lr=1.00e-03 | Top1=0.4591 | Top2=0.6522 | Top4=0.8329 | Top8=0.9522 | Top16=0.9931 | Top32=0.9991

Byte 13 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 40/80 | train_loss=1.8165 | val_loss=1.8971 | lr=1.00e-03 | Top1=0.4700 | Top2=0.6758 | Top4=0.8493 | Top8=0.9549 | Top16=0.9916 | Top32=0.9991

Byte 13 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 41/80 | train_loss=1.7558 | val_loss=1.9121 | lr=1.00e-03 | Top1=0.4753 | Top2=0.6680 | Top4=0.8427 | Top8=0.9504 | Top16=0.9896 | Top32=0.9987

Byte 13 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 42/80 | train_loss=1.7163 | val_loss=1.9196 | lr=1.00e-03 | Top1=0.4669 | Top2=0.6651 | Top4=0.8411 | Top8=0.9504 | Top16=0.9902 | Top32=0.9984

Byte 13 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 43/80 | train_loss=1.6807 | val_loss=1.8730 | lr=1.00e-03 | Top1=0.4829 | Top2=0.6702 | Top4=0.8424 | Top8=0.9567 | Top16=0.9938 | Top32=0.9993

Byte 13 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 44/80 | train_loss=1.6381 | val_loss=1.8955 | lr=1.00e-03 | Top1=0.4780 | Top2=0.6711 | Top4=0.8411 | Top8=0.9533 | Top16=0.9911 | Top32=0.9984

Byte 13 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 45/80 | train_loss=1.6017 | val_loss=1.8672 | lr=1.00e-03 | Top1=0.4853 | Top2=0.6784 | Top4=0.8536 | Top8=0.9562 | Top16=0.9938 | Top32=0.9984

Byte 13 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 46/80 | train_loss=1.5540 | val_loss=1.8232 | lr=1.00e-03 | Top1=0.5018 | Top2=0.7000 | Top4=0.8631 | Top8=0.9600 | Top16=0.9922 | Top32=0.9982

Byte 13 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 47/80 | train_loss=1.5238 | val_loss=1.9052 | lr=1.00e-03 | Top1=0.4773 | Top2=0.6842 | Top4=0.8582 | Top8=0.9529 | Top16=0.9891 | Top32=0.9973

Byte 13 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 48/80 | train_loss=1.4824 | val_loss=1.8816 | lr=1.00e-03 | Top1=0.4967 | Top2=0.6967 | Top4=0.8560 | Top8=0.9533 | Top16=0.9900 | Top32=0.9973

Byte 13 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 49/80 | train_loss=1.4591 | val_loss=1.7896 | lr=1.00e-03 | Top1=0.5098 | Top2=0.7144 | Top4=0.8716 | Top8=0.9664 | Top16=0.9951 | Top32=0.9991

Byte 13 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 50/80 | train_loss=1.4278 | val_loss=1.7523 | lr=1.00e-03 | Top1=0.5253 | Top2=0.7156 | Top4=0.8736 | Top8=0.9664 | Top16=0.9942 | Top32=0.9978

Byte 13 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 51/80 | train_loss=1.3843 | val_loss=1.6901 | lr=1.00e-03 | Top1=0.5404 | Top2=0.7353 | Top4=0.8933 | Top8=0.9711 | Top16=0.9960 | Top32=0.9998

Byte 13 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 52/80 | train_loss=1.3604 | val_loss=1.9304 | lr=1.00e-03 | Top1=0.5024 | Top2=0.6916 | Top4=0.8527 | Top8=0.9498 | Top16=0.9842 | Top32=0.9938

Byte 13 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 53/80 | train_loss=1.3371 | val_loss=1.7682 | lr=1.00e-03 | Top1=0.5222 | Top2=0.7220 | Top4=0.8800 | Top8=0.9656 | Top16=0.9942 | Top32=0.9991

Byte 13 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 54/80 | train_loss=1.3091 | val_loss=1.8485 | lr=1.00e-03 | Top1=0.5202 | Top2=0.7151 | Top4=0.8640 | Top8=0.9582 | Top16=0.9853 | Top32=0.9922

Byte 13 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 55/80 | train_loss=1.2701 | val_loss=1.6829 | lr=1.00e-03 | Top1=0.5569 | Top2=0.7478 | Top4=0.8976 | Top8=0.9687 | Top16=0.9918 | Top32=0.9982

Byte 13 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 56/80 | train_loss=1.2385 | val_loss=1.6565 | lr=1.00e-03 | Top1=0.5584 | Top2=0.7533 | Top4=0.9036 | Top8=0.9724 | Top16=0.9931 | Top32=0.9989

Byte 13 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 57/80 | train_loss=1.2151 | val_loss=1.7141 | lr=1.00e-03 | Top1=0.5529 | Top2=0.7420 | Top4=0.8871 | Top8=0.9691 | Top16=0.9907 | Top32=0.9962

Byte 13 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 58/80 | train_loss=1.1921 | val_loss=1.7314 | lr=1.00e-03 | Top1=0.5531 | Top2=0.7433 | Top4=0.8944 | Top8=0.9718 | Top16=0.9920 | Top32=0.9953

Byte 13 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 59/80 | train_loss=1.1622 | val_loss=1.8070 | lr=1.00e-03 | Top1=0.5489 | Top2=0.7333 | Top4=0.8820 | Top8=0.9562 | Top16=0.9807 | Top32=0.9889

Byte 13 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 60/80 | train_loss=1.1284 | val_loss=1.7087 | lr=1.00e-03 | Top1=0.5622 | Top2=0.7482 | Top4=0.8962 | Top8=0.9702 | Top16=0.9916 | Top32=0.9962

Byte 13 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 61/80 | train_loss=1.1200 | val_loss=1.6627 | lr=1.00e-03 | Top1=0.5667 | Top2=0.7640 | Top4=0.9058 | Top8=0.9731 | Top16=0.9933 | Top32=0.9976

Byte 13 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 62/80 | train_loss=1.1074 | val_loss=1.7877 | lr=1.00e-03 | Top1=0.5573 | Top2=0.7404 | Top4=0.8871 | Top8=0.9662 | Top16=0.9871 | Top32=0.9922

Byte 13 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 63/80 | train_loss=1.0797 | val_loss=1.7176 | lr=1.00e-03 | Top1=0.5642 | Top2=0.7540 | Top4=0.8960 | Top8=0.9669 | Top16=0.9902 | Top32=0.9964

Byte 13 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 64/80 | train_loss=1.0509 | val_loss=1.7834 | lr=1.00e-03 | Top1=0.5529 | Top2=0.7389 | Top4=0.8876 | Top8=0.9616 | Top16=0.9864 | Top32=0.9933

Byte 13 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 65/80 | train_loss=1.0495 | val_loss=1.7126 | lr=1.00e-03 | Top1=0.5733 | Top2=0.7562 | Top4=0.8978 | Top8=0.9640 | Top16=0.9876 | Top32=0.9924

Byte 13 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 66/80 | train_loss=1.0237 | val_loss=1.5860 | lr=1.00e-03 | Top1=0.5809 | Top2=0.7782 | Top4=0.9129 | Top8=0.9747 | Top16=0.9956 | Top32=0.9982

Byte 13 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 67/80 | train_loss=0.9982 | val_loss=1.5827 | lr=1.00e-03 | Top1=0.5918 | Top2=0.7818 | Top4=0.9233 | Top8=0.9771 | Top16=0.9947 | Top32=0.9982

Byte 13 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 68/80 | train_loss=0.9928 | val_loss=1.6715 | lr=1.00e-03 | Top1=0.5876 | Top2=0.7747 | Top4=0.9084 | Top8=0.9696 | Top16=0.9893 | Top32=0.9953

Byte 13 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 69/80 | train_loss=0.9615 | val_loss=1.6030 | lr=1.00e-03 | Top1=0.5882 | Top2=0.7840 | Top4=0.9184 | Top8=0.9787 | Top16=0.9922 | Top32=0.9964

Byte 13 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 70/80 | train_loss=0.9613 | val_loss=1.6637 | lr=1.00e-03 | Top1=0.5736 | Top2=0.7698 | Top4=0.9051 | Top8=0.9700 | Top16=0.9907 | Top32=0.9942

Byte 13 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 71/80 | train_loss=0.9357 | val_loss=1.6642 | lr=1.00e-03 | Top1=0.5947 | Top2=0.7849 | Top4=0.9067 | Top8=0.9687 | Top16=0.9871 | Top32=0.9931

Byte 13 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 72/80 | train_loss=0.9129 | val_loss=1.6079 | lr=1.00e-03 | Top1=0.5893 | Top2=0.7822 | Top4=0.9187 | Top8=0.9769 | Top16=0.9936 | Top32=0.9967

Byte 13 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 73/80 | train_loss=0.9141 | val_loss=1.6708 | lr=1.00e-03 | Top1=0.5691 | Top2=0.7544 | Top4=0.9116 | Top8=0.9787 | Top16=0.9960 | Top32=0.9987

Byte 13 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 74/80 | train_loss=0.7850 | val_loss=1.5269 | lr=5.00e-04 | Top1=0.6209 | Top2=0.8069 | Top4=0.9258 | Top8=0.9789 | Top16=0.9940 | Top32=0.9960

Byte 13 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 75/80 | train_loss=0.7503 | val_loss=1.5268 | lr=5.00e-04 | Top1=0.6247 | Top2=0.8104 | Top4=0.9284 | Top8=0.9762 | Top16=0.9902 | Top32=0.9938

Byte 13 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 76/80 | train_loss=0.7275 | val_loss=1.5570 | lr=5.00e-04 | Top1=0.6249 | Top2=0.8093 | Top4=0.9278 | Top8=0.9780 | Top16=0.9913 | Top32=0.9951

Byte 13 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 77/80 | train_loss=0.7054 | val_loss=1.5641 | lr=5.00e-04 | Top1=0.6278 | Top2=0.8089 | Top4=0.9300 | Top8=0.9773 | Top16=0.9913 | Top32=0.9951

Byte 13 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 78/80 | train_loss=0.6991 | val_loss=1.7490 | lr=5.00e-04 | Top1=0.5984 | Top2=0.7780 | Top4=0.8998 | Top8=0.9578 | Top16=0.9791 | Top32=0.9856

Byte 13 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 79/80 | train_loss=0.6926 | val_loss=1.6405 | lr=5.00e-04 | Top1=0.6144 | Top2=0.7907 | Top4=0.9160 | Top8=0.9718 | Top16=0.9867 | Top32=0.9900

Byte 13 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 13 | Epoch 80/80 | train_loss=0.6789 | val_loss=1.6829 | lr=5.00e-04 | Top1=0.6198 | Top2=0.7893 | Top4=0.9127 | Top8=0.9658 | Top16=0.9816 | Top32=0.9871

Finished ASCON byte 13
Best epoch: 77
Test Top-k: {'top1': 0.6322222352027893, 'top2': 0.8059999942779541, 'top4': 0.9306666851043701, 'top8': 0.9811111092567444, 'top16': 0.9944444298744202, 'top32': 0.9959999918937683}
Grouped Top4: {'grouped_n1_top4': 0.9306666851043701, 'grouped_n2_top4': 0.9848970174789429, 'grouped_n4_top4': 0.9990319609642029, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.04
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_13\byte_13_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_13\byte_13_summary.csv

Loading ASCON byte 14
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_14
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 14 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 01/80 | train_loss=5.3777 | val_loss=5.0781 | lr=1.00e-03 | Top1=0.0133 | Top2=0.0278 | Top4=0.0516 | Top8=0.1071 | Top16=0.1940 | Top32=0.3409

Byte 14 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 02/80 | train_loss=4.7631 | val_loss=4.2284 | lr=1.00e-03 | Top1=0.0318 | Top2=0.0651 | Top4=0.1189 | Top8=0.2242 | Top16=0.3896 | Top32=0.6647

Byte 14 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 03/80 | train_loss=4.1652 | val_loss=4.0010 | lr=1.00e-03 | Top1=0.0469 | Top2=0.0833 | Top4=0.1524 | Top8=0.2724 | Top16=0.4598 | Top32=0.7264

Byte 14 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 04/80 | train_loss=4.0237 | val_loss=3.9645 | lr=1.00e-03 | Top1=0.0429 | Top2=0.0829 | Top4=0.1602 | Top8=0.2916 | Top16=0.4818 | Top32=0.7493

Byte 14 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 05/80 | train_loss=3.9384 | val_loss=3.9418 | lr=1.00e-03 | Top1=0.0447 | Top2=0.0838 | Top4=0.1633 | Top8=0.3044 | Top16=0.5171 | Top32=0.7940

Byte 14 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 06/80 | train_loss=3.8686 | val_loss=3.8458 | lr=1.00e-03 | Top1=0.0496 | Top2=0.0938 | Top4=0.1789 | Top8=0.3322 | Top16=0.5507 | Top32=0.8273

Byte 14 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 07/80 | train_loss=3.8257 | val_loss=3.8264 | lr=1.00e-03 | Top1=0.0573 | Top2=0.1009 | Top4=0.1889 | Top8=0.3467 | Top16=0.5589 | Top32=0.8380

Byte 14 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 08/80 | train_loss=3.7666 | val_loss=3.8367 | lr=1.00e-03 | Top1=0.0524 | Top2=0.1016 | Top4=0.1849 | Top8=0.3536 | Top16=0.5809 | Top32=0.8847

Byte 14 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 09/80 | train_loss=3.7273 | val_loss=3.6981 | lr=1.00e-03 | Top1=0.0682 | Top2=0.1184 | Top4=0.2140 | Top8=0.3858 | Top16=0.6120 | Top32=0.8722

Byte 14 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 10/80 | train_loss=3.6844 | val_loss=3.7206 | lr=1.00e-03 | Top1=0.0620 | Top2=0.1176 | Top4=0.2204 | Top8=0.3971 | Top16=0.6351 | Top32=0.8918

Byte 14 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 11/80 | train_loss=3.6226 | val_loss=3.7131 | lr=1.00e-03 | Top1=0.0711 | Top2=0.1236 | Top4=0.2360 | Top8=0.4129 | Top16=0.6404 | Top32=0.8953

Byte 14 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 12/80 | train_loss=3.5761 | val_loss=3.5889 | lr=1.00e-03 | Top1=0.0807 | Top2=0.1416 | Top4=0.2609 | Top8=0.4587 | Top16=0.6902 | Top32=0.9211

Byte 14 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 13/80 | train_loss=3.4982 | val_loss=3.5280 | lr=1.00e-03 | Top1=0.1016 | Top2=0.1782 | Top4=0.3027 | Top8=0.4933 | Top16=0.7178 | Top32=0.9164

Byte 14 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 14/80 | train_loss=3.4425 | val_loss=3.3706 | lr=1.00e-03 | Top1=0.1160 | Top2=0.2004 | Top4=0.3442 | Top8=0.5547 | Top16=0.7742 | Top32=0.9484

Byte 14 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 15/80 | train_loss=3.3709 | val_loss=3.4316 | lr=1.00e-03 | Top1=0.1027 | Top2=0.1927 | Top4=0.3360 | Top8=0.5460 | Top16=0.7640 | Top32=0.9347

Byte 14 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 16/80 | train_loss=3.3121 | val_loss=3.3448 | lr=1.00e-03 | Top1=0.1196 | Top2=0.2180 | Top4=0.3618 | Top8=0.5647 | Top16=0.7909 | Top32=0.9484

Byte 14 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 17/80 | train_loss=3.2360 | val_loss=3.2686 | lr=1.00e-03 | Top1=0.1378 | Top2=0.2424 | Top4=0.4089 | Top8=0.6156 | Top16=0.8189 | Top32=0.9562

Byte 14 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 18/80 | train_loss=3.1766 | val_loss=3.0799 | lr=1.00e-03 | Top1=0.1656 | Top2=0.2827 | Top4=0.4558 | Top8=0.6713 | Top16=0.8673 | Top32=0.9747

Byte 14 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 19/80 | train_loss=3.0996 | val_loss=3.0878 | lr=1.00e-03 | Top1=0.1644 | Top2=0.2953 | Top4=0.4667 | Top8=0.6902 | Top16=0.8584 | Top32=0.9680

Byte 14 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 20/80 | train_loss=3.0540 | val_loss=3.0261 | lr=1.00e-03 | Top1=0.1804 | Top2=0.3060 | Top4=0.4844 | Top8=0.6982 | Top16=0.8820 | Top32=0.9789

Byte 14 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 21/80 | train_loss=2.9831 | val_loss=2.9373 | lr=1.00e-03 | Top1=0.1956 | Top2=0.3253 | Top4=0.5153 | Top8=0.7289 | Top16=0.8960 | Top32=0.9833

Byte 14 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 22/80 | train_loss=2.9186 | val_loss=2.9559 | lr=1.00e-03 | Top1=0.1844 | Top2=0.3262 | Top4=0.5138 | Top8=0.7262 | Top16=0.8962 | Top32=0.9816

Byte 14 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 23/80 | train_loss=2.8705 | val_loss=2.9183 | lr=1.00e-03 | Top1=0.2018 | Top2=0.3362 | Top4=0.5189 | Top8=0.7258 | Top16=0.9024 | Top32=0.9831

Byte 14 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 24/80 | train_loss=2.8137 | val_loss=2.8187 | lr=1.00e-03 | Top1=0.2178 | Top2=0.3611 | Top4=0.5567 | Top8=0.7618 | Top16=0.9140 | Top32=0.9847

Byte 14 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 25/80 | train_loss=2.7516 | val_loss=2.8175 | lr=1.00e-03 | Top1=0.2233 | Top2=0.3660 | Top4=0.5607 | Top8=0.7620 | Top16=0.9162 | Top32=0.9851

Byte 14 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 26/80 | train_loss=2.7087 | val_loss=2.7260 | lr=1.00e-03 | Top1=0.2442 | Top2=0.3931 | Top4=0.5924 | Top8=0.7811 | Top16=0.9271 | Top32=0.9887

Byte 14 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 27/80 | train_loss=2.6433 | val_loss=2.6714 | lr=1.00e-03 | Top1=0.2529 | Top2=0.4111 | Top4=0.6071 | Top8=0.8062 | Top16=0.9371 | Top32=0.9891

Byte 14 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 28/80 | train_loss=2.5762 | val_loss=2.6519 | lr=1.00e-03 | Top1=0.2696 | Top2=0.4269 | Top4=0.6278 | Top8=0.8093 | Top16=0.9340 | Top32=0.9878

Byte 14 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 29/80 | train_loss=2.5294 | val_loss=2.6507 | lr=1.00e-03 | Top1=0.2567 | Top2=0.4293 | Top4=0.6329 | Top8=0.8124 | Top16=0.9378 | Top32=0.9904

Byte 14 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 30/80 | train_loss=2.4925 | val_loss=2.6252 | lr=1.00e-03 | Top1=0.2676 | Top2=0.4369 | Top4=0.6316 | Top8=0.8087 | Top16=0.9442 | Top32=0.9922

Byte 14 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 31/80 | train_loss=2.4368 | val_loss=2.4911 | lr=1.00e-03 | Top1=0.3087 | Top2=0.4944 | Top4=0.6829 | Top8=0.8451 | Top16=0.9531 | Top32=0.9944

Byte 14 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 32/80 | train_loss=2.3815 | val_loss=2.5217 | lr=1.00e-03 | Top1=0.2987 | Top2=0.4749 | Top4=0.6656 | Top8=0.8402 | Top16=0.9482 | Top32=0.9904

Byte 14 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 33/80 | train_loss=2.3302 | val_loss=2.4405 | lr=1.00e-03 | Top1=0.3264 | Top2=0.5060 | Top4=0.6996 | Top8=0.8573 | Top16=0.9560 | Top32=0.9920

Byte 14 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 34/80 | train_loss=2.2676 | val_loss=2.5781 | lr=1.00e-03 | Top1=0.3018 | Top2=0.4598 | Top4=0.6607 | Top8=0.8300 | Top16=0.9469 | Top32=0.9909

Byte 14 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 35/80 | train_loss=2.2185 | val_loss=2.3503 | lr=1.00e-03 | Top1=0.3527 | Top2=0.5398 | Top4=0.7309 | Top8=0.8776 | Top16=0.9624 | Top32=0.9960

Byte 14 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 36/80 | train_loss=2.1564 | val_loss=2.3775 | lr=1.00e-03 | Top1=0.3449 | Top2=0.5342 | Top4=0.7173 | Top8=0.8687 | Top16=0.9596 | Top32=0.9958

Byte 14 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 37/80 | train_loss=2.0881 | val_loss=2.3018 | lr=1.00e-03 | Top1=0.3691 | Top2=0.5418 | Top4=0.7376 | Top8=0.8860 | Top16=0.9684 | Top32=0.9964

Byte 14 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 38/80 | train_loss=2.0436 | val_loss=2.2263 | lr=1.00e-03 | Top1=0.3880 | Top2=0.5744 | Top4=0.7587 | Top8=0.8929 | Top16=0.9713 | Top32=0.9958

Byte 14 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 39/80 | train_loss=1.9766 | val_loss=2.1965 | lr=1.00e-03 | Top1=0.4029 | Top2=0.5916 | Top4=0.7693 | Top8=0.9007 | Top16=0.9693 | Top32=0.9964

Byte 14 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 40/80 | train_loss=1.9072 | val_loss=2.1406 | lr=1.00e-03 | Top1=0.4173 | Top2=0.6007 | Top4=0.7829 | Top8=0.9078 | Top16=0.9736 | Top32=0.9964

Byte 14 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 41/80 | train_loss=1.8684 | val_loss=1.9879 | lr=1.00e-03 | Top1=0.4584 | Top2=0.6484 | Top4=0.8280 | Top8=0.9260 | Top16=0.9824 | Top32=0.9984

Byte 14 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 42/80 | train_loss=1.8232 | val_loss=1.9867 | lr=1.00e-03 | Top1=0.4653 | Top2=0.6460 | Top4=0.8160 | Top8=0.9236 | Top16=0.9811 | Top32=0.9987

Byte 14 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 43/80 | train_loss=1.7678 | val_loss=2.0260 | lr=1.00e-03 | Top1=0.4538 | Top2=0.6300 | Top4=0.8031 | Top8=0.9213 | Top16=0.9784 | Top32=0.9964

Byte 14 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 44/80 | train_loss=1.7028 | val_loss=1.9753 | lr=1.00e-03 | Top1=0.4707 | Top2=0.6556 | Top4=0.8227 | Top8=0.9307 | Top16=0.9842 | Top32=0.9976

Byte 14 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 45/80 | train_loss=1.6658 | val_loss=1.9254 | lr=1.00e-03 | Top1=0.4940 | Top2=0.6678 | Top4=0.8282 | Top8=0.9313 | Top16=0.9800 | Top32=0.9962

Byte 14 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 46/80 | train_loss=1.6200 | val_loss=1.8479 | lr=1.00e-03 | Top1=0.5076 | Top2=0.6896 | Top4=0.8469 | Top8=0.9447 | Top16=0.9862 | Top32=0.9984

Byte 14 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 47/80 | train_loss=1.5700 | val_loss=1.9416 | lr=1.00e-03 | Top1=0.4869 | Top2=0.6662 | Top4=0.8284 | Top8=0.9362 | Top16=0.9880 | Top32=0.9982

Byte 14 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 48/80 | train_loss=1.5183 | val_loss=1.8131 | lr=1.00e-03 | Top1=0.5187 | Top2=0.7040 | Top4=0.8538 | Top8=0.9491 | Top16=0.9884 | Top32=0.9980

Byte 14 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 49/80 | train_loss=1.4803 | val_loss=1.8259 | lr=1.00e-03 | Top1=0.5173 | Top2=0.7049 | Top4=0.8527 | Top8=0.9456 | Top16=0.9900 | Top32=0.9984

Byte 14 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 50/80 | train_loss=1.4495 | val_loss=1.8003 | lr=1.00e-03 | Top1=0.5260 | Top2=0.7158 | Top4=0.8638 | Top8=0.9520 | Top16=0.9856 | Top32=0.9982

Byte 14 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 51/80 | train_loss=1.4063 | val_loss=1.7397 | lr=1.00e-03 | Top1=0.5353 | Top2=0.7300 | Top4=0.8687 | Top8=0.9567 | Top16=0.9907 | Top32=0.9987

Byte 14 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 52/80 | train_loss=1.3710 | val_loss=2.0697 | lr=1.00e-03 | Top1=0.4782 | Top2=0.6542 | Top4=0.8187 | Top8=0.9287 | Top16=0.9789 | Top32=0.9956

Byte 14 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 53/80 | train_loss=1.3538 | val_loss=1.7164 | lr=1.00e-03 | Top1=0.5527 | Top2=0.7404 | Top4=0.8769 | Top8=0.9576 | Top16=0.9904 | Top32=0.9980

Byte 14 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 54/80 | train_loss=1.3160 | val_loss=1.7969 | lr=1.00e-03 | Top1=0.5482 | Top2=0.7296 | Top4=0.8618 | Top8=0.9471 | Top16=0.9878 | Top32=0.9973

Byte 14 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 55/80 | train_loss=1.2836 | val_loss=1.8042 | lr=1.00e-03 | Top1=0.5344 | Top2=0.7169 | Top4=0.8618 | Top8=0.9487 | Top16=0.9889 | Top32=0.9971

Byte 14 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 56/80 | train_loss=1.2563 | val_loss=1.6595 | lr=1.00e-03 | Top1=0.5676 | Top2=0.7562 | Top4=0.8856 | Top8=0.9580 | Top16=0.9887 | Top32=0.9984

Byte 14 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 57/80 | train_loss=1.2238 | val_loss=1.6727 | lr=1.00e-03 | Top1=0.5807 | Top2=0.7487 | Top4=0.8811 | Top8=0.9562 | Top16=0.9896 | Top32=0.9991

Byte 14 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 58/80 | train_loss=1.1944 | val_loss=1.6640 | lr=1.00e-03 | Top1=0.5678 | Top2=0.7536 | Top4=0.8860 | Top8=0.9602 | Top16=0.9924 | Top32=0.9982

Byte 14 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 59/80 | train_loss=1.1662 | val_loss=1.6316 | lr=1.00e-03 | Top1=0.5876 | Top2=0.7620 | Top4=0.8964 | Top8=0.9644 | Top16=0.9898 | Top32=0.9969

Byte 14 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 60/80 | train_loss=1.1377 | val_loss=1.6427 | lr=1.00e-03 | Top1=0.5849 | Top2=0.7638 | Top4=0.8922 | Top8=0.9649 | Top16=0.9913 | Top32=0.9976

Byte 14 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 61/80 | train_loss=1.1214 | val_loss=1.6980 | lr=1.00e-03 | Top1=0.5767 | Top2=0.7513 | Top4=0.8856 | Top8=0.9609 | Top16=0.9880 | Top32=0.9958

Byte 14 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 62/80 | train_loss=1.1004 | val_loss=1.6194 | lr=1.00e-03 | Top1=0.5980 | Top2=0.7720 | Top4=0.8987 | Top8=0.9671 | Top16=0.9920 | Top32=0.9991

Byte 14 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 63/80 | train_loss=1.0673 | val_loss=1.7445 | lr=1.00e-03 | Top1=0.5718 | Top2=0.7529 | Top4=0.8831 | Top8=0.9533 | Top16=0.9884 | Top32=0.9960

Byte 14 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 64/80 | train_loss=1.0532 | val_loss=1.6464 | lr=1.00e-03 | Top1=0.5904 | Top2=0.7656 | Top4=0.8964 | Top8=0.9662 | Top16=0.9911 | Top32=0.9969

Byte 14 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 65/80 | train_loss=1.0187 | val_loss=1.6455 | lr=1.00e-03 | Top1=0.5996 | Top2=0.7778 | Top4=0.8978 | Top8=0.9640 | Top16=0.9904 | Top32=0.9971

Byte 14 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 66/80 | train_loss=0.9962 | val_loss=1.5397 | lr=1.00e-03 | Top1=0.6213 | Top2=0.7882 | Top4=0.9080 | Top8=0.9718 | Top16=0.9929 | Top32=0.9982

Byte 14 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 67/80 | train_loss=0.9872 | val_loss=1.6970 | lr=1.00e-03 | Top1=0.5878 | Top2=0.7616 | Top4=0.8922 | Top8=0.9613 | Top16=0.9891 | Top32=0.9949

Byte 14 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 68/80 | train_loss=0.9653 | val_loss=1.5846 | lr=1.00e-03 | Top1=0.6116 | Top2=0.7833 | Top4=0.9053 | Top8=0.9698 | Top16=0.9909 | Top32=0.9964

Byte 14 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 69/80 | train_loss=0.9562 | val_loss=1.4954 | lr=1.00e-03 | Top1=0.6311 | Top2=0.8113 | Top4=0.9173 | Top8=0.9727 | Top16=0.9933 | Top32=0.9971

Byte 14 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 70/80 | train_loss=0.9390 | val_loss=1.5479 | lr=1.00e-03 | Top1=0.6207 | Top2=0.7947 | Top4=0.9089 | Top8=0.9707 | Top16=0.9924 | Top32=0.9980

Byte 14 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 71/80 | train_loss=0.9239 | val_loss=1.5181 | lr=1.00e-03 | Top1=0.6313 | Top2=0.7991 | Top4=0.9116 | Top8=0.9742 | Top16=0.9922 | Top32=0.9973

Byte 14 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 72/80 | train_loss=0.8948 | val_loss=1.6054 | lr=1.00e-03 | Top1=0.6044 | Top2=0.7864 | Top4=0.9109 | Top8=0.9724 | Top16=0.9907 | Top32=0.9960

Byte 14 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 73/80 | train_loss=0.8792 | val_loss=1.5708 | lr=1.00e-03 | Top1=0.6153 | Top2=0.7929 | Top4=0.9120 | Top8=0.9704 | Top16=0.9924 | Top32=0.9969

Byte 14 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 74/80 | train_loss=0.8656 | val_loss=1.5822 | lr=1.00e-03 | Top1=0.6240 | Top2=0.7869 | Top4=0.9124 | Top8=0.9738 | Top16=0.9929 | Top32=0.9962

Byte 14 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 75/80 | train_loss=0.8451 | val_loss=1.5677 | lr=1.00e-03 | Top1=0.6193 | Top2=0.7869 | Top4=0.9127 | Top8=0.9753 | Top16=0.9940 | Top32=0.9967

Byte 14 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 76/80 | train_loss=0.7309 | val_loss=1.4063 | lr=5.00e-04 | Top1=0.6687 | Top2=0.8309 | Top4=0.9347 | Top8=0.9809 | Top16=0.9944 | Top32=0.9964

Byte 14 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 77/80 | train_loss=0.6971 | val_loss=1.4614 | lr=5.00e-04 | Top1=0.6613 | Top2=0.8293 | Top4=0.9273 | Top8=0.9769 | Top16=0.9911 | Top32=0.9958

Byte 14 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 78/80 | train_loss=0.6781 | val_loss=1.4056 | lr=5.00e-04 | Top1=0.6751 | Top2=0.8342 | Top4=0.9329 | Top8=0.9793 | Top16=0.9911 | Top32=0.9962

Byte 14 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 79/80 | train_loss=0.6692 | val_loss=1.3777 | lr=5.00e-04 | Top1=0.6800 | Top2=0.8404 | Top4=0.9367 | Top8=0.9796 | Top16=0.9942 | Top32=0.9973

Byte 14 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 14 | Epoch 80/80 | train_loss=0.6546 | val_loss=1.5264 | lr=5.00e-04 | Top1=0.6542 | Top2=0.8224 | Top4=0.9176 | Top8=0.9696 | Top16=0.9869 | Top32=0.9907

Finished ASCON byte 14
Best epoch: 79
Test Top-k: {'top1': 0.6679999828338623, 'top2': 0.8282222151756287, 'top4': 0.9300000071525574, 'top8': 0.9784444570541382, 'top16': 0.9919999837875366, 'top32': 0.996666669845581}
Grouped Top4: {'grouped_n1_top4': 0.9300000071525574, 'grouped_n2_top4': 0.9881061315536499, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.01
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_14\byte_14_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_14\byte_14_summary.csv

Loading ASCON byte 15
Byte dir: C:\Users\thetp\Downloads\ASCON_FYP\03_Data\tight_trigger_keybyte_auto30k\ascon_tighttrigger_30k_per_byte_20260526_014007\byte_15
Trace chunks: 30
Metadata chunks: 30
X shape: (30000, 2000)
y shape: (30000,)
Class count: 256
Trace dtype: float32
Train: (21000, 2000) (21000,)
Val:   (4500, 2000) (4500,)
Test:  (4500, 2000) (4500,)

Byte 15 Epoch 01:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 01/80 | train_loss=5.2452 | val_loss=4.8400 | lr=1.00e-03 | Top1=0.0187 | Top2=0.0356 | Top4=0.0673 | Top8=0.1324 | Top16=0.2362 | Top32=0.4142

Byte 15 Epoch 02:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 02/80 | train_loss=4.5688 | val_loss=4.1625 | lr=1.00e-03 | Top1=0.0364 | Top2=0.0671 | Top4=0.1287 | Top8=0.2529 | Top16=0.4262 | Top32=0.6864

Byte 15 Epoch 03:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 03/80 | train_loss=4.1145 | val_loss=3.9784 | lr=1.00e-03 | Top1=0.0404 | Top2=0.0816 | Top4=0.1613 | Top8=0.2911 | Top16=0.4747 | Top32=0.7529

Byte 15 Epoch 04:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 04/80 | train_loss=3.9378 | val_loss=3.8970 | lr=1.00e-03 | Top1=0.0547 | Top2=0.0960 | Top4=0.1693 | Top8=0.3111 | Top16=0.5038 | Top32=0.7793

Byte 15 Epoch 05:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 05/80 | train_loss=3.8271 | val_loss=3.7482 | lr=1.00e-03 | Top1=0.0549 | Top2=0.1047 | Top4=0.1956 | Top8=0.3600 | Top16=0.5902 | Top32=0.8644

Byte 15 Epoch 06:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 06/80 | train_loss=3.7360 | val_loss=3.7082 | lr=1.00e-03 | Top1=0.0622 | Top2=0.1218 | Top4=0.2287 | Top8=0.4113 | Top16=0.6482 | Top32=0.8962

Byte 15 Epoch 07:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 07/80 | train_loss=3.6819 | val_loss=3.7619 | lr=1.00e-03 | Top1=0.0513 | Top2=0.1062 | Top4=0.2004 | Top8=0.3827 | Top16=0.6200 | Top32=0.8902

Byte 15 Epoch 08:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 08/80 | train_loss=3.6032 | val_loss=3.4665 | lr=1.00e-03 | Top1=0.0891 | Top2=0.1607 | Top4=0.2913 | Top8=0.4949 | Top16=0.7347 | Top32=0.9360

Byte 15 Epoch 09:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 09/80 | train_loss=3.5345 | val_loss=3.4672 | lr=1.00e-03 | Top1=0.0969 | Top2=0.1716 | Top4=0.2942 | Top8=0.4953 | Top16=0.7329 | Top32=0.9393

Byte 15 Epoch 10:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 10/80 | train_loss=3.4550 | val_loss=3.3264 | lr=1.00e-03 | Top1=0.1118 | Top2=0.2047 | Top4=0.3602 | Top8=0.5604 | Top16=0.7831 | Top32=0.9529

Byte 15 Epoch 11:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 11/80 | train_loss=3.3775 | val_loss=3.3573 | lr=1.00e-03 | Top1=0.1011 | Top2=0.1958 | Top4=0.3413 | Top8=0.5531 | Top16=0.7809 | Top32=0.9471

Byte 15 Epoch 12:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 12/80 | train_loss=3.3026 | val_loss=3.1859 | lr=1.00e-03 | Top1=0.1373 | Top2=0.2393 | Top4=0.3889 | Top8=0.6129 | Top16=0.8318 | Top32=0.9740

Byte 15 Epoch 13:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 13/80 | train_loss=3.2353 | val_loss=3.1347 | lr=1.00e-03 | Top1=0.1456 | Top2=0.2638 | Top4=0.4298 | Top8=0.6473 | Top16=0.8509 | Top32=0.9789

Byte 15 Epoch 14:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 14/80 | train_loss=3.1450 | val_loss=3.1800 | lr=1.00e-03 | Top1=0.1331 | Top2=0.2442 | Top4=0.4156 | Top8=0.6309 | Top16=0.8373 | Top32=0.9793

Byte 15 Epoch 15:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 15/80 | train_loss=3.0599 | val_loss=2.9556 | lr=1.00e-03 | Top1=0.1869 | Top2=0.3151 | Top4=0.5056 | Top8=0.7149 | Top16=0.8827 | Top32=0.9802

Byte 15 Epoch 16:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 16/80 | train_loss=2.9740 | val_loss=3.0068 | lr=1.00e-03 | Top1=0.1796 | Top2=0.3093 | Top4=0.4987 | Top8=0.7076 | Top16=0.9027 | Top32=0.9853

Byte 15 Epoch 17:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 17/80 | train_loss=2.9038 | val_loss=2.9341 | lr=1.00e-03 | Top1=0.1849 | Top2=0.3187 | Top4=0.5198 | Top8=0.7400 | Top16=0.9104 | Top32=0.9896

Byte 15 Epoch 18:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 18/80 | train_loss=2.8057 | val_loss=2.8053 | lr=1.00e-03 | Top1=0.2316 | Top2=0.3749 | Top4=0.5698 | Top8=0.7616 | Top16=0.9156 | Top32=0.9876

Byte 15 Epoch 19:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 19/80 | train_loss=2.7198 | val_loss=2.6974 | lr=1.00e-03 | Top1=0.2536 | Top2=0.4053 | Top4=0.6104 | Top8=0.8009 | Top16=0.9264 | Top32=0.9882

Byte 15 Epoch 20:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 20/80 | train_loss=2.6585 | val_loss=2.5388 | lr=1.00e-03 | Top1=0.2893 | Top2=0.4504 | Top4=0.6669 | Top8=0.8467 | Top16=0.9549 | Top32=0.9956

Byte 15 Epoch 21:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 21/80 | train_loss=2.5718 | val_loss=2.5182 | lr=1.00e-03 | Top1=0.2942 | Top2=0.4747 | Top4=0.6604 | Top8=0.8413 | Top16=0.9538 | Top32=0.9940

Byte 15 Epoch 22:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 22/80 | train_loss=2.4734 | val_loss=2.4498 | lr=1.00e-03 | Top1=0.2987 | Top2=0.4820 | Top4=0.6867 | Top8=0.8576 | Top16=0.9576 | Top32=0.9938

Byte 15 Epoch 23:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 23/80 | train_loss=2.3875 | val_loss=2.4891 | lr=1.00e-03 | Top1=0.3156 | Top2=0.4807 | Top4=0.6773 | Top8=0.8411 | Top16=0.9513 | Top32=0.9944

Byte 15 Epoch 24:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 24/80 | train_loss=2.3274 | val_loss=2.2324 | lr=1.00e-03 | Top1=0.3676 | Top2=0.5616 | Top4=0.7620 | Top8=0.9020 | Top16=0.9782 | Top32=0.9982

Byte 15 Epoch 25:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 25/80 | train_loss=2.2443 | val_loss=2.2412 | lr=1.00e-03 | Top1=0.3624 | Top2=0.5611 | Top4=0.7593 | Top8=0.9073 | Top16=0.9756 | Top32=0.9978

Byte 15 Epoch 26:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 26/80 | train_loss=2.1494 | val_loss=2.1993 | lr=1.00e-03 | Top1=0.3713 | Top2=0.5753 | Top4=0.7733 | Top8=0.9044 | Top16=0.9778 | Top32=0.9987

Byte 15 Epoch 27:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 27/80 | train_loss=2.0724 | val_loss=2.0457 | lr=1.00e-03 | Top1=0.4182 | Top2=0.6209 | Top4=0.8131 | Top8=0.9311 | Top16=0.9822 | Top32=0.9976

Byte 15 Epoch 28:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 28/80 | train_loss=2.0014 | val_loss=1.9548 | lr=1.00e-03 | Top1=0.4516 | Top2=0.6511 | Top4=0.8322 | Top8=0.9418 | Top16=0.9891 | Top32=0.9987

Byte 15 Epoch 29:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 29/80 | train_loss=1.9398 | val_loss=1.9294 | lr=1.00e-03 | Top1=0.4611 | Top2=0.6582 | Top4=0.8362 | Top8=0.9433 | Top16=0.9882 | Top32=0.9987

Byte 15 Epoch 30:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 30/80 | train_loss=1.8794 | val_loss=1.9261 | lr=1.00e-03 | Top1=0.4667 | Top2=0.6638 | Top4=0.8333 | Top8=0.9440 | Top16=0.9862 | Top32=0.9987

Byte 15 Epoch 31:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 31/80 | train_loss=1.8070 | val_loss=1.9408 | lr=1.00e-03 | Top1=0.4567 | Top2=0.6607 | Top4=0.8318 | Top8=0.9409 | Top16=0.9878 | Top32=0.9980

Byte 15 Epoch 32:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 32/80 | train_loss=1.7608 | val_loss=1.8033 | lr=1.00e-03 | Top1=0.4978 | Top2=0.6969 | Top4=0.8629 | Top8=0.9564 | Top16=0.9929 | Top32=0.9984

Byte 15 Epoch 33:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 33/80 | train_loss=1.7108 | val_loss=1.9357 | lr=1.00e-03 | Top1=0.4660 | Top2=0.6640 | Top4=0.8384 | Top8=0.9424 | Top16=0.9889 | Top32=0.9991

Byte 15 Epoch 34:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 34/80 | train_loss=1.6515 | val_loss=1.7560 | lr=1.00e-03 | Top1=0.5196 | Top2=0.7184 | Top4=0.8658 | Top8=0.9567 | Top16=0.9916 | Top32=0.9980

Byte 15 Epoch 35:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 35/80 | train_loss=1.6045 | val_loss=1.7089 | lr=1.00e-03 | Top1=0.5331 | Top2=0.7222 | Top4=0.8836 | Top8=0.9671 | Top16=0.9929 | Top32=0.9987

Byte 15 Epoch 36:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 36/80 | train_loss=1.5694 | val_loss=1.7806 | lr=1.00e-03 | Top1=0.5067 | Top2=0.7100 | Top4=0.8689 | Top8=0.9596 | Top16=0.9907 | Top32=0.9989

Byte 15 Epoch 37:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 37/80 | train_loss=1.5275 | val_loss=1.6298 | lr=1.00e-03 | Top1=0.5511 | Top2=0.7520 | Top4=0.9020 | Top8=0.9689 | Top16=0.9940 | Top32=0.9987

Byte 15 Epoch 38:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 38/80 | train_loss=1.5078 | val_loss=1.6272 | lr=1.00e-03 | Top1=0.5549 | Top2=0.7576 | Top4=0.9020 | Top8=0.9722 | Top16=0.9931 | Top32=0.9984

Byte 15 Epoch 39:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 39/80 | train_loss=1.4274 | val_loss=1.5841 | lr=1.00e-03 | Top1=0.5736 | Top2=0.7673 | Top4=0.9042 | Top8=0.9760 | Top16=0.9951 | Top32=0.9989

Byte 15 Epoch 40:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 40/80 | train_loss=1.4155 | val_loss=1.6358 | lr=1.00e-03 | Top1=0.5638 | Top2=0.7584 | Top4=0.8987 | Top8=0.9682 | Top16=0.9931 | Top32=0.9982

Byte 15 Epoch 41:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 41/80 | train_loss=1.3803 | val_loss=1.5182 | lr=1.00e-03 | Top1=0.5909 | Top2=0.7838 | Top4=0.9160 | Top8=0.9796 | Top16=0.9951 | Top32=0.9984

Byte 15 Epoch 42:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 42/80 | train_loss=1.3443 | val_loss=1.6285 | lr=1.00e-03 | Top1=0.5778 | Top2=0.7642 | Top4=0.9000 | Top8=0.9707 | Top16=0.9944 | Top32=0.9980

Byte 15 Epoch 43:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 43/80 | train_loss=1.3272 | val_loss=1.6337 | lr=1.00e-03 | Top1=0.5740 | Top2=0.7633 | Top4=0.9020 | Top8=0.9713 | Top16=0.9933 | Top32=0.9980

Byte 15 Epoch 44:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 44/80 | train_loss=1.2836 | val_loss=1.6016 | lr=1.00e-03 | Top1=0.5702 | Top2=0.7653 | Top4=0.9071 | Top8=0.9740 | Top16=0.9942 | Top32=0.9987

Byte 15 Epoch 45:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 45/80 | train_loss=1.2646 | val_loss=1.5134 | lr=1.00e-03 | Top1=0.5991 | Top2=0.7871 | Top4=0.9180 | Top8=0.9802 | Top16=0.9953 | Top32=0.9989

Byte 15 Epoch 46:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 46/80 | train_loss=1.2310 | val_loss=1.5446 | lr=1.00e-03 | Top1=0.5969 | Top2=0.7889 | Top4=0.9149 | Top8=0.9769 | Top16=0.9938 | Top32=0.9982

Byte 15 Epoch 47:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 47/80 | train_loss=1.2208 | val_loss=1.4906 | lr=1.00e-03 | Top1=0.6053 | Top2=0.7984 | Top4=0.9209 | Top8=0.9796 | Top16=0.9958 | Top32=0.9987

Byte 15 Epoch 48:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 48/80 | train_loss=1.1942 | val_loss=1.4627 | lr=1.00e-03 | Top1=0.6244 | Top2=0.8056 | Top4=0.9302 | Top8=0.9804 | Top16=0.9951 | Top32=0.9980

Byte 15 Epoch 49:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 49/80 | train_loss=1.1587 | val_loss=1.4960 | lr=1.00e-03 | Top1=0.6124 | Top2=0.7993 | Top4=0.9191 | Top8=0.9773 | Top16=0.9953 | Top32=0.9984

Byte 15 Epoch 50:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 50/80 | train_loss=1.1330 | val_loss=1.5080 | lr=1.00e-03 | Top1=0.6096 | Top2=0.7938 | Top4=0.9180 | Top8=0.9778 | Top16=0.9949 | Top32=0.9984

Byte 15 Epoch 51:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 51/80 | train_loss=1.1010 | val_loss=1.5294 | lr=1.00e-03 | Top1=0.6109 | Top2=0.7931 | Top4=0.9240 | Top8=0.9791 | Top16=0.9953 | Top32=0.9984

Byte 15 Epoch 52:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 52/80 | train_loss=1.0938 | val_loss=1.4760 | lr=1.00e-03 | Top1=0.6344 | Top2=0.8113 | Top4=0.9273 | Top8=0.9822 | Top16=0.9953 | Top32=0.9978

Byte 15 Epoch 53:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 53/80 | train_loss=1.0719 | val_loss=1.3946 | lr=1.00e-03 | Top1=0.6409 | Top2=0.8178 | Top4=0.9349 | Top8=0.9816 | Top16=0.9951 | Top32=0.9978

Byte 15 Epoch 54:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 54/80 | train_loss=1.0424 | val_loss=1.4791 | lr=1.00e-03 | Top1=0.6253 | Top2=0.8058 | Top4=0.9247 | Top8=0.9778 | Top16=0.9956 | Top32=0.9984

Byte 15 Epoch 55:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 55/80 | train_loss=1.0388 | val_loss=1.4947 | lr=1.00e-03 | Top1=0.6264 | Top2=0.8060 | Top4=0.9209 | Top8=0.9778 | Top16=0.9953 | Top32=0.9980

Byte 15 Epoch 56:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 56/80 | train_loss=1.0204 | val_loss=1.4107 | lr=1.00e-03 | Top1=0.6482 | Top2=0.8260 | Top4=0.9327 | Top8=0.9798 | Top16=0.9944 | Top32=0.9980

Byte 15 Epoch 57:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 57/80 | train_loss=0.9873 | val_loss=1.4032 | lr=1.00e-03 | Top1=0.6549 | Top2=0.8240 | Top4=0.9331 | Top8=0.9844 | Top16=0.9967 | Top32=0.9991

Byte 15 Epoch 58:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 58/80 | train_loss=0.9607 | val_loss=1.3710 | lr=1.00e-03 | Top1=0.6638 | Top2=0.8322 | Top4=0.9400 | Top8=0.9836 | Top16=0.9967 | Top32=0.9982

Byte 15 Epoch 59:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 59/80 | train_loss=0.9484 | val_loss=1.3607 | lr=1.00e-03 | Top1=0.6689 | Top2=0.8391 | Top4=0.9429 | Top8=0.9836 | Top16=0.9960 | Top32=0.9984

Byte 15 Epoch 60:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 60/80 | train_loss=0.9225 | val_loss=1.3602 | lr=1.00e-03 | Top1=0.6716 | Top2=0.8427 | Top4=0.9464 | Top8=0.9831 | Top16=0.9960 | Top32=0.9982

Byte 15 Epoch 61:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 61/80 | train_loss=0.9015 | val_loss=1.3740 | lr=1.00e-03 | Top1=0.6798 | Top2=0.8409 | Top4=0.9451 | Top8=0.9836 | Top16=0.9956 | Top32=0.9976

Byte 15 Epoch 62:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 62/80 | train_loss=0.8901 | val_loss=1.3151 | lr=1.00e-03 | Top1=0.6856 | Top2=0.8529 | Top4=0.9513 | Top8=0.9869 | Top16=0.9962 | Top32=0.9984

Byte 15 Epoch 63:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 63/80 | train_loss=0.8748 | val_loss=1.3649 | lr=1.00e-03 | Top1=0.6787 | Top2=0.8411 | Top4=0.9442 | Top8=0.9816 | Top16=0.9953 | Top32=0.9971

Byte 15 Epoch 64:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 64/80 | train_loss=0.8641 | val_loss=1.3017 | lr=1.00e-03 | Top1=0.6944 | Top2=0.8582 | Top4=0.9478 | Top8=0.9842 | Top16=0.9949 | Top32=0.9964

Byte 15 Epoch 65:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 65/80 | train_loss=0.8432 | val_loss=1.3361 | lr=1.00e-03 | Top1=0.6873 | Top2=0.8493 | Top4=0.9487 | Top8=0.9862 | Top16=0.9947 | Top32=0.9967

Byte 15 Epoch 66:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 66/80 | train_loss=0.8304 | val_loss=1.3860 | lr=1.00e-03 | Top1=0.6760 | Top2=0.8427 | Top4=0.9440 | Top8=0.9836 | Top16=0.9940 | Top32=0.9964

Byte 15 Epoch 67:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 67/80 | train_loss=0.8205 | val_loss=1.2958 | lr=1.00e-03 | Top1=0.7009 | Top2=0.8636 | Top4=0.9529 | Top8=0.9856 | Top16=0.9949 | Top32=0.9967

Byte 15 Epoch 68:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 68/80 | train_loss=0.8027 | val_loss=1.4539 | lr=1.00e-03 | Top1=0.6607 | Top2=0.8284 | Top4=0.9371 | Top8=0.9787 | Top16=0.9918 | Top32=0.9951

Byte 15 Epoch 69:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 69/80 | train_loss=0.7860 | val_loss=1.2613 | lr=1.00e-03 | Top1=0.7089 | Top2=0.8631 | Top4=0.9558 | Top8=0.9880 | Top16=0.9971 | Top32=0.9982

Byte 15 Epoch 70:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 70/80 | train_loss=0.7750 | val_loss=1.2988 | lr=1.00e-03 | Top1=0.7020 | Top2=0.8616 | Top4=0.9513 | Top8=0.9856 | Top16=0.9949 | Top32=0.9976

Byte 15 Epoch 71:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 71/80 | train_loss=0.7686 | val_loss=1.3668 | lr=1.00e-03 | Top1=0.7018 | Top2=0.8536 | Top4=0.9462 | Top8=0.9824 | Top16=0.9913 | Top32=0.9947

Byte 15 Epoch 72:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 72/80 | train_loss=0.7434 | val_loss=1.2558 | lr=1.00e-03 | Top1=0.7144 | Top2=0.8682 | Top4=0.9509 | Top8=0.9853 | Top16=0.9947 | Top32=0.9973

Byte 15 Epoch 73:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 73/80 | train_loss=0.7440 | val_loss=1.2689 | lr=1.00e-03 | Top1=0.7118 | Top2=0.8664 | Top4=0.9553 | Top8=0.9880 | Top16=0.9956 | Top32=0.9980

Byte 15 Epoch 74:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 74/80 | train_loss=0.7414 | val_loss=1.3530 | lr=1.00e-03 | Top1=0.7024 | Top2=0.8509 | Top4=0.9480 | Top8=0.9820 | Top16=0.9909 | Top32=0.9947

Byte 15 Epoch 75:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 75/80 | train_loss=0.7167 | val_loss=1.4120 | lr=1.00e-03 | Top1=0.6898 | Top2=0.8422 | Top4=0.9411 | Top8=0.9809 | Top16=0.9907 | Top32=0.9940

Byte 15 Epoch 76:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 76/80 | train_loss=0.6197 | val_loss=1.2604 | lr=5.00e-04 | Top1=0.7289 | Top2=0.8744 | Top4=0.9518 | Top8=0.9847 | Top16=0.9944 | Top32=0.9964

Byte 15 Epoch 77:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 77/80 | train_loss=0.5947 | val_loss=1.1561 | lr=5.00e-04 | Top1=0.7527 | Top2=0.8884 | Top4=0.9627 | Top8=0.9891 | Top16=0.9960 | Top32=0.9978

Byte 15 Epoch 78:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 78/80 | train_loss=0.5828 | val_loss=1.1563 | lr=5.00e-04 | Top1=0.7480 | Top2=0.8893 | Top4=0.9647 | Top8=0.9896 | Top16=0.9951 | Top32=0.9969

Byte 15 Epoch 79:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 79/80 | train_loss=0.5755 | val_loss=1.1365 | lr=5.00e-04 | Top1=0.7480 | Top2=0.8911 | Top4=0.9658 | Top8=0.9909 | Top16=0.9971 | Top32=0.9978

Byte 15 Epoch 80:   0%|          | 0/165 [00:00<?, ?it/s]

Byte 15 | Epoch 80/80 | train_loss=0.5664 | val_loss=1.1004 | lr=5.00e-04 | Top1=0.7607 | Top2=0.8967 | Top4=0.9684 | Top8=0.9904 | Top16=0.9967 | Top32=0.9978

Finished ASCON byte 15
Best epoch: 80
Test Top-k: {'top1': 0.7513333559036255, 'top2': 0.8853333592414856, 'top4': 0.9624444246292114, 'top8': 0.9868888854980469, 'top16': 0.9944444298744202, 'top32': 0.9968888759613037}
Grouped Top4: {'grouped_n1_top4': 0.9624444246292114, 'grouped_n2_top4': 0.9944979548454285, 'grouped_n4_top4': 1.0, 'grouped_n8_top4': 1.0, 'grouped_n12_top4': 1.0, 'grouped_n16_top4': 1.0}
Elapsed minutes: 12.00
Saved model: C:\Users\thetp\Downloads\ASCON_FYP\05_Models\ascon_cnn256_topk_training\run_20260527_140605\byte_15\byte_15_ascon_cnn256_rescnn_best.pt
Saved summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\byte_15\byte_15_summary.csv

All requested ASCON bytes finished.
Elapsed hours: 3.13
Saved all-byte summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\summary_results_ascon_cnn256_rescnn.csv

,target_byte,algorithm,model,best_epoch,best_val_top4,test_loss,elapsed_minutes,train_size,val_size,test_size,class_count_total,trace_len,top1,top2,top4,top8,top16,top32,grouped_n1_groups,grouped_n1_top1,grouped_n1_top2,grouped_n1_top4,grouped_n1_top8,grouped_n1_top16,grouped_n1_top32,grouped_n2_groups,grouped_n2_top1,grouped_n2_top2,grouped_n2_top4,grouped_n2_top8,grouped_n2_top16,grouped_n2_top32,grouped_n4_groups,grouped_n4_top1,grouped_n4_top2,grouped_n4_top4,grouped_n4_top8,grouped_n4_top16,grouped_n4_top32,grouped_n8_groups,grouped_n8_top1,grouped_n8_top2,grouped_n8_top4,grouped_n8_top8,grouped_n8_top16,grouped_n8_top32,grouped_n12_groups,grouped_n12_top1,grouped_n12_top2,grouped_n12_top4,grouped_n12_top8,grouped_n12_top16,grouped_n12_top32,grouped_n16_groups,grouped_n16_top1,grouped_n16_top2,grouped_n16_top4,grouped_n16_top8,grouped_n16_top16,grouped_n16_top32
0,0,ASCON-AEAD-128,CNN256ResCNN1D,62,1.000000,0.443632,11.978776,21000,4500,4500,256,2000,0.969333,0.994889,0.999556,1.000000,1.000000,1.000000,4500,0.969333,0.994889,0.999556,1.000000,1.000000,1.000000,2180,0.996330,0.999083,1.000000,1.000000,1.000000,1.000000,1029,0.999028,1.000000,1.000000,1.000000,1.000000,1.0,486,1.000000,1.000000,1.000000,1.0,1.0,1.0,256,1.000000,1.000000,1.000000,1.0,1.0,1.0,230,1.000000,1.000000,1.0,1.0,1.0,1.0
1,1,ASCON-AEAD-128,CNN256ResCNN1D,61,0.993556,0.767435,11.405698,21000,4500,4500,256,2000,0.855111,0.958889,0.989333,0.998000,1.000000,1.000000,4500,0.855111,0.958889,0.989333,0.998000,1.000000,1.000000,2187,0.955190,0.991770,0.999085,1.000000,1.000000,1.000000,1026,0.994152,1.000000,1.000000,1.000000,1.000000,1.0,485,1.000000,1.000000,1.000000,1.0,1.0,1.0,256,0.996094,1.000000,1.000000,1.0,1.0,1.0,229,1.000000,1.000000,1.0,1.0,1.0,1.0
2,2,ASCON-AEAD-128,CNN256ResCNN1D,69,0.922444,1.588159,11.999097,21000,4500,4500,256,2000,0.601556,0.792000,0.920000,0.980000,0.992667,0.997111,4500,0.601556,0.792000,0.920000,0.980000,0.992667,0.997111,2188,0.776508,0.921389,0.984004,0.998172,0.999543,0.999543,1030,0.916505,0.983495,0.998058,1.000000,1.000000,1.0,486,0.944444,0.997942,1.000000,1.0,1.0,1.0,257,0.976654,1.000000,1.000000,1.0,1.0,1.0,229,0.978166,1.000000,1.0,1.0,1.0,1.0
3,3,ASCON-AEAD-128,CNN256ResCNN1D,76,0.995778,0.680081,12.049367,21000,4500,4500,256,2000,0.888222,0.970667,0.994444,0.999111,1.000000,1.000000,4500,0.888222,0.970667,0.994444,0.999111,1.000000,1.000000,2185,0.975286,0.999542,1.000000,1.000000,1.000000,1.000000,1027,0.994158,1.000000,1.000000,1.000000,1.000000,1.0,487,1.000000,1.000000,1.000000,1.0,1.0,1.0,256,1.000000,1.000000,1.000000,1.0,1.0,1.0,231,1.000000,1.000000,1.0,1.0,1.0,1.0
4,4,ASCON-AEAD-128,CNN256ResCNN1D,71,0.714667,2.543880,12.015820,21000,4500,4500,256,2000,0.335333,0.520000,0.708889,0.868222,0.960222,0.990222,4500,0.335333,0.520000,0.708889,0.868222,0.960222,0.990222,2187,0.486054,0.681299,0.862369,0.964792,0.994056,0.999543,1024,0.661133,0.838867,0.951172,0.990234,0.998047,1.0,482,0.765560,0.914938,0.993776,1.0,1.0,1.0,256,0.812500,0.941406,0.992188,1.0,1.0,1.0,226,0.880531,0.964602,1.0,1.0,1.0,1.0
5,5,ASCON-AEAD-128,CNN256ResCNN1D,78,0.960444,1.161214,12.061112,21000,4500,4500,256,2000,0.738667,0.884000,0.965778,0.992667,0.997333,0.998222,4500,0.738667,0.884000,0.965778,0.992667,0.997333,0.998222,2191,0.885897,0.970333,0.994067,0.999087,0.999544,1.000000,1030,0.958252,0.997087,0.999029,1.000000,1.000000,1.0,486,0.985597,1.000000,1.000000,1.0,1.0,1.0,256,0.988281,1.000000,1.000000,1.0,1.0,1.0,230,1.000000,1.000000,1.0,1.0,1.0,1.0
6,6,ASCON-AEAD-128,CNN256ResCNN1D,75,0.917111,1.525284,12.022944,21000,4500,4500,256,2000,0.619556,0.793778,0.910889,0.970444,0.992889,0.998444,4500,0.619556,0.793778,0.910889,0.970444,0.992889,0.998444,2183,0.837380,0.947320,0.983509,0.996335,1.000000,1.000000,1034,0.955513,0.993230,1.000000,1.000000,1.000000,1.0,491,0.977597,1.000000,1.000000,1.0,1.0,1.0,256,0.996094,1.000000,1.000000,1.0,1.0,1.0,235,0.995745,1.000000,1.0,1.0,1.0,1.0
7,7,ASCON-AEAD-128,CNN256ResCNN1D,77,0.957778,1.302905,12.016688,21000,4500,4500,256,2000,0.707333,0.858667,0.945778,0.985111,0.993333,0.995556,4500,0.707333,0.858667,0.945778,0.985111,0.993333,0.995556,2176,0.880974,0.966452,0.992647,0.998621,1.000000,1.000000,1028,0.975681,0.998055,1.000000,1.000000,1.000000,1.0,486,0.993827,1.000000,1.000000,1.0,1.0,1.0,256,1.000000,1.000000,1.000000,1.0,1.0,1.0,230,1.000000,1.000000,1.0,1.0,1.0,1.0
8,8,ASCON-AEAD-128,CNN256ResCNN1D,39,1.000000,0.507402,8.125734,21000,4500,4500,256,2000,0.972222,0.996667,1.000000,1.000000,1.000000,1.000000,4500,0.972222,0.996667,1.000000,1.000000,1.000000,1.000000,2188,0.992230,0.999543,1.000000,1.000000,1.000000,1.000000,1034,0.997099,1.000000,1.000000,1.000000,1.000000,1.0,484,1.000000,1.000000,1.000000,1.0,1.0,1.0,256,1.000000,1.000000,1.000000,1.0,1.0,1.0,228,1.000000,1.000000,1.0,1.0,1.0,1.0
9,9,ASCON-AEAD-128,CNN256ResCNN1D,80,0.909778,1.658164,12.025630,21000,4500,4500,256,2000,0.583111,0.780000,0.909556,0.972222,0.990222,0.993556,4500,0.583111,0.780000,0.909556,0.972222,0.990222,0.993556,2180,0.775688,0.926606,0.984862,0.997248,0.999541,1.000000,1021,0.884427,0.986288,0.999021,1.000000,1.000000,1.0,481,0.952183,0.997921,1.000000,1.0,1.0,1.0,256,0.957031,1.000000,1.000000,1.0,1.0,1.0,225,0.968889,1.000000,1.0,1.0,1.0,1.0
10,10,ASCON-AEAD-128,CNN256ResCNN1D,77,0.962444,1.201595,12.023338,21000,4500,4500,256,2000,0.707556,0.876444,0.962000,0.990000,0.997333,0.998444,4500,0.707556,0.876444,0.962000,0.990000,0.997333,0.998444,2191,0.866271,0.968964,0.997718,1.000000,1.000000,1.000000,1042,0.946257,0.990403,1.000000,1.000000,1.000000,1.0,489,0.989775,1.000000,1.000000,1.0,1.0,1.0,256,0.996094,1.000000,1.000000,1.0,1.0,1.0,233,0.995708,1.000000,1.0,1.0,1.0,1.0
11,11,ASCON-AEAD-128,CNN256ResCNN1D,80,0.992000,0.709862,12.021310,21000,4500,4500,256,2000,0.884889,0.964000,0.990667,0.996667,0.997778,0.999333,4500,0.884889,0.964000,0.990667,0.996667,0.997778,0.999333,2182,0.970211,0.996792,0.999542,1.000000,1.000000,1.000000,1028,0.991245,0.999027,1.000000,1.000000,1.000000,1.0,482,0.997925,1.000000,1.000000,1.0,1.0,1.0,256,0.996094,1.000000,1.000000,1.0,1.0,1.0,226,1.000000,1.000000,1.0,1.0,1.0,1.0
12,12,ASCON-AEAD-128,CNN256ResCNN1D,79,0.730444,2.534969,12.022431,21000,4500,4500,256,2000,0.388000,0.563111,0.737111,0.877556,0.953556,0.987111,4500,0.388000,0.563111,0.737111,0.877556,0.953556,0.987111,2183,0.559780,0.748053,0.885479,0.965644,0.994045,0.999542,1025,0.752195,0.901463,0.971707,0.996098,0.999024,1.0,485,0.872165,0.979381,1.000000,1.0,1.0,1.0,256,0.902344,0.980469,1.000000,1.0,1.0,1.0,229,0.934498,0.986900,1.0,1.0,1.0,1.0
13,13,ASCON-AEAD-128,CNN256ResCNN1D,77,0.930000,1.515936,12.038120,21000,4500,4500,256,2000,0.632222,0.806000,0.930667,0.981111,0.994444,0.996000,4500,0.632222,0.806000,0.930667,0.981111,0.994444,0.996000,2185,0.815103,0.935927,0.984897,0.998169,1.000000,1.000000,1033,0.928364,0.987415,0.999032,1.000000,1.000000,1.0,489,0.977505,0.995910,1.000000,1.0,1.0,1.0,256,0.988281,1.000000,1.000000,1.0,1.0,1.0,233,0.991416,1.000000,1.0,1.0,1.0,1.0
14,14,ASCON-AEAD-128,CNN256ResCNN1D,79,0.936667,1.415978,12.006511,21000,4500,4500,256,2000,0.668000,0.828222,0.930000,0.978444,0.992000,0.996667,4500,0.668000,0.828222,0.930000,0.978444,0.992000,0.996667,2186,0.855444,0.954712,0.988106,0.997713,1.000000,1.000000,1028,0.958171,0.994163,1.000000,1.000000,1.000000,1.0,484,0.989669,1.000000,1.000000,1.0,1.0,1.0,256,0.992188,1.000000,1.000000,1.0,1.0,1.0,228,1.000000,1.000000,1.0,1.0,1.0,1.0
15,15,ASCON-AEAD-128,CNN256ResCNN1D,80,0.968444,1.150056,11.995674,21000,4500,4500,256,2000,0.751333,0.885333,0.962444,0.986889,0.994444,0.996889,4500,0.751333,0.885333,0.962444,0.986889,0.994444,0.996889,2181,0.915635,0.977075,0.994498,0.999542,1.000000,1.000000,1025,0.983415,0.995122,1.000000,1.000000,1.000000,1.0,488,0.995902,1.000000,1.000000,1.0,1.0,1.0,256,1.000000,1.000000,1.000000,1.0,1.0,1.0,232,1.000000,1.000000,1.0,1.0,1.0,1.0

## 12. Candidate-Space Reduction Summary

In [12]:
def candidate_space_power(k, n_bytes=16):
    return n_bytes * math.log2(k)


def build_single_trace_candidate_summary(summary_df):
    rows = []
    for k in TOPK_VALUES:
        col = f"top{k}"
        if col not in summary_df.columns:
            continue
        values = summary_df[col].astype(float).values
        weakest_idx = int(np.nanargmin(values))
        weakest_byte = int(summary_df.loc[weakest_idx, "target_byte"])
        weakest_value = float(values[weakest_idx])
        avg_value = float(np.nanmean(values))
        full_key_inclusion_estimate = float(np.nanprod(values))
        log2_space = candidate_space_power(k, n_bytes=16)
        rows.append({
            "setting": f"single_trace_top{k}",
            "k": k,
            "average_byte_accuracy": avg_value,
            "weakest_byte": weakest_byte,
            "weakest_byte_accuracy": weakest_value,
            "estimated_full_key_inclusion_probability": full_key_inclusion_estimate,
            "candidate_space_expression": f"{k}^16",
            "candidate_space_log2": log2_space,
            "candidate_space_as_power_of_2": f"2^{log2_space:.0f}" if abs(log2_space - round(log2_space)) < 1e-9 else f"2^{log2_space:.2f}",
        })
    return pd.DataFrame(rows)


def build_grouped_candidate_summary(summary_df):
    rows = []
    for n in GROUP_SIZES:
        for k in TOPK_VALUES:
            col = f"grouped_n{n}_top{k}"
            if col not in summary_df.columns:
                continue
            values = summary_df[col].astype(float).values
            if np.all(np.isnan(values)):
                continue
            weakest_idx = int(np.nanargmin(values))
            weakest_byte = int(summary_df.loc[weakest_idx, "target_byte"])
            weakest_value = float(values[weakest_idx])
            avg_value = float(np.nanmean(values))
            full_key_inclusion_estimate = float(np.nanprod(values))
            log2_space = candidate_space_power(k, n_bytes=16)
            rows.append({
                "setting": f"grouped_n{n}_top{k}",
                "group_size": n,
                "k": k,
                "average_byte_accuracy": avg_value,
                "weakest_byte": weakest_byte,
                "weakest_byte_accuracy": weakest_value,
                "estimated_full_key_inclusion_probability": full_key_inclusion_estimate,
                "candidate_space_expression": f"{k}^16",
                "candidate_space_log2": log2_space,
                "candidate_space_as_power_of_2": f"2^{log2_space:.0f}" if abs(log2_space - round(log2_space)) < 1e-9 else f"2^{log2_space:.2f}",
            })
    return pd.DataFrame(rows)

single_candidate_df = build_single_trace_candidate_summary(summary_df)
grouped_candidate_df = build_grouped_candidate_summary(summary_df)

single_path = RESULTS_ROOT / "candidate_space_summary_single_trace_ascon.csv"
grouped_path = RESULTS_ROOT / "candidate_space_summary_grouped_ascon.csv"

single_candidate_df.to_csv(single_path, index=False)
grouped_candidate_df.to_csv(grouped_path, index=False)

print("Saved single-trace candidate summary:", single_path)
print("Saved grouped candidate summary:", grouped_path)

display(single_candidate_df)
if not grouped_candidate_df.empty:
    display(grouped_candidate_df[grouped_candidate_df["setting"].str.contains("top4")].sort_values("group_size"))
else:
    print("No grouped candidate summary available.")

Saved single-trace candidate summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\candidate_space_summary_single_trace_ascon.csv
Saved grouped candidate summary: C:\Users\thetp\Downloads\ASCON_FYP\04_Results\ascon_cnn256_topk_training\run_20260527_140605\candidate_space_summary_grouped_ascon.csv

              setting   k  average_byte_accuracy  weakest_byte  weakest_byte_accuracy  estimated_full_key_inclusion_probability candidate_space_expression  candidate_space_log2 candidate_space_as_power_of_2
0   single_trace_top1   1               0.706403             4               0.335333                                  0.002101                       1^16                   0.0                           2^0
1   single_trace_top2   2               0.842042             4               0.520000                                  0.050228                       2^16                  16.0                          2^16
2   single_trace_top4   4               0.928569             4               0.708889                                  0.284018                       4^16                  32.0                          2^32
3   single_trace_top8   8               0.973528             4               0.868222                                  0.642109                       8^16                  48.0                          2^48
4  single_trace_top16  16               0.991014            12               0.953556                                  0.864245                      16^16                  64.0                          2^64
5  single_trace_top32  32               0.996722            12               0.987111                                  0.948727                      32^16                  80.0                          2^80

             setting  group_size  k  average_byte_accuracy  weakest_byte  weakest_byte_accuracy  estimated_full_key_inclusion_probability candidate_space_expression  candidate_space_log2 candidate_space_as_power_of_2
2    grouped_n1_top4           1  4               0.928569             4               0.708889                                  0.284018                       4^16                  32.0                          2^32
8    grouped_n2_top4           2  4               0.978174             4               0.862369                                  0.692535                       4^16                  32.0                          2^32
14   grouped_n4_top4           4  4               0.994876             4               0.951172                                  0.919777                       4^16                  32.0                          2^32
20   grouped_n8_top4           8  4               0.999611             4               0.993776                                  0.993776                       4^16                  32.0                          2^32
26  grouped_n12_top4          12  4               0.999512             4               0.992188                                  0.992188                       4^16                  32.0                          2^32
32  grouped_n16_top4          16  4               1.000000             0               1.000000                                  1.000000                       4^16                  32.0                          2^32

## 13. Quick Result View

In [13]:
cols = [
    "target_byte", "best_epoch", "best_val_top4",
    "top1", "top2", "top4", "top8", "top16", "top32",
    "grouped_n2_top4", "grouped_n4_top4", "grouped_n8_top4", "grouped_n12_top4", "grouped_n16_top4",
]
cols = [c for c in cols if c in summary_df.columns]
summary_df[cols]

    target_byte  best_epoch  best_val_top4      top1      top2      top4      top8     top16     top32  grouped_n2_top4  grouped_n4_top4  grouped_n8_top4  grouped_n12_top4  grouped_n16_top4
0             0          62       1.000000  0.969333  0.994889  0.999556  1.000000  1.000000  1.000000         1.000000         1.000000         1.000000          1.000000               1.0
1             1          61       0.993556  0.855111  0.958889  0.989333  0.998000  1.000000  1.000000         0.999085         1.000000         1.000000          1.000000               1.0
2             2          69       0.922444  0.601556  0.792000  0.920000  0.980000  0.992667  0.997111         0.984004         0.998058         1.000000          1.000000               1.0
3             3          76       0.995778  0.888222  0.970667  0.994444  0.999111  1.000000  1.000000         1.000000         1.000000         1.000000          1.000000               1.0
4             4          71       0.714667  0.335333  0.520000  0.708889  0.868222  0.960222  0.990222         0.862369         0.951172         0.993776          0.992188               1.0
5             5          78       0.960444  0.738667  0.884000  0.965778  0.992667  0.997333  0.998222         0.994067         0.999029         1.000000          1.000000               1.0
6             6          75       0.917111  0.619556  0.793778  0.910889  0.970444  0.992889  0.998444         0.983509         1.000000         1.000000          1.000000               1.0
7             7          77       0.957778  0.707333  0.858667  0.945778  0.985111  0.993333  0.995556         0.992647         1.000000         1.000000          1.000000               1.0
8             8          39       1.000000  0.972222  0.996667  1.000000  1.000000  1.000000  1.000000         1.000000         1.000000         1.000000          1.000000               1.0
9             9          80       0.909778  0.583111  0.780000  0.909556  0.972222  0.990222  0.993556         0.984862         0.999021         1.000000          1.000000               1.0
10           10          77       0.962444  0.707556  0.876444  0.962000  0.990000  0.997333  0.998444         0.997718         1.000000         1.000000          1.000000               1.0
11           11          80       0.992000  0.884889  0.964000  0.990667  0.996667  0.997778  0.999333         0.999542         1.000000         1.000000          1.000000               1.0
12           12          79       0.730444  0.388000  0.563111  0.737111  0.877556  0.953556  0.987111         0.885479         0.971707         1.000000          1.000000               1.0
13           13          77       0.930000  0.632222  0.806000  0.930667  0.981111  0.994444  0.996000         0.984897         0.999032         1.000000          1.000000               1.0
14           14          79       0.936667  0.668000  0.828222  0.930000  0.978444  0.992000  0.996667         0.988106         1.000000         1.000000          1.000000               1.0
15           15          80       0.968444  0.751333  0.885333  0.962444  0.986889  0.994444  0.996889         0.994498         1.000000         1.000000          1.000000               1.0

## Notes

For ASCON, this notebook follows the agreed folder rule:

```text
03_Data   = traces only
04_Results = training CSVs, summaries, plots, predictions, split mappings
05_Models  = .pt model checkpoints only
```

If CUDA runs out of memory, stop the notebook, change `BATCH_SIZE = 64`, and rerun from the beginning.